# Testing

### In brief

> A single statistical model can test many different hypotheses. Sometimes these
> hypotheses can, superficially, sound similar---but selecting the relevant test
> and reporting it correctly can sometimes be a challange. R packages exist to
> make specifying and reporting tests easier, but none can automate the process:
> Testing hypotheses always requires thought about both the research question in
> hand alongside statistical issues. The replication crisis has brought renewed
> focus on the pitfalls of multiple testing and researcher degrees of freedom.
> Both technical strategies and research policies can mitigate this risk to some
> degree, but research integrity is crucial.

## Session 1: Planned contrasts with `emmeans`

In this session we primarily cover the `emmeans` library and ways to test
planned contrasts in an experimental design.

<!--


When performing statistical tests, I always keep in mind this quote from the
famous scientist Richard Feynman:

> The first principle is that you must not fool yourself and you are the easiest
> person to fool.
> [Feynman, 1974](http://calteches.library.caltech.edu/51/2/CargoCult.htm)


 -->
