## Bayesian estimation of the

### How does this all work? {#extra-bayes-explain}

Behind the scenes, the model is being used to _simulate_ new data: `add_fitted_samples` does
thousands of simulations for what the average prediction will be, and then the `mean_qi` function
summarises them, giving us mean, and the 2.5 and 97.5th percentiles. That is, we say in 95% of the
simulations the mean was between `conf.low` and `conf.high`.

Because of the way the model was fitted, this is the same as making real probability statements
about our prediction.

It might be useful to know that these simulations are said to be _samples from the posterior
distribution_ --- that is, the distribution of probabilities once we combined our data with our
_prior probability_.

##### Why doesn't this work on my laptop or at home?

The `rstanarm` package is
[slightly fiddly to install](https://github.com/plymouthPsychology/installR), and if you don't get
it right then this code won't work.

We've done it for you on university computers though, and on the RStudio server that you have login
details for. So you if you want to run this at home use
[RStudio server](https://rstudio.plymouth.ac.uk/).



### Why do my results differ from yours? {#explain-bayes-variation}

Because of the way the Bayesian models are fitted, there is normally some variation in the results
each time you run the program. This means different people will get (slightly) different answers.

This is usual, and nothing to worry about: the amount of variation is typically small. If you see large differences it normally means something else has gone wrong.

However, when fitting complex models we do sometimes need to minimise the amount of variation.  This is quite a complex topic, not covered in this course, but if you were interested see Jon Kruschke's excellent textbook [@kruschke2014doing] or Richard McElreaths' *Rethinking* book [@mcelreath2018statistical].

However, the short version is that we need to increase the number of simulations the software uses to calculate estimates and intervals. You can do this with rstanarm by setting the `iter` variable when you run the model. For example, this runs a simple model using 20,000 simulations, rather than the default of 4000:

```{r, eval=F}
stan_glm(mpg~wt, data=mtcars, iter=20000)
```

In short: the default values are often fine, but if you are worried about increasing precision there are ways to achieve it.
