## Wider reading

If you feel anxious about returning to study after some time, or have simply forgotten all the statistics and research methods you learnt on your BSc, you might find the [teaching materials from the Plymouth University BSc course](https://ajwills72.github.io/rminr/) useful.

[Just Enough R](https://benwhalley.github.io/just-enough-r/) is a companion website to these materials. It is designed to offer a more concise guide to all of the topics dealt with in PSY556, PSY558, along with other material likely to be of use to MSc and PhD students in Psychology. It's probably best used _after_ you have worked through the relevant workshop sessions — although it can also be used for self study.

If you actually want to understand *how* regression works in more detail and have some maths background (e.g. A level) the Gelman and Hill book [*Data Analysis Using Regression and Multilevel/Hierarchical Models*](http://www.stat.columbia.edu/~gelman/arm/) is quite advanced, but offers clear explanations of the underlying concepts.

If you'd like more details on how to actually work with 'real' data... i.e. messy, unfamiliar datasets, then Roger Peng's [*Exploratory Data Analysis with R*](https://bookdown.org/rdpeng/exdata/) is nice. If you'd also like to improve your understanding of R and the tidyverse, then Hadley Wickham's [*R for Data Science*](http://r4ds.had.co.nz) gets into more of the nuts and bolts of dealing with data, plotting, modelling and and programming in (modern idiomatic) R.
There's also Wickham's [*Advanced R*](http://adv-r.had.co.nz) if you get really ambitious (although this isn't really a recommended text unless you have a specific problem to solve).

For a deep-dive (with lots of examples) on plotting and visualisation, see Claus O. Wilke,  [*Fundamentals of Data Visualization*](https://serialmentor.com/dataviz/proportional-ink.html#visualizations-along-linear-axes). The *principles* outlined in part 2 are especially useful, and draw on older texts like  [Cleveland 1993](https://dl.acm.org/citation.cfm?id=529269) and [Tufte 2001](https://www.edwardtufte.com/tufte/books_vdqi), bringing them up to date and providing R source code to reproduce the examples. Kieran Healy's [*Data  visualisation*](https://socviz.co) is also good on these topics, with longer explanatory text and more examples, if you prefer.
