## Teachers' notes

### Course features

#### Organization and staffing

The module comprises 17 workshop sessions. Students work individually or in
pairs within workshop classes of up to 80. For each session there will be a
specified teaching assistant (Ph.D student or TARA) supporting students.

Each session is broken in half, with more intensive exercises in the first
session, followed by supported-self study or followup activities (e.g. finding
literature, working on problems).

#### Resources

All sessions in 2019/20 will be run in the a computer lab. The course requires
one computer (PC, Mac, or Linux) per student, in all sessions. Any student with
a laptop should bring it.

For activities based around R, students will use the school RStudio server.
Accounts will be released in the [first session](#beginners).

There is a need for an online **lab book** system. Students can use the Blog
system within the DLE to keep a record of their activities and progress each
week.

#### Employability skills

Data handling and visualisation. Communication skills. Working to deadline.
Critical thinking / analysis.


## Week-by-week resources




### Session 6 (Regression as a fitted line)


Need:

- OHPs
- [printable rulers](rulers_metric_narrow.pdf)
- Sharpies
- Printed out [example-plots.pdf](regression-example-plots.pdf) (give several to each group to avoid swapping)


Timings:

- First hour is plotting task
- Second hour is the regression worksheet + prediction using augment


### Session 7 (Causes and effects)

Relates to: [second regression session including causal models](#regression-thinking-causes)


### Resources

Bring:
- Markers
- A3 paper
- Cancer plot
- Printouts of studies

### Timings

- Introduction... thinking about cause and effect before we dive deeper into techniques
- Explain DAG relationships (but not moderation)
- Students brainstorm one of the topics, then draw a diagram
- Followup questions about how strong relations are, evidence, is there mediation?

30 mins

- Explain effect modification
- Draw in gender and possible moderators
- Draw in other moderators if possible

45 mins

- Distribute cancer plot
- Students draw causal models from cancer plot
- Students add more confounding to their model

60 mins

- Point explaining why correlation would, ideally, be redrawn as directed lines
- Point relating causal to statistical models (t test, regression, multiple regression, mediation etc)
- Stats are just an implementation detail though (focus on your predictions)
- Make the point that inferences require the causal model to be correctly specified
- Representing non-linear effects using $\cup$ and $\cap$ as labels

- Introduce real examples exercise with study1/2.

75 mins


Students work independently.




### Session 8

- Begin by getting groups to share their models of the papers
- Confounding? Is it addressed in the discussion of the papers? Are the inferences safe?

20 mins
