<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Session 3 ANOVA: between-subjects designs | PSYC753 Data Fluency: Analysis</title>
  <meta name="description" content="Course materials for PSYC753 2022" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Session 3 ANOVA: between-subjects designs | PSYC753 Data Fluency: Analysis" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://chrisjberry.github.io/datafluencyCB/" />
  
  <meta property="og:description" content="Course materials for PSYC753 2022" />
  <meta name="github-repo" content="datafluencyCB" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Session 3 ANOVA: between-subjects designs | PSYC753 Data Fluency: Analysis" />
  
  <meta name="twitter:description" content="Course materials for PSYC753 2022" />
  

<meta name="author" content="Chris Berry" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multiple1.html"/>
<link rel="next" href="mutliple2.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />



<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="include/psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include/webex.css" type="text/css" />
<link rel="stylesheet" href="include/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PSYC753 Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="simple1.html"><a href="simple1.html"><i class="fa fa-check"></i><b>1</b> Simple Regression</a>
<ul>
<li class="chapter" data-level="1.1" data-path="simple1.html"><a href="simple1.html#overview-1"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="simple1.html"><a href="simple1.html#worked-example"><i class="fa fa-check"></i><b>1.2</b> Worked Example</a></li>
<li class="chapter" data-level="1.3" data-path="simple1.html"><a href="simple1.html#predicting"><i class="fa fa-check"></i><b>1.3</b> Predicting</a></li>
<li class="chapter" data-level="1.4" data-path="simple1.html"><a href="simple1.html#residuals"><i class="fa fa-check"></i><b>1.4</b> Residuals</a></li>
<li class="chapter" data-level="1.5" data-path="simple1.html"><a href="simple1.html#evaluating-the-model"><i class="fa fa-check"></i><b>1.5</b> Evaluating the model</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="simple1.html"><a href="simple1.html#r2"><i class="fa fa-check"></i><b>1.5.1</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="1.5.2" data-path="simple1.html"><a href="simple1.html#bayes-factor"><i class="fa fa-check"></i><b>1.5.2</b> Bayes Factor</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="simple1.html"><a href="simple1.html#exercise"><i class="fa fa-check"></i><b>1.6</b> Exercise</a></li>
<li class="chapter" data-level="1.7" data-path="simple1.html"><a href="simple1.html#further-exercises"><i class="fa fa-check"></i><b>1.7</b> Further Exercises</a></li>
<li class="chapter" data-level="1.8" data-path="simple1.html"><a href="simple1.html#summary"><i class="fa fa-check"></i><b>1.8</b> Summary</a></li>
<li class="chapter" data-level="1.9" data-path="simple1.html"><a href="simple1.html#references"><i class="fa fa-check"></i><b>1.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="multiple1.html"><a href="multiple1.html"><i class="fa fa-check"></i><b>2</b> Multiple regression: multiple continuous predictors</a>
<ul>
<li class="chapter" data-level="2.1" data-path="multiple1.html"><a href="multiple1.html#overview-2"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="multiple1.html"><a href="multiple1.html#worked-example-1"><i class="fa fa-check"></i><b>2.2</b> Worked example</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="multiple1.html"><a href="multiple1.html#residual-plot"><i class="fa fa-check"></i><b>2.2.1</b> Residual plot</a></li>
<li class="chapter" data-level="2.2.2" data-path="multiple1.html"><a href="multiple1.html#evaluating-the-model-bayes-factor"><i class="fa fa-check"></i><b>2.2.2</b> Evaluating the model: Bayes Factor</a></li>
<li class="chapter" data-level="2.2.3" data-path="multiple1.html"><a href="multiple1.html#evaluating-the-model-r2"><i class="fa fa-check"></i><b>2.2.3</b> Evaluating the model: R<sup>2</sup></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="multiple1.html"><a href="multiple1.html#understanding-the-contribution-of-individual-predictors"><i class="fa fa-check"></i><b>2.3</b> Understanding the contribution of individual predictors</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="multiple1.html"><a href="multiple1.html#r2-in-simple-vs.-multiple-regression"><i class="fa fa-check"></i><b>2.3.1</b> R<sup>2</sup> in simple vs. multiple regression</a></li>
<li class="chapter" data-level="2.3.2" data-path="multiple1.html"><a href="multiple1.html#venn-diagrams"><i class="fa fa-check"></i><b>2.3.2</b> Venn Diagrams</a></li>
<li class="chapter" data-level="2.3.3" data-path="multiple1.html"><a href="multiple1.html#using-bayes-factors-to-assess-the-unique-contribution-of-predictors"><i class="fa fa-check"></i><b>2.3.3</b> Using Bayes factors to assess the unique contribution of predictors</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="multiple1.html"><a href="multiple1.html#multicollinearity"><i class="fa fa-check"></i><b>2.4</b> Multicollinearity</a></li>
<li class="chapter" data-level="2.5" data-path="multiple1.html"><a href="multiple1.html#exercise-1"><i class="fa fa-check"></i><b>2.5</b> Exercise</a></li>
<li class="chapter" data-level="2.6" data-path="multiple1.html"><a href="multiple1.html#further-exercises-1"><i class="fa fa-check"></i><b>2.6</b> Further exercises</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="multiple1.html"><a href="multiple1.html#regressionbf"><i class="fa fa-check"></i><b>2.6.1</b> <code>regressionBF()</code></a></li>
<li class="chapter" data-level="2.6.2" data-path="multiple1.html"><a href="multiple1.html#predicting-new-data"><i class="fa fa-check"></i><b>2.6.2</b> Predicting new data</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="multiple1.html"><a href="multiple1.html#summary-of-key-points"><i class="fa fa-check"></i><b>2.7</b> Summary of key points</a></li>
<li class="chapter" data-level="2.8" data-path="multiple1.html"><a href="multiple1.html#references-1"><i class="fa fa-check"></i><b>2.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="anova1.html"><a href="anova1.html"><i class="fa fa-check"></i><b>3</b> ANOVA: between-subjects designs</a>
<ul>
<li class="chapter" data-level="3.1" data-path="anova1.html"><a href="anova1.html#overview-3"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="anova1.html"><a href="anova1.html#one-way-between-subjects-anova"><i class="fa fa-check"></i><b>3.2</b> One-way between subjects ANOVA</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="anova1.html"><a href="anova1.html#worked-example-2"><i class="fa fa-check"></i><b>3.2.1</b> Worked Example</a></li>
<li class="chapter" data-level="3.2.2" data-path="anova1.html"><a href="anova1.html#read-in-the-data"><i class="fa fa-check"></i><b>3.2.2</b> Read in the data</a></li>
<li class="chapter" data-level="3.2.3" data-path="anova1.html"><a href="anova1.html#convert-the-independent-variable-to-a-factor"><i class="fa fa-check"></i><b>3.2.3</b> Convert the independent variable to a factor</a></li>
<li class="chapter" data-level="3.2.4" data-path="anova1.html"><a href="anova1.html#n-of-each-group"><i class="fa fa-check"></i><b>3.2.4</b> n of each group</a></li>
<li class="chapter" data-level="3.2.5" data-path="anova1.html"><a href="anova1.html#visualise-the-data"><i class="fa fa-check"></i><b>3.2.5</b> Visualise the data</a></li>
<li class="chapter" data-level="3.2.6" data-path="anova1.html"><a href="anova1.html#plot-the-means"><i class="fa fa-check"></i><b>3.2.6</b> Plot the means</a></li>
<li class="chapter" data-level="3.2.7" data-path="anova1.html"><a href="anova1.html#descriptives-mean-of-each-group"><i class="fa fa-check"></i><b>3.2.7</b> Descriptives: Mean of each group</a></li>
<li class="chapter" data-level="3.2.8" data-path="anova1.html"><a href="anova1.html#bayes-factor-1"><i class="fa fa-check"></i><b>3.2.8</b> Bayes factor</a></li>
<li class="chapter" data-level="3.2.9" data-path="anova1.html"><a href="anova1.html#r2-1"><i class="fa fa-check"></i><b>3.2.9</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="3.2.10" data-path="anova1.html"><a href="anova1.html#follow-up-tests"><i class="fa fa-check"></i><b>3.2.10</b> Follow-up tests</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="anova1.html"><a href="anova1.html#two-way-between-subjects-anova"><i class="fa fa-check"></i><b>3.3</b> Two-way between-subjects ANOVA</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="anova1.html"><a href="anova1.html#worked-example-3"><i class="fa fa-check"></i><b>3.3.1</b> Worked example</a></li>
<li class="chapter" data-level="3.3.2" data-path="anova1.html"><a href="anova1.html#read-in-the-data-1"><i class="fa fa-check"></i><b>3.3.2</b> Read in the data</a></li>
<li class="chapter" data-level="3.3.3" data-path="anova1.html"><a href="anova1.html#convert-the-independent-variables-to-factors"><i class="fa fa-check"></i><b>3.3.3</b> Convert the independent variables to factors</a></li>
<li class="chapter" data-level="3.3.4" data-path="anova1.html"><a href="anova1.html#n-in-each-group"><i class="fa fa-check"></i><b>3.3.4</b> n in each group</a></li>
<li class="chapter" data-level="3.3.5" data-path="anova1.html"><a href="anova1.html#visualise-the-data-1"><i class="fa fa-check"></i><b>3.3.5</b> Visualise the data</a></li>
<li class="chapter" data-level="3.3.6" data-path="anova1.html"><a href="anova1.html#plot-the-means-1"><i class="fa fa-check"></i><b>3.3.6</b> Plot the means</a></li>
<li class="chapter" data-level="3.3.7" data-path="anova1.html"><a href="anova1.html#bayes-factors"><i class="fa fa-check"></i><b>3.3.7</b> Bayes factors</a></li>
<li class="chapter" data-level="3.3.8" data-path="anova1.html"><a href="anova1.html#r2-2"><i class="fa fa-check"></i><b>3.3.8</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="3.3.9" data-path="anova1.html"><a href="anova1.html#follow-up-comparisons"><i class="fa fa-check"></i><b>3.3.9</b> Follow-up comparisons</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="anova1.html"><a href="anova1.html#exercise-one-way"><i class="fa fa-check"></i><b>3.4</b> Exercise: one-way</a></li>
<li class="chapter" data-level="3.5" data-path="anova1.html"><a href="anova1.html#exercise-two-way"><i class="fa fa-check"></i><b>3.5</b> Exercise: two-way</a></li>
<li class="chapter" data-level="3.6" data-path="anova1.html"><a href="anova1.html#summary-1"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
<li class="chapter" data-level="3.7" data-path="anova1.html"><a href="anova1.html#references-2"><i class="fa fa-check"></i><b>3.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="mutliple2.html"><a href="mutliple2.html"><i class="fa fa-check"></i><b>4</b> Multiple regression: one continuous, one categorical</a>
<ul>
<li class="chapter" data-level="4.1" data-path="mutliple2.html"><a href="mutliple2.html#overview-4"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="mutliple2.html"><a href="mutliple2.html#worked-example-4"><i class="fa fa-check"></i><b>4.2</b> Worked example</a></li>
<li class="chapter" data-level="4.3" data-path="mutliple2.html"><a href="mutliple2.html#read-in-the-data-2"><i class="fa fa-check"></i><b>4.3</b> Read in the data</a></li>
<li class="chapter" data-level="4.4" data-path="mutliple2.html"><a href="mutliple2.html#visualise-the-data-2"><i class="fa fa-check"></i><b>4.4</b> Visualise the data</a></li>
<li class="chapter" data-level="4.5" data-path="mutliple2.html"><a href="mutliple2.html#evidence-for-the-interaction"><i class="fa fa-check"></i><b>4.5</b> Evidence for the interaction</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="mutliple2.html"><a href="mutliple2.html#model-without-the-interaction"><i class="fa fa-check"></i><b>4.5.1</b> Model without the interaction</a></li>
<li class="chapter" data-level="4.5.2" data-path="mutliple2.html"><a href="mutliple2.html#model-with-the-interaction"><i class="fa fa-check"></i><b>4.5.2</b> Model with the interaction</a></li>
<li class="chapter" data-level="4.5.3" data-path="mutliple2.html"><a href="mutliple2.html#compare-the-model-with-and-without-the-interaction"><i class="fa fa-check"></i><b>4.5.3</b> Compare the model with and without the interaction</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="mutliple2.html"><a href="mutliple2.html#simple-slopes-analysis"><i class="fa fa-check"></i><b>4.6</b> Simple slopes analysis</a></li>
<li class="chapter" data-level="4.7" data-path="mutliple2.html"><a href="mutliple2.html#exercises"><i class="fa fa-check"></i><b>4.7</b> Exercises</a></li>
<li class="chapter" data-level="4.8" data-path="mutliple2.html"><a href="mutliple2.html#further"><i class="fa fa-check"></i><b>4.8</b> Further</a></li>
<li class="chapter" data-level="4.9" data-path="mutliple2.html"><a href="mutliple2.html#further-knowledge-centring"><i class="fa fa-check"></i><b>4.9</b> Further knowledge: Centring</a></li>
<li class="chapter" data-level="4.10" data-path="mutliple2.html"><a href="mutliple2.html#further-knowledge-coefficients"><i class="fa fa-check"></i><b>4.10</b> Further knowledge: coefficients</a></li>
<li class="chapter" data-level="4.11" data-path="mutliple2.html"><a href="mutliple2.html#summary-2"><i class="fa fa-check"></i><b>4.11</b> Summary</a></li>
<li class="chapter" data-level="4.12" data-path="mutliple2.html"><a href="mutliple2.html#references-3"><i class="fa fa-check"></i><b>4.12</b> References</a></li>
<li class="chapter" data-level="4.13" data-path="mutliple2.html"><a href="mutliple2.html#cut"><i class="fa fa-check"></i><b>4.13</b> cut</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="multiple3.html"><a href="multiple3.html"><i class="fa fa-check"></i><b>5</b> Multiple regression: evaluating and comparing models</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="multiple3.html"><a href="multiple3.html#using-anova-and-bayes-factors-to-compare-models"><i class="fa fa-check"></i><b>5.0.1</b> Using ANOVA and Bayes Factors to compare models</a></li>
<li class="chapter" data-level="5.0.2" data-path="multiple3.html"><a href="multiple3.html#overview-5"><i class="fa fa-check"></i><b>5.0.2</b> Overview</a></li>
<li class="chapter" data-level="5.1" data-path="multiple3.html"><a href="multiple3.html#comparing-models-using-anova"><i class="fa fa-check"></i><b>5.1</b> Comparing models using ANOVA</a></li>
<li class="chapter" data-level="5.2" data-path="multiple3.html"><a href="multiple3.html#comparing-models-using-bayes-factors"><i class="fa fa-check"></i><b>5.2</b> Comparing models using Bayes Factors</a></li>
<li class="chapter" data-level="5.3" data-path="multiple3.html"><a href="multiple3.html#exercise-2"><i class="fa fa-check"></i><b>5.3</b> Exercise</a></li>
<li class="chapter" data-level="5.4" data-path="multiple3.html"><a href="multiple3.html#summary-of-key-points-1"><i class="fa fa-check"></i><b>5.4</b> Summary of key points</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="anova2.html"><a href="anova2.html"><i class="fa fa-check"></i><b>6</b> ANOVA: Repeated measures</a></li>
<li class="chapter" data-level="7" data-path="prepost.html"><a href="prepost.html"><i class="fa fa-check"></i><b>7</b> Pre-post data, effect sizes, clinically significant change</a></li>
<li class="chapter" data-level="8" data-path="assessment2022.html"><a href="assessment2022.html"><i class="fa fa-check"></i><b>8</b> Data Analysis Assessment 2022</a></li>
<li class="chapter" data-level="9" data-path="faqs.html"><a href="faqs.html"><i class="fa fa-check"></i><b>9</b> FAQs</a>
<ul>
<li class="chapter" data-level="9.1" data-path="faqs.html"><a href="faqs.html#e-meaning"><i class="fa fa-check"></i><b>9.1</b> What does it mean if RStudio prints out "e-" next to a number?</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSYC753 Data Fluency: Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anova1" class="section level1" number="3">
<h1><span class="header-section-number">Session 3</span> ANOVA: between-subjects designs</h1>
<p><em>Chris Berry</em><br />
<em>2022</em></p>
<!--
commented text
commented text
-->
<style>
div.exercise { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<style>
div.tip { background-color:#D5F5E3; border-radius: 5px; padding: 20px;}
</style>
<div id="overview-3" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Overview</h2>
<ul>
<li><strong>Slides</strong> from the lecture part of the session: <a href="slides/PSYC753_L3_ANOVA_1.pptx">Download</a></li>
</ul>
<p><br />
</p>
<p>So far we have used regression where both the outcome and predictor are <em>continuous variables</em>.</p>
<p>When all the <em>predictor variables</em> in a regression are categorical, the analysis is called <strong>ANOVA</strong>, which stands for Analysis Of VAriance. Here we consider two types of ANOVA for between-subjects designs: one-way ANOVA and two-way ANOVA. We will consider other types in future sessions (e.g., for within-subjects/repeated measures designs).</p>
</div>
<div id="one-way-between-subjects-anova" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> One-way between subjects ANOVA</h2>
<div class="tip">
<p><strong>A one-way between subjects ANOVA</strong> is used to compare the scores from a dependent variable across different groups of individuals. For example, do <strong>mood</strong> scores differ between three groups of individuals, where each group undergoes a different type of therapy as treatment?</p>
</div>
<p><br />
</p>
<ul>
<li><strong>one-way</strong> means that there is one independent variable, for example, <em>type of therapy</em>.</li>
<li>Independent variables are also called <strong>factors</strong> in ANOVA.</li>
<li>A factor is made up of different <strong>levels</strong>. <em>Type of therapy</em> could have three levels: CBT (Cognitive Behavioural Therapy), EMDR (Eye Movement Desensitisation and Reprocessing), and Control.</li>
<li><strong>between subjects</strong> means that a different group of participants gives us mood scores for each level of the independent variable. For example, if type of therapy is manipulated between-subjects, one group receives CBT, another group receives EMDR, and another group are the control group. Each participant provides exactly one score.</li>
</ul>
<div id="worked-example-2" class="section level3" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Worked Example</h3>
<p>What is the effect of viewing pictures of different aesthetic value on a person's mood? To investigate, Meidenbauer et al. (2020) showed three groups of participants pictures of urban environments that were either very low in aesthetic value (<em>n</em> = 102), low in aesthetic value (<em>n</em> = 100), or high (<em>n</em> = 104). Participants' change in State Trait Anxiety Inventory (STAI: a measure of negative symptoms such as upset, tense, worried) as a result of viewing the pictures was measured.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-1" class="exercise"><strong>Exercise 3.1  </strong></span>Design check.</p>
<ul>
<li><p>What is the independent variable (or <em>factor</em>) in this design? <select class='webex-select'><option value='blank'></option><option value=''>change in STAI score</option><option value='answer'>aesthetic appeal of the pictures</option></select></p></li>
<li><p>How many levels does the factor have? <select class='webex-select'><option value='blank'></option><option value=''>1</option><option value=''>2</option><option value='answer'>3</option><option value=''>4</option></select></p></li>
<li><p>What is the dependent variable? <select class='webex-select'><option value='blank'></option><option value=''>VeryLow, Low, High</option><option value='answer'>change in STAI score</option><option value=''>aesthetic appeal of images</option></select></p></li>
<li><p>What is the nature of the independent variable? <select class='webex-select'><option value='blank'></option><option value='answer'>categorical</option><option value=''>continuous</option></select></p></li>
<li><p>Is the independent variable manipulated within- or between-subjects?
<select class='webex-select'><option value='blank'></option><option value='answer'>between-subjects</option><option value=''>within-subjects</option></select></p></li>
</ul>
</div>
<p><br />
</p>
</div>
<div id="read-in-the-data" class="section level3" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Read in the data</h3>
<p>Read in the data at the link below and store in <code>affect_data</code>. Preview the data using <code>head()</code>.</p>
<p><a href="https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_affect.csv" class="uri">https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_affect.csv</a></p>
<p>(Note. The data in are taken from the Urban condition of Meidenbauer et al. (2020, Experiment 1). The data are publicly available through the links in their article. The variable names have been changed here for clarity.)</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="anova1.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the data</span></span>
<span id="cb1-2"><a href="anova1.html#cb1-2" aria-hidden="true" tabindex="-1"></a>affect_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_affect.csv&#39;</span>)</span>
<span id="cb1-3"><a href="anova1.html#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="anova1.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the first 6 rows</span></span>
<span id="cb1-5"><a href="anova1.html#cb1-5" aria-hidden="true" tabindex="-1"></a>affect_data <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<p>Key variables of interest in <code>affect_data</code>:</p>
<ul>
<li><code>group</code>: the aesthetic value group, with levels <code>VeryLow</code>, <code>Low</code> and <code>High</code></li>
<li><code>score</code>: the change in STAI score. Higher scores indicate <em>fewer</em> negative symptoms after viewing the images (i.e., <em>improvement</em> in mood).</li>
</ul>
<div class="webex-solution">
<button>
Variable labels
</button>
<p>Notice that the <code>group</code> column is by default read into R as a <em>character variable</em> (that's what the label <code>&lt;chr&gt;</code> means in the output). This is because the levels of <code>group</code> have been recorded in the dataset as words e.g., "VeryLow".</p>
</div>
<p><br />
</p>
</div>
<div id="convert-the-independent-variable-to-a-factor" class="section level3" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Convert the independent variable to a factor</h3>
<p>To enable us to use the <code>group</code> column in an ANOVA, we need to tell R that <code>group</code> is a <em>factor</em>. Use <code>mutate()</code> and <code>factor()</code> to convert <code>group</code> to a factor.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="anova1.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use mutate() to convert the group variable to a factor</span></span>
<span id="cb2-2"><a href="anova1.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># store the changes back in affect_data </span></span>
<span id="cb2-3"><a href="anova1.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (i.e., overwrite what&#39;s already in affect_data)</span></span>
<span id="cb2-4"><a href="anova1.html#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="anova1.html#cb2-5" aria-hidden="true" tabindex="-1"></a>affect_data <span class="ot">&lt;-</span></span>
<span id="cb2-6"><a href="anova1.html#cb2-6" aria-hidden="true" tabindex="-1"></a>  affect_data <span class="sc">%&gt;%</span> </span>
<span id="cb2-7"><a href="anova1.html#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group =</span> <span class="fu">factor</span>(group))</span></code></pre></div>
<div class="webex-solution">
<button>
Remember
</button>
<p><code>mutate()</code> can be used to change variables or create new ones.</p>
<p><br />
</p>
<p>The code <code>mutate(group = factor(group))</code> means:</p>
<ul>
<li><code>group =</code>: create a variable called <code>group</code>. Because <code>group</code> already exists in <code>affect_data</code> it will be overwritten.</li>
<li><code>factor(group)</code>: convert the <code>group</code> variable to a factor.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Tip
</button>
<p>If we'd have used:</p>
<p><code>factor(group, levels = c("VeryLow","Low","High"))</code></p>
<p>instead of</p>
<p><code>factor(group)</code></p>
<p>this would mean that the levels of <code>group</code> will additionally be <em>ordered</em> according to the order in <code>levels</code>.</p>
<p>This can be useful when plotting the data.</p>
</div>
<div class="webex-solution">
<button>
Check
</button>
<p>Check that the variable label for <code>group</code> has now changed from <code>&lt;chr&gt;</code> to <code>&lt;fct&gt;</code> (i.e., a factor) by looking at the dataset again.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="anova1.html#cb3-1" aria-hidden="true" tabindex="-1"></a>affect_data</span></code></pre></div>
</div>
<p><br />
</p>
</div>
<div id="n-of-each-group" class="section level3" number="3.2.4">
<h3><span class="header-section-number">3.2.4</span> n of each group</h3>
<p>Use <code>group_by()</code> and <code>count()</code> to obtain the number of participants in each group:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="anova1.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use group_by() to group the output by &#39;group&#39; column, </span></span>
<span id="cb4-2"><a href="anova1.html#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># then obtain number of rows in each group with count()</span></span>
<span id="cb4-3"><a href="anova1.html#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="anova1.html#cb4-4" aria-hidden="true" tabindex="-1"></a>affect_data <span class="sc">%&gt;%</span> </span>
<span id="cb4-5"><a href="anova1.html#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb4-6"><a href="anova1.html#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div>
<ul>
<li>How many participants were there in the <code>VeryLow</code> aesthetic value group? <input class='webex-solveme nospaces' size='3' data-answer='["102"]'/></li>
<li>How many participants were there in the <code>Low</code> aesthetic value group? <input class='webex-solveme nospaces' size='3' data-answer='["100"]'/></li>
<li>How many participants were there in the <code>High</code> aesthetic value group? <input class='webex-solveme nospaces' size='3' data-answer='["104"]'/></li>
</ul>
<p><br />
</p>
</div>
<div id="visualise-the-data" class="section level3" number="3.2.5">
<h3><span class="header-section-number">3.2.5</span> Visualise the data</h3>
<p>The way the data are distributed in each group can be inspected with histograms or density plots:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="anova1.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of scores in each group </span></span>
<span id="cb5-2"><a href="anova1.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Use facet_wrap(~group) to create a separate</span></span>
<span id="cb5-3"><a href="anova1.html#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># panel for each group</span></span>
<span id="cb5-4"><a href="anova1.html#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="anova1.html#cb5-5" aria-hidden="true" tabindex="-1"></a>affect_data <span class="sc">%&gt;%</span> </span>
<span id="cb5-6"><a href="anova1.html#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(score)) <span class="sc">+</span></span>
<span id="cb5-7"><a href="anova1.html#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb5-8"><a href="anova1.html#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>group)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-6"></span>
<img src="03_anova_between_subjects_files/figure-html/unnamed-chunk-6-1.png" alt="Histogram of scores in each aesthetic value group" width="75%" />
<p class="caption">
Figure 3.1: Histogram of scores in each aesthetic value group
</p>
</div>
<div class="webex-solution">
<button>
Tip
</button>
<p>To produce density plots, swap <code>geom_histogram()</code> with <code>geom_density()</code>.</p>
</div>
<div class="webex-solution">
<button>
Comments on the histograms
</button>
<p>The spread of scores in each group appears relatively similar, suggesting the assumption of homogeneity of variance in ANOVA, may be met. The distributions are reasonably symmetrical, and, aside from the very high number of 0 scores in each group (indicative of zero change in STAI score in a large number of individuals), the data appear approximately normally distributed. In practice, ANOVA is considered reasonably robust against violations of the test's assumptions (see e.g., Glass et al. 1972, Schmider et al., 2010).</p>
</div>
<p><br />
</p>
</div>
<div id="plot-the-means" class="section level3" number="3.2.6">
<h3><span class="header-section-number">3.2.6</span> Plot the means</h3>
<p>Visualise the data further by obtaining a plot of the mean score in each group.</p>
<p>The package <code>ggpubr</code> can produce high quality plots with ease. Using <code>ggerrorplot()</code> in <code>ggpubr</code>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="anova1.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the ggpubr package</span></span>
<span id="cb6-2"><a href="anova1.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb6-3"><a href="anova1.html#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="anova1.html#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the mean of each group </span></span>
<span id="cb6-5"><a href="anova1.html#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># specify desc_stat = &quot;mean_se&quot; to </span></span>
<span id="cb6-6"><a href="anova1.html#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># add error bars representing the standard error </span></span>
<span id="cb6-7"><a href="anova1.html#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="anova1.html#cb6-8" aria-hidden="true" tabindex="-1"></a>affect_data <span class="sc">%&gt;%</span> </span>
<span id="cb6-9"><a href="anova1.html#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggerrorplot</span>(<span class="at">x =</span> <span class="st">&quot;group&quot;</span> , <span class="at">y =</span> <span class="st">&quot;score&quot;</span>, <span class="at">desc_stat =</span> <span class="st">&quot;mean_se&quot;</span>) <span class="sc">+</span></span>
<span id="cb6-10"><a href="anova1.html#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Aesthetic value group&quot;</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-7"></span>
<img src="03_anova_between_subjects_files/figure-html/unnamed-chunk-7-1.png" alt="Mean change in STAI score across aesthetic value groups (error bars indicate SE)" width="75%" />
<p class="caption">
Figure 3.2: Mean change in STAI score across aesthetic value groups (error bars indicate SE)
</p>
</div>
<p><br />
</p>
<p>From inspection of the means:</p>
<ul>
<li>Which aesthetic value group has the greatest improvement in STAI score? <select class='webex-select'><option value='blank'></option><option value='answer'>High</option><option value=''>Low</option><option value=''>VeryLow</option></select></li>
<li>Which aesthetic value group has the lowest improvement in STAI score? <select class='webex-select'><option value='blank'></option><option value=''>High</option><option value=''>Low</option><option value='answer'>VeryLow</option></select></li>
<li>Did STAI scores appear to worsen (i.e., be below zero) in any group as a result of viewing the images? <select class='webex-select'><option value='blank'></option><option value=''>High group</option><option value=''>Low group</option><option value='answer'>VeryLow group</option></select></li>
</ul>
<div class="webex-solution">
<button>
Developing the plot
</button>
<p>As with plots generated in <code>ggplot()</code>, the figure can be enhanced by adding further code, e.g., try adding the line:</p>
<p><code>+ ylab("Change in STAI (negative symptoms)")</code></p>
<p><br />
</p>
<p>Beneath the surface, <code>ggpubr</code> uses <code>ggplot()</code> to make graphs.</p>
<p><br />
</p>
<p>Other types of plot are available in <code>ggpubr</code>, see e.g.:</p>
<ul>
<li>Errorplots: <code>?ggerrorplot()</code></li>
<li>Boxplots: <code>?ggboxplot()</code></li>
<li>Violin plots: <code>?ggviolin()</code></li>
</ul>
<p>I encourage you to play around to find clear and effective ways to visualise your data!</p>
<p>To see more types of plot: <code>help(package = ggpubr)</code></p>
</div>
<p><br />
</p>
</div>
<div id="descriptives-mean-of-each-group" class="section level3" number="3.2.7">
<h3><span class="header-section-number">3.2.7</span> Descriptives: Mean of each group</h3>
<p>Use <code>summarise()</code> and <code>group_by()</code> to obtain the mean (<em>M</em>) in each group:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="anova1.html#cb7-1" aria-hidden="true" tabindex="-1"></a>affect_data <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="anova1.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="anova1.html#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">M =</span> <span class="fu">mean</span>(score))</span></code></pre></div>
<ul>
<li>The mean score in the <code>High</code> group is (to 2 decimal places) <input class='webex-solveme nospaces' size='4' data-answer='["0.11"]'/></li>
<li>The mean score in the <code>Low</code> group is (to 2 decimal places) <input class='webex-solveme nospaces' size='4' data-answer='["0.08"]'/></li>
<li>The mean score in the <code>VeryLow</code> group is (to 2 decimal places) <input class='webex-solveme nospaces' size='5' data-answer='["-0.14"]'/></li>
</ul>
<div class="webex-solution">
<button>
Tip - Standard Error
</button>
<p>The formula for the standard error of the mean is <span class="math inline">\(SD / \sqrt{n}\)</span>. We can therefore obtain the standard error of the mean for each group as follows:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="anova1.html#cb8-1" aria-hidden="true" tabindex="-1"></a>affect_data <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="anova1.html#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="anova1.html#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">SE =</span> <span class="fu">sd</span>(score) <span class="sc">/</span> <span class="fu">sqrt</span>( <span class="fu">n</span>() ))</span></code></pre></div>
<p>To show the mean and SE in the same output:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="anova1.html#cb9-1" aria-hidden="true" tabindex="-1"></a>affect_data <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="anova1.html#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="anova1.html#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="at">M =</span> <span class="fu">mean</span>(score), </span>
<span id="cb9-4"><a href="anova1.html#cb9-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">SE =</span> <span class="fu">sd</span>(score) <span class="sc">/</span> <span class="fu">sqrt</span>( <span class="fu">n</span>() ) )</span></code></pre></div>
</div>
<p><br />
</p>
</div>
<div id="bayes-factor-1" class="section level3" number="3.2.8">
<h3><span class="header-section-number">3.2.8</span> Bayes factor</h3>
<div class="tip">
<p>A Bayes factor can be obtained for the one-way ANOVA model using <code>anovaBF()</code>. The model we specify is of <code>score</code> on the basis of <code>group</code> (i.e., <code>score ~ group</code>). The BF will tell us how much more likely the model (with different three groups) is than an intercept-only model, in which all the scores are treated as coming from one large group. In other words, the BF will tell us whether we have evidence for an effect of aesthetic appeal on the STAI scores or not.</p>
</div>
<p><br />
</p>
<p>To obtain the BF for the one-way ANOVA model, use <code>anovaBF()</code>:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="anova1.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ensure BayesFactor package is loaded</span></span>
<span id="cb10-2"><a href="anova1.html#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(BayesFactor)</span></span>
<span id="cb10-3"><a href="anova1.html#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="anova1.html#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain the BF for the ANOVA model with lmBF()</span></span>
<span id="cb10-5"><a href="anova1.html#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>( score <span class="sc">~</span> group, <span class="at">data =</span> <span class="fu">data.frame</span>(affect_data) )</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] group : 66.65842 ±0.04%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The Bayes Factor for the model is equal to BF = <input class='webex-solveme nospaces' size='5' data-answer='["66.66"]'/>. This indicates that the model is over <select class='webex-select'><option value='blank'></option><option value=''>six</option><option value='answer'>sixty</option><option value=''>six hundred</option></select> times more likely than an intercept-only model. There is therefore substantial evidence for an effect of the aesthetic value of urban images on changes in STAI scores.</p>
<div class="webex-solution">
<button>
Tip - lmBF()
</button>
<p><code>lmBF()</code> in the <code>BayesFactor</code> package can be used in place of <code>lmBF()</code> to produce exactly the same result:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="anova1.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lmBF</span>( score <span class="sc">~</span> group, <span class="at">data =</span> <span class="fu">data.frame</span>(affect_data) )</span></code></pre></div>
<p>Remember, this works because ANOVA is a special case of regression.</p>
</div>
<p><br />
</p>
</div>
<div id="r2-1" class="section level3" number="3.2.9">
<h3><span class="header-section-number">3.2.9</span> R<sup>2</sup></h3>
<div class="tip">
<p>R<sup>2</sup> can be reported for ANOVA models as a measure of <em>effect size</em>. As with simple and multiple regression, R<sup>2</sup> represents the proportion of variance explained by the model, where our model is that the scores come from distinct groups of individuals (three groups in our example) with different means.</p>
</div>
<p><br />
</p>
<p>To obtain R<sup>2</sup>, first use <code>lm()</code> to specify the model, then use <code>glance()</code> from the <code>broom</code> package:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="anova1.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specify and store the anova</span></span>
<span id="cb13-2"><a href="anova1.html#cb13-2" aria-hidden="true" tabindex="-1"></a>anova_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> group, <span class="at">data =</span> affect_data)</span>
<span id="cb13-3"><a href="anova1.html#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="anova1.html#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># make sure broom package is loaded, then</span></span>
<span id="cb13-5"><a href="anova1.html#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># use glance() with anova_1 </span></span>
<span id="cb13-6"><a href="anova1.html#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(anova_1)</span></code></pre></div>
<div class="kable-table">
<table>
<colgroup>
<col width="9%" />
<col width="12%" />
<col width="6%" />
<col width="9%" />
<col width="9%" />
<col width="2%" />
<col width="9%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="11%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.0523547</td>
<td align="right">0.0460996</td>
<td align="right">0.4743</td>
<td align="right">8.369943</td>
<td align="right">0.0002896</td>
<td align="right">2</td>
<td align="right">-204.4377</td>
<td align="right">416.8754</td>
<td align="right">431.7697</td>
<td align="right">68.16302</td>
<td align="right">303</td>
<td align="right">306</td>
</tr>
</tbody>
</table>
</div>
<p>Adjusted R<sup>2</sup> (as a <em>percentage</em>, to two decimal places) = <input class='webex-solveme nospaces' size='4' data-answer='["4.61"]'/> %, which represents the percentage of the variance in the change in STAI scores is explained by the affect value of an image. (_Remember, the values given by <code>glance()</code> are <em>proportions</em>, so need to be multiplied by 100 to get the percentage.)</p>
<p><br />
</p>
</div>
<div id="follow-up-tests" class="section level3" number="3.2.10">
<h3><span class="header-section-number">3.2.10</span> Follow-up tests</h3>
<p>The Bayes factor (66.66) tells us that there's evidence that the means of the three groups differ from one another, but not which groups differ from which.</p>
<p>With three groups, there are three possible pairwise comparisons that can be made:</p>
<ul>
<li><code>VeryLow</code> vs. <code>Low</code></li>
<li><code>VeryLow</code> vs. <code>High</code></li>
<li><code>Low</code> vs. <code>High</code></li>
</ul>
<p>To compare scores from two groups, we can use <code>filter()</code> to filter the <code>affect_data</code> so that it contains only the two groups we want to compare. Then use <code>anovaBF()</code> again to compare the scores across groups. The BF will tell us how many times more likely it is that there's a difference between means, compared to no difference.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="anova1.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare scores of VeryLow vs. Low groups</span></span>
<span id="cb14-2"><a href="anova1.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb14-3"><a href="anova1.html#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1. Filter affect_data for VeryLow and Low groups only</span></span>
<span id="cb14-4"><a href="anova1.html#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Store in &#39;groups_VeryLow_Low&#39;</span></span>
<span id="cb14-5"><a href="anova1.html#cb14-5" aria-hidden="true" tabindex="-1"></a>groups_VeryLow_Low <span class="ot">&lt;-</span> </span>
<span id="cb14-6"><a href="anova1.html#cb14-6" aria-hidden="true" tabindex="-1"></a>  affect_data <span class="sc">%&gt;%</span> </span>
<span id="cb14-7"><a href="anova1.html#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">&quot;VeryLow&quot;</span> <span class="sc">|</span> group <span class="sc">==</span> <span class="st">&quot;Low&quot;</span>)</span>
<span id="cb14-8"><a href="anova1.html#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb14-9"><a href="anova1.html#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2. Obtain BF for VeryLow vs. Low groups</span></span>
<span id="cb14-10"><a href="anova1.html#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>(score <span class="sc">~</span> group, <span class="at">data =</span> <span class="fu">data.frame</span>(groups_VeryLow_Low))</span>
<span id="cb14-11"><a href="anova1.html#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="anova1.html#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="anova1.html#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare scores of VeryLow vs. High groups</span></span>
<span id="cb14-14"><a href="anova1.html#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb14-15"><a href="anova1.html#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1. Filter affect_data for VeryLow and High groups only</span></span>
<span id="cb14-16"><a href="anova1.html#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Store in &#39;groups_VeryLow_High&#39;</span></span>
<span id="cb14-17"><a href="anova1.html#cb14-17" aria-hidden="true" tabindex="-1"></a>groups_VeryLow_High <span class="ot">&lt;-</span> </span>
<span id="cb14-18"><a href="anova1.html#cb14-18" aria-hidden="true" tabindex="-1"></a>  affect_data <span class="sc">%&gt;%</span> </span>
<span id="cb14-19"><a href="anova1.html#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">&quot;VeryLow&quot;</span> <span class="sc">|</span> group <span class="sc">==</span> <span class="st">&quot;High&quot;</span>)</span>
<span id="cb14-20"><a href="anova1.html#cb14-20" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb14-21"><a href="anova1.html#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2. Obtain BF for VeryLow vs. Low groups</span></span>
<span id="cb14-22"><a href="anova1.html#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>(score <span class="sc">~</span> group, <span class="at">data =</span> <span class="fu">data.frame</span>(groups_VeryLow_High))</span>
<span id="cb14-23"><a href="anova1.html#cb14-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-24"><a href="anova1.html#cb14-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-25"><a href="anova1.html#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare scores of Low vs. High groups</span></span>
<span id="cb14-26"><a href="anova1.html#cb14-26" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb14-27"><a href="anova1.html#cb14-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1. Filter affect_data to store Low and High groups only</span></span>
<span id="cb14-28"><a href="anova1.html#cb14-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Store in &#39;groups_Low_High&#39;</span></span>
<span id="cb14-29"><a href="anova1.html#cb14-29" aria-hidden="true" tabindex="-1"></a>groups_Low_High <span class="ot">&lt;-</span> </span>
<span id="cb14-30"><a href="anova1.html#cb14-30" aria-hidden="true" tabindex="-1"></a>  affect_data <span class="sc">%&gt;%</span> </span>
<span id="cb14-31"><a href="anova1.html#cb14-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">&quot;Low&quot;</span> <span class="sc">|</span> group <span class="sc">==</span> <span class="st">&quot;High&quot;</span>)</span>
<span id="cb14-32"><a href="anova1.html#cb14-32" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb14-33"><a href="anova1.html#cb14-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2. Obtain BF for VeryLow vs. Low groups</span></span>
<span id="cb14-34"><a href="anova1.html#cb14-34" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>(score <span class="sc">~</span> group, <span class="at">data =</span> <span class="fu">data.frame</span>(groups_Low_High))</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] group : 10.25237 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS
## 
## Bayes factor analysis
## --------------
## [1] group : 55.43484 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS
## 
## Bayes factor analysis
## --------------
## [1] group : 0.1774611 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>To two decimal places:</p>
<ul>
<li>The BF for the comparison of <code>VeryLow</code> vs. <code>Low</code> groups = <input class='webex-solveme nospaces' size='5' data-answer='["10.25"]'/></li>
<li>The BF for the comparison of <code>VeryLow</code> vs. <code>High</code> groups = <input class='webex-solveme nospaces' size='5' data-answer='["55.43"]'/></li>
<li>The BF for the comparison of <code>Low</code> vs. <code>High</code> groups = <input class='webex-solveme nospaces' size='4' data-answer='["0.18"]'/></li>
</ul>
<p><strong>Interpretation:</strong> The one-way between subjects ANOVA indicated that there was evidence for an effect of aesthetic value on change in STAI scores (BF = 66.66). The scores in the <code>VeryLow</code> group were lower than those of the <code>Low</code> (BF = 10.25) and <code>High</code> groups (BF = 55.43), but scores in the <code>Low</code> and <code>High</code> groups did not differ (BF = 0.18). This indicates that STAI scores were lower (i.e., there were more negative symptoms) after viewing images that were very low in aesthetic value, compared to images that were low or high in aesthetic value. Viewing pictures that were low or high in aesthetic value resulted in similar changes in STAI scores.</p>
<div class="webex-solution">
<button>
Further information on filter()
</button>
<ul>
<li>The <code>|</code> symbol means "or".</li>
<li>The <code>==</code> symbol (an equals sign typed twice) means "is equal to"</li>
</ul>
<p>So <code>filter(group == "VeryLow" | group == "Low")</code> means "filter the rows of <code>affect_data</code> when the labels in <code>group</code> are equal to <code>VeryLow</code> OR the labels in <code>group</code> are equal to <code>Low</code></p>
</div>
<div class="webex-solution">
<button>
An equivalent approach: ttestBF()
</button>
<p><code>anovaBF()</code> was used to conduct follow-up tests. Because each test had two groups, this is equivalent to a Bayesian <em>t</em>-test, and so the exact same BFs could have been obtained using <code>ttestBF()</code>:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="anova1.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare scores of VeryLow vs. Low groups</span></span>
<span id="cb16-2"><a href="anova1.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestBF</span>( <span class="at">x =</span> affect_data<span class="sc">$</span>score[ affect_data<span class="sc">$</span>group<span class="sc">==</span><span class="st">&quot;VeryLow&quot;</span> ], </span>
<span id="cb16-3"><a href="anova1.html#cb16-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> affect_data<span class="sc">$</span>score[ affect_data<span class="sc">$</span>group<span class="sc">==</span><span class="st">&quot;Low&quot;</span> ] )</span>
<span id="cb16-4"><a href="anova1.html#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="anova1.html#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># compare scores of VeryLow vs. High groups</span></span>
<span id="cb16-6"><a href="anova1.html#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestBF</span>( <span class="at">x =</span> affect_data<span class="sc">$</span>score[ affect_data<span class="sc">$</span>group<span class="sc">==</span><span class="st">&quot;VeryLow&quot;</span> ], </span>
<span id="cb16-7"><a href="anova1.html#cb16-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> affect_data<span class="sc">$</span>score[ affect_data<span class="sc">$</span>group<span class="sc">==</span><span class="st">&quot;High&quot;</span> ] )</span>
<span id="cb16-8"><a href="anova1.html#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="anova1.html#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># compare scores of Low vs. High groups</span></span>
<span id="cb16-10"><a href="anova1.html#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestBF</span>( <span class="at">x =</span> affect_data<span class="sc">$</span>score[ affect_data<span class="sc">$</span>group<span class="sc">==</span><span class="st">&quot;Low&quot;</span> ], </span>
<span id="cb16-11"><a href="anova1.html#cb16-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> affect_data<span class="sc">$</span>score[ affect_data<span class="sc">$</span>group<span class="sc">==</span><span class="st">&quot;High&quot;</span> ] )</span></code></pre></div>
</div>
<p><br />
</p>
</div>
</div>
<div id="two-way-between-subjects-anova" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Two-way between-subjects ANOVA</h2>
<div class="tip">
<p>In a <strong>two-way ANOVA</strong>, there are <em>two</em> categorical independent variables or factors.</p>
<p>When there are multiple factors, the ANOVA is referred to as <em>factorial</em> ANOVA.</p>
<p>For example, if the design has two factors, and each factor has two levels, then we refer to the design as a 2 x 2 factorial design. The first number (2) denotes the number of levels of the first factor. The second number (2) denotes the number of levels of the second factor. If, instead, the second factor had three levels, we'd say we have a 2 x 3 factorial design.</p>
</div>
<div id="worked-example-3" class="section level3" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Worked example</h3>
<p>What is the role of resilience in the distress experienced from childhood adversities? Beutel et al. (2017) analysed the distress scores from 2,437 individuals who were either low or high in trait resilience and had experienced either low or high levels of childhood adversity.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-2" class="exercise"><strong>Exercise 3.2  </strong></span>Design check.</p>
<ul>
<li><p>What is the first independent variable (or <em>factor</em>) that is mentioned in this design? <select class='webex-select'><option value='blank'></option><option value=''>distress score</option><option value=''>childhood adversity</option><option value='answer'>trait resilience</option></select></p></li>
<li><p>How many levels does the first factor have? <select class='webex-select'><option value='blank'></option><option value=''>1</option><option value='answer'>2</option><option value=''>3</option><option value=''>4</option></select></p></li>
<li><p>What is the second independent variable (or <em>factor</em>)? <select class='webex-select'><option value='blank'></option><option value=''>distress score</option><option value='answer'>childhood adversity</option><option value=''>trait resilience</option></select></p></li>
<li><p>How many levels does the second factor have? <select class='webex-select'><option value='blank'></option><option value=''>1</option><option value='answer'>2</option><option value=''>3</option><option value=''>4</option></select></p></li>
<li><p>What is the dependent variable? <select class='webex-select'><option value='blank'></option><option value='answer'>distress score</option><option value=''>childhood adversity</option><option value=''>trait resilience</option></select></p></li>
<li><p>What is the nature of the independent variables? <select class='webex-select'><option value='blank'></option><option value='answer'>categorical</option><option value=''>continuous</option></select></p></li>
<li><p>What type of design is this? <select class='webex-select'><option value='blank'></option><option value=''>2 x 2 x 2 between subjects factorial design</option><option value=''>2 x 3 between subjects factorial design</option><option value='answer'>2 x 2 between subjects factorial design</option><option value=''>correlational design</option></select></p></li>
</ul>
</div>
</div>
<div id="read-in-the-data-1" class="section level3" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Read in the data</h3>
<p>Read in the data at the link below and store in <code>resilience_data</code>:</p>
<p><a href="https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_resilience_data.csv" class="uri">https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_resilience_data.csv</a></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="anova1.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in the data</span></span>
<span id="cb17-2"><a href="anova1.html#cb17-2" aria-hidden="true" tabindex="-1"></a>resilience_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_resilience_data.csv&#39;</span>)</span>
<span id="cb17-3"><a href="anova1.html#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="anova1.html#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># preview</span></span>
<span id="cb17-5"><a href="anova1.html#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(resilience_data)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">distress</th>
<th align="left">resilience</th>
<th align="left">adversity</th>
<th align="right">sex</th>
<th align="right">partnership</th>
<th align="right">education</th>
<th align="right">income</th>
<th align="right">unemployed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="left">high</td>
<td align="left">low</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">low</td>
<td align="left">low</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">0</td>
<td align="left">high</td>
<td align="left">low</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="left">high</td>
<td align="left">low</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="left">low</td>
<td align="left">low</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="left">high</td>
<td align="left">low</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><code>distress</code> contains the distress scores. Higher scores indicate greater levels of distress.</li>
<li><code>resilience</code> labels the levels of childhood adversity ( <em>low</em> or <em>high</em>)</li>
<li><code>adversity</code> labels the levels of trait resilience ( <em>low</em> or <em>high</em>)</li>
</ul>
<p>(Note. The data are publicly available, but I have changed some of the variable names for clarity.)</p>
<p><br />
</p>
</div>
<div id="convert-the-independent-variables-to-factors" class="section level3" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Convert the independent variables to factors</h3>
<p>To enable the factors to be used as such in ANOVA, we need to convert them to factors using <code>factor()</code>:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="anova1.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use mutate() and factor() to convert </span></span>
<span id="cb18-2"><a href="anova1.html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># resilience and adversity to factors</span></span>
<span id="cb18-3"><a href="anova1.html#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="anova1.html#cb18-4" aria-hidden="true" tabindex="-1"></a>resilience_data <span class="ot">&lt;-</span> </span>
<span id="cb18-5"><a href="anova1.html#cb18-5" aria-hidden="true" tabindex="-1"></a>  resilience_data <span class="sc">%&gt;%</span> </span>
<span id="cb18-6"><a href="anova1.html#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">resilience =</span> <span class="fu">factor</span>(resilience),</span>
<span id="cb18-7"><a href="anova1.html#cb18-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">adversity  =</span> <span class="fu">factor</span>(adversity))</span></code></pre></div>
</div>
<div id="n-in-each-group" class="section level3" number="3.3.4">
<h3><span class="header-section-number">3.3.4</span> n in each group</h3>
<p>Obtain the number of participants in each group:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="anova1.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use count() to obtain the number of rows in the dataset, </span></span>
<span id="cb19-2"><a href="anova1.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># group_by() both resilience AND adversity</span></span>
<span id="cb19-3"><a href="anova1.html#cb19-3" aria-hidden="true" tabindex="-1"></a>resilience_data <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="anova1.html#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(resilience, adversity) <span class="sc">%&gt;%</span> </span>
<span id="cb19-5"><a href="anova1.html#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="left">resilience</th>
<th align="left">adversity</th>
<th align="right">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">high</td>
<td align="left">high</td>
<td align="right">106</td>
</tr>
<tr class="even">
<td align="left">high</td>
<td align="left">low</td>
<td align="right">997</td>
</tr>
<tr class="odd">
<td align="left">low</td>
<td align="left">high</td>
<td align="right">284</td>
</tr>
<tr class="even">
<td align="left">low</td>
<td align="left">low</td>
<td align="right">1050</td>
</tr>
</tbody>
</table>
</div>
<p>In a between-subjects factorial design, participants are assigned to groups by crossing the levels of one variable with those of the second variable. Thus, each row labels the level of resilience and level of adversity for that group.</p>
<ul>
<li>The number of participants in the high resilience, high adversity group is <input class='webex-solveme nospaces' size='3' data-answer='["106"]'/></li>
<li>The number of participants in the high resilience, low adversity group is <input class='webex-solveme nospaces' size='3' data-answer='["997"]'/></li>
<li>The number of participants in the low resilience, high adversity group is <input class='webex-solveme nospaces' size='3' data-answer='["284"]'/></li>
<li>The number of participants in the low resilience, low adversity group is <input class='webex-solveme nospaces' size='4' data-answer='["1050"]'/></li>
</ul>
<p><br />
</p>
</div>
<div id="visualise-the-data-1" class="section level3" number="3.3.5">
<h3><span class="header-section-number">3.3.5</span> Visualise the data</h3>
<p>The way the data are distributed in each group can be inspected with histograms or density plots.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="anova1.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use `facet_wrap(~ resilience * adversity)`</span></span>
<span id="cb20-2"><a href="anova1.html#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># to plot scores for all combinations of </span></span>
<span id="cb20-3"><a href="anova1.html#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># resilience x adversity levels</span></span>
<span id="cb20-4"><a href="anova1.html#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># use &#39;labeller = label_both&#39; to label levels by factor name</span></span>
<span id="cb20-5"><a href="anova1.html#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="anova1.html#cb20-6" aria-hidden="true" tabindex="-1"></a>resilience_data <span class="sc">%&gt;%</span> </span>
<span id="cb20-7"><a href="anova1.html#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(distress)) <span class="sc">+</span> </span>
<span id="cb20-8"><a href="anova1.html#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb20-9"><a href="anova1.html#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> resilience <span class="sc">*</span> adversity, <span class="at">labeller =</span> label_both)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-19"></span>
<img src="03_anova_between_subjects_files/figure-html/unnamed-chunk-19-1.png" alt="Density plots showing distress scores in each group)" width="75%" />
<p class="caption">
Figure 3.3: Density plots showing distress scores in each group)
</p>
</div>
<p><strong>Interpretation:</strong> The data in each group appear positively skewed - the tail of the distribution goes towards the right (i.e., towards more positive values of distress). Beutel et al. (2017) took no further action and analysed the scores as they were.</p>
<p><br />
</p>
</div>
<div id="plot-the-means-1" class="section level3" number="3.3.6">
<h3><span class="header-section-number">3.3.6</span> Plot the means</h3>
<p>Use <code>ggbarplot()</code> in the <code>ggpubr</code> package:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="anova1.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb21-2"><a href="anova1.html#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="anova1.html#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the mean of each group</span></span>
<span id="cb21-4"><a href="anova1.html#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># use &#39;desc_stat = &quot;mean_se&quot; to add SE error bars</span></span>
<span id="cb21-5"><a href="anova1.html#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># use &#39;position = position_dodge(0.3)&#39; so that points are spaced</span></span>
<span id="cb21-6"><a href="anova1.html#cb21-6" aria-hidden="true" tabindex="-1"></a>resilience_data <span class="sc">%&gt;%</span> </span>
<span id="cb21-7"><a href="anova1.html#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggerrorplot</span>(<span class="at">x =</span> <span class="st">&quot;resilience&quot;</span>, <span class="at">y =</span> <span class="st">&quot;distress&quot;</span>,  <span class="at">color =</span> <span class="st">&quot;adversity&quot;</span>,</span>
<span id="cb21-8"><a href="anova1.html#cb21-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">desc_stat =</span> <span class="st">&quot;mean_se&quot;</span>, </span>
<span id="cb21-9"><a href="anova1.html#cb21-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb21-10"><a href="anova1.html#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Resilience&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="anova1.html#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Distress&quot;</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-20"></span>
<img src="03_anova_between_subjects_files/figure-html/unnamed-chunk-20-1.png" alt="Distress as a function of adversity and resilience (error bars indicate SE of the mean)" width="75%" />
<p class="caption">
Figure 3.4: Distress as a function of adversity and resilience (error bars indicate SE of the mean)
</p>
</div>
<p><br />
</p>
<div class="tip">
<p>In a two-way design, researchers look at three things:</p>
<ul>
<li><strong>The main effect of factor 1</strong>: Overall, do scores differ according to the levels of factor 1?</li>
<li><strong>The main effect of factor 2</strong>: Overall, do scores differ according to the levels of factor 2?</li>
<li><strong>The interaction between the factors</strong>: Is the effect of one factor different at <em>each level</em> of the other factor?</li>
</ul>
</div>
<p><br />
</p>
<p>We can get some idea of the main effects and interaction by inspecting the plot of the means:</p>
<ul>
<li><strong>The main effect of resilience:</strong> Overall, distress scores in the high resilience groups appear to be <select class='webex-select'><option value='blank'></option><option value='answer'>lower than</option><option value=''>about the same as</option><option value=''>higher than</option></select> those in the low resilience groups.</li>
<li><strong>The main effect of adversity</strong>: Overall, distress scores in the low adversity groups appear to be <select class='webex-select'><option value='blank'></option><option value='answer'>lower than</option><option value=''>about the same as</option><option value=''>higher than</option></select> those in the high adversity groups.</li>
<li><strong>The interaction between resilience and distress</strong>: When trait resilience is low rather than high, the effect of adversity on distress appears to be <select class='webex-select'><option value='blank'></option><option value=''>lower</option><option value=''>similar</option><option value='answer'>greater</option></select>. (Hint: the effect of adversity is indicated by the difference between the red and blue points.)</li>
</ul>
<p><br />
</p>
</div>
<div id="bayes-factors" class="section level3" number="3.3.7">
<h3><span class="header-section-number">3.3.7</span> Bayes factors</h3>
<div class="tip">
<p>Use <code>anovaBF()</code> in the <code>BayesFactor</code> package to obtain Bayes Factors corresponding to the main effect of factor 1, the main effect of factor 2, and the interaction between factor 1 and factor 2.</p>
<p>To specify the two-way ANOVA in <code>anovaBF()</code>, use <code>dependent_variable ~ factor1 * factor2</code>.</p>
</div>
<p><br />
</p>
<p>For the resilience data:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="anova1.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain the Bayes Factors for the ANOVA model</span></span>
<span id="cb22-2"><a href="anova1.html#cb22-2" aria-hidden="true" tabindex="-1"></a>anova2x2_BF <span class="ot">&lt;-</span> <span class="fu">anovaBF</span>( distress <span class="sc">~</span> resilience <span class="sc">*</span> adversity, <span class="at">data =</span> <span class="fu">data.frame</span>(resilience_data) )</span>
<span id="cb22-3"><a href="anova1.html#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="anova1.html#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the output</span></span>
<span id="cb22-5"><a href="anova1.html#cb22-5" aria-hidden="true" tabindex="-1"></a>anova2x2_BF</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] resilience                                    : 1.822053e+27 ±0%
## [2] adversity                                     : 7.870878e+25 ±0%
## [3] resilience + adversity                        : 3.339074e+46 ±2.16%
## [4] resilience + adversity + resilience:adversity : 3.130195e+49 ±2.06%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<div class="webex-solution">
<button>
What does 1.82e+27 mean?
</button>
<p>It means 1.82 x 10<sup>27</sup>. A very large number! For more information see:
<a href="https://chrisjberry.github.io/datafluencyCB/faqs#e-meaning" target="_blank">FAQ</a> (Opens a new tab.)</p>
</div>
<p>Each BF in the output compares how likely the model is, compared to an intercept only model:</p>
<ul>
<li><code>[1] resilience</code> is the BF for the main effect of resilience. It's how much more likely a model with <code>resilience</code> alone is than an intercept-only model.</li>
<li><code>[2] adversity</code> is the BF for the main effect of adversity. It's how much more likely a model with <code>adversity</code> alone is than an intercept-only model.<br />
</li>
<li><code>[3] resilience + adversity</code> is the BF for the main effects of resilience and adversity. It's how much more likely a model with main effects of <code>resilience</code> and <code>adversity</code> is than an intercept-only model.<br />
</li>
<li><code>[4] resilience + adversity + resilience:adversity</code> is the BF for the main effects of resilience and adversity <strong>and</strong> the interaction between them (<code>resilience:adversity</code>). It's how much more likely a model with main effects of <code>resilience</code> and <code>adversity</code> and also the interaction (<code>resilience:adversity</code>) is than an intercept-only model.</li>
</ul>
<p><code>[1]</code> and <code>[2]</code> correspond to the main effects of <code>resilience</code> and <code>adversity</code>, respectively. To obtain the BF for the interaction, we need to divide <code>[4]</code> by <code>[3]</code>:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="anova1.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># BF for the interaction</span></span>
<span id="cb24-2"><a href="anova1.html#cb24-2" aria-hidden="true" tabindex="-1"></a>anova2x2_BF[<span class="dv">4</span>] <span class="sc">/</span> anova2x2_BF[<span class="dv">3</span>]</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] resilience + adversity + resilience:adversity : 937.444 ±2.98%
## 
## Against denominator:
##   distress ~ resilience + adversity 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>This BF then tells us whether there's evidence for the addition of an interaction term to a model containing the main effects of each factor. This is the BF for the interaction.</p>
<p>Record the Bayes factors below:</p>
<ul>
<li>The BF for the main effect of <code>resilience</code> is BF = <input class='webex-solveme nospaces' size='4' data-answer='["1.82"]'/> x 10<sup>27</sup>.</li>
<li>The BF for the main effect of <code>adversity</code> is BF = <input class='webex-solveme nospaces' size='4' data-answer='["7.87"]'/> x 10<sup>25</sup>.</li>
<li>The BF for the <code>resilience</code> and <code>adversity</code> interaction is approximately (to the nearest whole number) <input class='webex-solveme nospaces' data-tol='5' size='3' data-answer='["939"]'/>.</li>
</ul>
<div class="webex-solution">
<button>
Meaning of ±number%
</button>
<p>You'll notice that some of BFs had <code>±1.03%</code> or similar next to them in the output. This is the error associated with the BF. It's like saying my height is 185 cm, plus or minus a millimeter or so. It can be non-zero because generation of the BFs involves random sampling processes. Larger error values mean that the exact same value of the BF won't necessarily be output each time the line of code containing <code>anovaBF()</code> is run, so there's a chance that the BFs in your output differ slightly from those above (particularly for the interaction). This is why I asked you to give your answer to the nearest whole number.</p>
</div>
<p><br />
</p>
</div>
<div id="r2-2" class="section level3" number="3.3.8">
<h3><span class="header-section-number">3.3.8</span> R<sup>2</sup></h3>
<div class="tip">
<p>Once again, <code>glance()</code> can be used to obtain R<sup>2</sup> for the ANOVA model. The model first needs to be specified with <code>lm()</code>. Using <code>factor1 * factor2</code> when specifying the model is a shortcut, which will automatically specify the full model containing the interaction. We can use <code>lm(distress ~ resilience * adversity)</code>, which is equivalent to <code>lm(distress ~ resilience + adversity + resilience*adversity)</code>.</p>
</div>
<p><br />
</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="anova1.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specify the ANOVA model using lm()</span></span>
<span id="cb26-2"><a href="anova1.html#cb26-2" aria-hidden="true" tabindex="-1"></a>anova2x2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(distress <span class="sc">~</span> resilience <span class="sc">*</span> adversity, <span class="at">data =</span> resilience_data)</span>
<span id="cb26-3"><a href="anova1.html#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="anova1.html#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># R^2^</span></span>
<span id="cb26-5"><a href="anova1.html#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(anova2x2)</span></code></pre></div>
<div class="kable-table">
<table>
<colgroup>
<col width="9%" />
<col width="12%" />
<col width="8%" />
<col width="9%" />
<col width="7%" />
<col width="2%" />
<col width="9%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="11%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.0963021</td>
<td align="right">0.0951878</td>
<td align="right">2.142569</td>
<td align="right">86.42379</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">-5312.959</td>
<td align="right">10635.92</td>
<td align="right">10664.91</td>
<td align="right">11168.93</td>
<td align="right">2433</td>
<td align="right">2437</td>
</tr>
</tbody>
</table>
</div>
<p>The adjusted R<sup>2</sup> of the ANOVA model (to two decimal places, as a <em>percentage</em>) is <input class='webex-solveme nospaces' size='4' data-answer='["9.52"]'/> %, which is the percentage of variance in distress explained by the model.</p>
<p><br />
</p>
</div>
<div id="follow-up-comparisons" class="section level3" number="3.3.9">
<h3><span class="header-section-number">3.3.9</span> Follow-up comparisons</h3>
<p>Given that we have evidence for an interaction, <code>anovaBF()</code> can be used to conduct follow-up comparisons to explore the nature of the interaction. (Note, we would not do this if the BF did not show evidence for the interaction, i.e., if the BF was less than 3.)</p>
<p>The interaction implies the effect of <code>adversity</code> is different in individuals with <code>high</code> resilience, and those with <code>low</code> resilience.</p>
<p>To determine the evidence for the effect of adversity in individuals with high resilience:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="anova1.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. The effect of adversity in individuals with high resilience</span></span>
<span id="cb27-2"><a href="anova1.html#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="anova1.html#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># First use filter() to store only </span></span>
<span id="cb27-4"><a href="anova1.html#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># the data from the &#39;high&#39; resilience groups</span></span>
<span id="cb27-5"><a href="anova1.html#cb27-5" aria-hidden="true" tabindex="-1"></a>resilience_high <span class="ot">&lt;-</span> </span>
<span id="cb27-6"><a href="anova1.html#cb27-6" aria-hidden="true" tabindex="-1"></a>  resilience_data <span class="sc">%&gt;%</span> </span>
<span id="cb27-7"><a href="anova1.html#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(resilience <span class="sc">==</span> <span class="st">&quot;high&quot;</span>)</span>
<span id="cb27-8"><a href="anova1.html#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="anova1.html#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Then use `anovaBF()` to look at effect of adversity in resilience_high</span></span>
<span id="cb27-10"><a href="anova1.html#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>( distress <span class="sc">~</span> adversity, <span class="at">data =</span> <span class="fu">data.frame</span>(resilience_high) )</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] adversity : 1.026598 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>To determine the evidence for the effect of <code>adversity</code> in individuals with <code>low</code> resilience:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="anova1.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. The effect of adversity in individuals with low resilience</span></span>
<span id="cb29-2"><a href="anova1.html#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="anova1.html#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># First use filter() to store only </span></span>
<span id="cb29-4"><a href="anova1.html#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># the data from the &#39;low&#39; resilience groups</span></span>
<span id="cb29-5"><a href="anova1.html#cb29-5" aria-hidden="true" tabindex="-1"></a>resilience_low <span class="ot">&lt;-</span> </span>
<span id="cb29-6"><a href="anova1.html#cb29-6" aria-hidden="true" tabindex="-1"></a>  resilience_data <span class="sc">%&gt;%</span> </span>
<span id="cb29-7"><a href="anova1.html#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(resilience <span class="sc">==</span> <span class="st">&quot;low&quot;</span>)</span>
<span id="cb29-8"><a href="anova1.html#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="anova1.html#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Then use `anovaBF()` to look at effect of adversity in resilience_low</span></span>
<span id="cb29-10"><a href="anova1.html#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>( distress <span class="sc">~</span> adversity, <span class="at">data =</span> <span class="fu">data.frame</span>(resilience_low) )</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] adversity : 2.389569e+17 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>This confirms the interaction that is apparent in the plot: There's no evidence for an effect of adversity within high resilience individuals (BF = <input class='webex-solveme nospaces' size='4' data-answer='["1.03"]'/>), but there's substantial evidence for an effect of adversity within low resilience individuals (BF = <input class='webex-solveme nospaces' size='4' data-answer='["2.39"]'/>x 10<sup>17</sup>), such that levels of distress are greatest when the level of adversity is highest. Interestingly, this suggests that resilience may have a <em>buffering effect</em> on the distress experienced as a result of childhood adversity (see Beutel et al., 2017, for further discussion).</p>
<p><br />
</p>
</div>
</div>
<div id="exercise-one-way" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Exercise: one-way</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-3" class="exercise"><strong>Exercise 3.3  </strong></span>One-way ANOVA</p>
<p>The data at the link below are from a study by Bobak et al. (2016). They looked at the face matching <code>performance</code> of individuals with superior face recognition abilities, so called "super recognisers". Their performance was compared to two control groups. In one control group, payment was linked to performance (labelled "motivated_control"). The individuals in the other control group were not paid (labelled "control"). The column <code>face_group</code> contains the labels for each group.</p>
<p><a href="https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_super_data.csv" class="uri">https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_super_data.csv</a></p>
<p>Conduct a one-way ANOVA to compare the <code>performance</code> across the three groups.</p>
<p><br />
</p>
<p><strong>Adapt the code in this worksheet to do the following:</strong></p>
<p><strong>1. Read in the data and store in <code>super_data</code></strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Ensure the <code>tidyverse</code> package is loaded. See <code>?read_csv()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="anova1.html#cb31-1" aria-hidden="true" tabindex="-1"></a>super_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_super_data.csv&#39;</span>)</span>
<span id="cb31-2"><a href="anova1.html#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="anova1.html#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the raw data</span></span>
<span id="cb31-4"><a href="anova1.html#cb31-4" aria-hidden="true" tabindex="-1"></a>super_data</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>2. Convert the independent variable to a factor</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>See <code>?mutate()</code> and <code>?factor()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="anova1.html#cb32-1" aria-hidden="true" tabindex="-1"></a>super_data <span class="ot">&lt;-</span> </span>
<span id="cb32-2"><a href="anova1.html#cb32-2" aria-hidden="true" tabindex="-1"></a>  super_data <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="anova1.html#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">face_group =</span> <span class="fu">factor</span>(face_group) )</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>3. Obtain n in each group</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Pipe the data to <code>group_by()</code> and <code>count()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="anova1.html#cb33-1" aria-hidden="true" tabindex="-1"></a>super_data <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="anova1.html#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(face_group) <span class="sc">%&gt;%</span> </span>
<span id="cb33-3"><a href="anova1.html#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div>
</div>
<ul>
<li><em>n</em> super recognisers = <input class='webex-solveme nospaces' size='1' data-answer='["7"]'/></li>
<li><em>n</em> motivated_control = <input class='webex-solveme nospaces' size='2' data-answer='["20"]'/></li>
<li><em>n</em> control = <input class='webex-solveme nospaces' size='2' data-answer='["20"]'/></li>
</ul>
<p><br />
</p>
<p><strong>4. Produce a histogram of scores in each group</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Pipe the data to <code>ggplot()</code> and <code>geom_histogram()</code> and <code>facet_wrap()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="anova1.html#cb34-1" aria-hidden="true" tabindex="-1"></a>super_data <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="anova1.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(performance)) <span class="sc">+</span></span>
<span id="cb34-3"><a href="anova1.html#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb34-4"><a href="anova1.html#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>face_group)</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>5. Produce a plot of the means (with SEs) in each group</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p><code>?ggerrorplot()</code> in the <code>ggpubr</code> package</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="anova1.html#cb35-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># produce means plot</span></span>
<span id="cb35-2"><a href="anova1.html#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="anova1.html#cb35-3" aria-hidden="true" tabindex="-1"></a>super_data <span class="sc">%&gt;%</span> </span>
<span id="cb35-4"><a href="anova1.html#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggerrorplot</span>(<span class="at">x =</span> <span class="st">&quot;face_group&quot;</span>, <span class="at">y =</span><span class="st">&quot;performance&quot;</span>, <span class="at">desc_stat =</span> <span class="st">&quot;mean_se&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="anova1.html#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Group&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="anova1.html#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Face matching performance&quot;</span>)</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>6. Obtain the mean and SE of each group</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Use <code>group_by()</code> and <code>summarise()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="anova1.html#cb36-1" aria-hidden="true" tabindex="-1"></a>super_data <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="anova1.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(face_group) <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="anova1.html#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="at">M  =</span> <span class="fu">mean</span>(performance), </span>
<span id="cb36-4"><a href="anova1.html#cb36-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">SE =</span> <span class="fu">sd</span>(performance) <span class="sc">/</span> <span class="fu">sqrt</span>( <span class="fu">n</span>() ) )</span></code></pre></div>
</div>
<ul>
<li>The mean score of the <code>super_recogniser</code> group is <input class='webex-solveme nospaces' size='4' data-answer='["4.23"]'/>, SE = <input class='webex-solveme nospaces' size='4' data-answer='["0.28"]'/></li>
<li>The mean score of the <code>motivated_control</code> group is <input class='webex-solveme nospaces' size='4' data-answer='["3.09"]'/>, SE = <input class='webex-solveme nospaces' size='4' data-answer='["0.14"]'/></li>
<li>The mean score of the <code>control</code> group is <input class='webex-solveme nospaces' size='4' data-answer='["2.82"]'/>, SE = <input class='webex-solveme nospaces' size='4' data-answer='["0.16"]'/></li>
</ul>
<p><br />
</p>
<p><strong>7. Obtain the Bayes factor for the ANOVA model</strong></p>
<ul>
<li>The Bayes factor for the model is equal to (to two decimal places) <input class='webex-solveme nospaces' size='6' data-answer='["118.27"]'/>.</li>
<li>This indicates that there is <select class='webex-select'><option value='blank'></option><option value=''>no evidence</option><option value='answer'>substantial evidence</option></select> for an effect of the face group on matching performance.</li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<p><code>?anovaBF()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="anova1.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>(performance <span class="sc">~</span> face_group, <span class="at">data =</span> <span class="fu">data.frame</span>(super_data))</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>8. What is R<sup>2</sup> for the model?</strong></p>
<p>The adjusted R<sup>2</sup> for the effect of face group on matching performance is (to two decimal places) <input class='webex-solveme nospaces' size='5' data-answer='["30.11"]'/> %</p>
<div class="webex-solution">
<button>
Hint
</button>
<p>obtain the model with <code>lm()</code>, then use <code>glance()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="anova1.html#cb38-1" aria-hidden="true" tabindex="-1"></a>super_anova <span class="ot">&lt;-</span> <span class="fu">lm</span>(performance <span class="sc">~</span> face_group, <span class="at">data =</span> super_data)</span>
<span id="cb38-2"><a href="anova1.html#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(super_anova)</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>9. Conduct follow-up tests to compare the mean score of each group</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<ul>
<li>Use <code>filter()</code> to create new variables containing the scores of two groups at a time</li>
<li>Then use <code>anovaBF()</code> to compare the scores of each group.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Solution using anovaBF()
</button>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="anova1.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># super_recognisers vs. motivated_control</span></span>
<span id="cb39-2"><a href="anova1.html#cb39-2" aria-hidden="true" tabindex="-1"></a>super_vs_motivated_controls <span class="ot">&lt;-</span> </span>
<span id="cb39-3"><a href="anova1.html#cb39-3" aria-hidden="true" tabindex="-1"></a>  super_data <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="anova1.html#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(face_group <span class="sc">==</span> <span class="st">&quot;super_recogniser&quot;</span> <span class="sc">|</span> face_group <span class="sc">==</span> <span class="st">&quot;motivated_control&quot;</span>)</span>
<span id="cb39-5"><a href="anova1.html#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="anova1.html#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>(performance <span class="sc">~</span> face_group, <span class="at">data =</span> <span class="fu">data.frame</span>(super_vs_motivated_controls))</span>
<span id="cb39-7"><a href="anova1.html#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="anova1.html#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="anova1.html#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="co"># super_recognisers vs. control</span></span>
<span id="cb39-10"><a href="anova1.html#cb39-10" aria-hidden="true" tabindex="-1"></a>super_vs_controls <span class="ot">&lt;-</span> </span>
<span id="cb39-11"><a href="anova1.html#cb39-11" aria-hidden="true" tabindex="-1"></a>  super_data <span class="sc">%&gt;%</span></span>
<span id="cb39-12"><a href="anova1.html#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(face_group <span class="sc">==</span> <span class="st">&quot;super_recogniser&quot;</span> <span class="sc">|</span> face_group <span class="sc">==</span> <span class="st">&quot;control&quot;</span>)</span>
<span id="cb39-13"><a href="anova1.html#cb39-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-14"><a href="anova1.html#cb39-14" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>(performance <span class="sc">~</span> face_group, <span class="at">data =</span> <span class="fu">data.frame</span>(super_vs_controls))</span>
<span id="cb39-15"><a href="anova1.html#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="anova1.html#cb39-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-17"><a href="anova1.html#cb39-17" aria-hidden="true" tabindex="-1"></a><span class="co"># motivated_control vs. control</span></span>
<span id="cb39-18"><a href="anova1.html#cb39-18" aria-hidden="true" tabindex="-1"></a>motivated_control_vs_control <span class="ot">&lt;-</span> </span>
<span id="cb39-19"><a href="anova1.html#cb39-19" aria-hidden="true" tabindex="-1"></a>  super_data <span class="sc">%&gt;%</span></span>
<span id="cb39-20"><a href="anova1.html#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(face_group <span class="sc">==</span> <span class="st">&quot;motivated_control&quot;</span> <span class="sc">|</span> face_group <span class="sc">==</span> <span class="st">&quot;control&quot;</span>)</span>
<span id="cb39-21"><a href="anova1.html#cb39-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-22"><a href="anova1.html#cb39-22" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>(performance <span class="sc">~</span> face_group, <span class="at">data =</span> <span class="fu">data.frame</span>(motivated_control_vs_control))</span></code></pre></div>
</div>
<div class="webex-solution">
<button>
Solution using ttestBF()
</button>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="anova1.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># super_recognisers vs. motivated_control</span></span>
<span id="cb40-2"><a href="anova1.html#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestBF</span>(<span class="at">x =</span> super_data<span class="sc">$</span>performance[super_data<span class="sc">$</span>face_group <span class="sc">==</span> <span class="st">&quot;super_recogniser&quot;</span>],</span>
<span id="cb40-3"><a href="anova1.html#cb40-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> super_data<span class="sc">$</span>performance[super_data<span class="sc">$</span>face_group <span class="sc">==</span> <span class="st">&quot;motivated_control&quot;</span>])</span>
<span id="cb40-4"><a href="anova1.html#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="anova1.html#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># super_recognisers vs. control</span></span>
<span id="cb40-6"><a href="anova1.html#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestBF</span>(<span class="at">x =</span> super_data<span class="sc">$</span>performance[super_data<span class="sc">$</span>face_group <span class="sc">==</span> <span class="st">&quot;super_recogniser&quot;</span>],</span>
<span id="cb40-7"><a href="anova1.html#cb40-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> super_data<span class="sc">$</span>performance[super_data<span class="sc">$</span>face_group <span class="sc">==</span> <span class="st">&quot;control&quot;</span>])</span>
<span id="cb40-8"><a href="anova1.html#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="anova1.html#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="co"># motivated_control vs. control</span></span>
<span id="cb40-10"><a href="anova1.html#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestBF</span>(<span class="at">x =</span> super_data<span class="sc">$</span>performance[super_data<span class="sc">$</span>face_group <span class="sc">==</span> <span class="st">&quot;motivated_control&quot;</span>],</span>
<span id="cb40-11"><a href="anova1.html#cb40-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> super_data<span class="sc">$</span>performance[super_data<span class="sc">$</span>face_group <span class="sc">==</span> <span class="st">&quot;control&quot;</span>])</span></code></pre></div>
</div>
<ul>
<li>The Bayes factor comparing the <code>super_recogniser</code> and <code>motivated_control</code> groups is <input class='webex-solveme nospaces' size='5' data-answer='["47.28"]'/>, indicating <select class='webex-select'><option value='blank'></option><option value='answer'>substantial evidence for</option><option value=''>substantial evidence against there being</option></select> a difference between groups.</li>
<li>Face matching performance in the <code>super_recogniser</code> group was <select class='webex-select'><option value='blank'></option><option value=''>the same</option><option value=''>lower</option><option value='answer'>higher</option></select> than that of the <code>motivated_control</code> group.</li>
<li>The Bayes factor comparing the <code>super_recogniser</code> and <code>control</code> groups is <input class='webex-solveme nospaces' size='6' data-answer='["113.41"]'/>, indicating <select class='webex-select'><option value='blank'></option><option value='answer'>substantial evidence for</option><option value=''>substantial evidence against there being</option></select> a difference between groups.</li>
<li>Face matching performance in the <code>super_recogniser</code> group was <select class='webex-select'><option value='blank'></option><option value=''>the same</option><option value=''>lower</option><option value='answer'>higher</option></select> than that of the <code>control</code> group.</li>
<li>The Bayes factor comparing the <code>motivated_control</code> and <code>control</code> groups is <input class='webex-solveme nospaces' size='4' data-answer='["0.55"]'/>, indicating that there was <select class='webex-select'><option value='blank'></option><option value=''>substantial evidence for a</option><option value='answer'>insufficient evidence for a</option><option value=''>substantial evidence for an absence of a</option></select> difference between the scores of each group.</li>
</ul>
</div>
<p><br />
</p>
</div>
<div id="exercise-two-way" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Exercise: two-way</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-4" class="exercise"><strong>Exercise 3.4  </strong></span>Two-way ANOVA</p>
<p>Horstmann et al. (2018) looked at whether the type of <code>exchange</code> that people had with a robot would affect how long it would then take for them to switch it off. The type of <code>exchange</code> was either 'functional' or 'social'. Additionally, the researchers looked at the effect of the type of <code>objection</code> that the robot made during the conversation. The robot either voiced an 'objection' to being switched off, or voiced 'no objection'.</p>
<p>The <code>robot_data</code> are located at the link below:</p>
<p><a href="https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_robot_data.csv" class="uri">https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_robot_data.csv</a></p>
<p><br />
</p>
<p><strong>Adapt the code in this worksheet to do the following:</strong></p>
<ol style="list-style-type: decimal">
<li><strong>Conduct a two-way ANOVA to compare the effects of <code>exchange</code> and <code>objection</code> on <code>time</code>. Determine whether there's sufficient evidence for the following:</strong></li>
</ol>
<ul>
<li>The main effect of <code>objection</code>: BF (to two decimal places) = <input class='webex-solveme nospaces' size='4' data-answer='["6.29"]'/></li>
<li>The main effect of <code>exchange</code>: BF (to two decimal places) = <input class='webex-solveme nospaces' size='4' data-answer='["0.74"]'/></li>
<li>The interaction between <code>exchange</code> and <code>objection</code>: BF (nearest whole number) = <input class='webex-solveme nospaces' data-tol='0.4' size='1' data-answer='["3"]'/></li>
</ul>
<p><br />
</p>
<ol start="2" style="list-style-type: decimal">
<li><strong>Conduct any follow-up tests concerning the interaction (if necessary).</strong></li>
</ol>
<ul>
<li>The effect of <code>exchange</code> when the robot objected: BF (to two decimal places) = <input class='webex-solveme nospaces' size='4' data-answer='["1.55"]'/></li>
<li>The effect of <code>exchange</code> when the robot did not object: BF (to two decimal places) = <input class='webex-solveme nospaces' size='4' data-answer='["0.47"]'/></li>
</ul>
<p><br />
</p>
<ol start="3" style="list-style-type: decimal">
<li><strong>Interpret the main effects and interaction. What do they mean?</strong></li>
</ol>
<p><br />
</p>
<div class="webex-solution">
<button>
Hint - code
</button>
<ul>
<li>Read in the data to a variable called <code>robot_data</code></li>
<li>Convert the independent variables to factors using <code>factor()</code></li>
<li>Examine the distribution of <code>time</code> in each group using <code>geom_histogram()</code> or <code>geom_density()</code> in <code>ggplot()</code></li>
<li>Obtain summary statistics using <code>group_by()</code>, <code>count()</code> and <code>summarise(mean())</code></li>
<li>Use a plot from the <code>ggpubr</code> package to create a plot of the means (e.g., <code>ggerrorplot()</code>)</li>
<li>Use <code>anovaBF()</code> to obtain the Bayes factors to allow you to assess evidence for the main effects and interaction.</li>
<li>If there's evidence for an interaction, then conduct follow-up tests using <code>anovaBF()</code> or <code>ttestBF()</code></li>
</ul>
</div>
<div class="webex-solution">
<button>
Solution - code
</button>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="anova1.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ensure following packages have been loaded</span></span>
<span id="cb41-2"><a href="anova1.html#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(tidyverse)</span></span>
<span id="cb41-3"><a href="anova1.html#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># library(BayesFactor)</span></span>
<span id="cb41-4"><a href="anova1.html#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># library(ggpubr)</span></span>
<span id="cb41-5"><a href="anova1.html#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="anova1.html#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="co"># read the data</span></span>
<span id="cb41-7"><a href="anova1.html#cb41-7" aria-hidden="true" tabindex="-1"></a>robot_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://raw.githubusercontent.com/chrisjberry/Teaching/master/3_robot_data.csv&#39;</span>)</span>
<span id="cb41-8"><a href="anova1.html#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="anova1.html#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="co"># convert IVs to factors</span></span>
<span id="cb41-10"><a href="anova1.html#cb41-10" aria-hidden="true" tabindex="-1"></a>robot_data <span class="ot">&lt;-</span></span>
<span id="cb41-11"><a href="anova1.html#cb41-11" aria-hidden="true" tabindex="-1"></a>  robot_data <span class="sc">%&gt;%</span> </span>
<span id="cb41-12"><a href="anova1.html#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">exchange  =</span> <span class="fu">factor</span>(exchange),</span>
<span id="cb41-13"><a href="anova1.html#cb41-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">objection =</span> <span class="fu">factor</span>(objection)) </span>
<span id="cb41-14"><a href="anova1.html#cb41-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-15"><a href="anova1.html#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect distributions</span></span>
<span id="cb41-16"><a href="anova1.html#cb41-16" aria-hidden="true" tabindex="-1"></a>robot_data <span class="sc">%&gt;%</span> </span>
<span id="cb41-17"><a href="anova1.html#cb41-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>( <span class="fu">aes</span>(time) ) <span class="sc">+</span> </span>
<span id="cb41-18"><a href="anova1.html#cb41-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb41-19"><a href="anova1.html#cb41-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> exchange<span class="sc">*</span>objection)</span>
<span id="cb41-20"><a href="anova1.html#cb41-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-21"><a href="anova1.html#cb41-21" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain M and SE each group</span></span>
<span id="cb41-22"><a href="anova1.html#cb41-22" aria-hidden="true" tabindex="-1"></a>robot_data <span class="sc">%&gt;%</span> </span>
<span id="cb41-23"><a href="anova1.html#cb41-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(exchange, objection) <span class="sc">%&gt;%</span> </span>
<span id="cb41-24"><a href="anova1.html#cb41-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="at">M =</span> <span class="fu">mean</span>(time), <span class="at">SE =</span> <span class="fu">sd</span>(time)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>()) )</span>
<span id="cb41-25"><a href="anova1.html#cb41-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-26"><a href="anova1.html#cb41-26" aria-hidden="true" tabindex="-1"></a><span class="co"># plot of means</span></span>
<span id="cb41-27"><a href="anova1.html#cb41-27" aria-hidden="true" tabindex="-1"></a>robot_data <span class="sc">%&gt;%</span> </span>
<span id="cb41-28"><a href="anova1.html#cb41-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggerrorplot</span>(<span class="at">x =</span> <span class="st">&quot;objection&quot;</span>, <span class="at">y =</span> <span class="st">&quot;time&quot;</span>, <span class="at">color =</span> <span class="st">&quot;exchange&quot;</span>,</span>
<span id="cb41-29"><a href="anova1.html#cb41-29" aria-hidden="true" tabindex="-1"></a>              <span class="at">desc_stat =</span> <span class="st">&quot;mean_se&quot;</span>, </span>
<span id="cb41-30"><a href="anova1.html#cb41-30" aria-hidden="true" tabindex="-1"></a>              <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb41-31"><a href="anova1.html#cb41-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Type of exchange&quot;</span>) <span class="sc">+</span></span>
<span id="cb41-32"><a href="anova1.html#cb41-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Switch off time (seconds)&quot;</span>) </span>
<span id="cb41-33"><a href="anova1.html#cb41-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-34"><a href="anova1.html#cb41-34" aria-hidden="true" tabindex="-1"></a><span class="co"># 2x2 ANOVA</span></span>
<span id="cb41-35"><a href="anova1.html#cb41-35" aria-hidden="true" tabindex="-1"></a>BF_robot <span class="ot">&lt;-</span> <span class="fu">anovaBF</span>( time <span class="sc">~</span> exchange<span class="sc">*</span>objection, <span class="at">data =</span> <span class="fu">data.frame</span>(robot_data) )</span>
<span id="cb41-36"><a href="anova1.html#cb41-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-37"><a href="anova1.html#cb41-37" aria-hidden="true" tabindex="-1"></a><span class="co"># look at BFs</span></span>
<span id="cb41-38"><a href="anova1.html#cb41-38" aria-hidden="true" tabindex="-1"></a>BF_robot</span>
<span id="cb41-39"><a href="anova1.html#cb41-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-40"><a href="anova1.html#cb41-40" aria-hidden="true" tabindex="-1"></a><span class="co"># main effect objection</span></span>
<span id="cb41-41"><a href="anova1.html#cb41-41" aria-hidden="true" tabindex="-1"></a>BF_robot[<span class="dv">1</span>]</span>
<span id="cb41-42"><a href="anova1.html#cb41-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-43"><a href="anova1.html#cb41-43" aria-hidden="true" tabindex="-1"></a><span class="co"># main effect exchange</span></span>
<span id="cb41-44"><a href="anova1.html#cb41-44" aria-hidden="true" tabindex="-1"></a>BF_robot[<span class="dv">2</span>]</span>
<span id="cb41-45"><a href="anova1.html#cb41-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-46"><a href="anova1.html#cb41-46" aria-hidden="true" tabindex="-1"></a><span class="co"># interaction</span></span>
<span id="cb41-47"><a href="anova1.html#cb41-47" aria-hidden="true" tabindex="-1"></a>BF_robot[<span class="dv">4</span>] <span class="sc">/</span> BF_robot[<span class="dv">3</span>]</span>
<span id="cb41-48"><a href="anova1.html#cb41-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-49"><a href="anova1.html#cb41-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-50"><a href="anova1.html#cb41-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Given the evidence for an interaction, conduct further comparisons</span></span>
<span id="cb41-51"><a href="anova1.html#cb41-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-52"><a href="anova1.html#cb41-52" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. The effect of exchange when the robot objected (i.e., `objection`)</span></span>
<span id="cb41-53"><a href="anova1.html#cb41-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-54"><a href="anova1.html#cb41-54" aria-hidden="true" tabindex="-1"></a><span class="co"># use filter() to store only </span></span>
<span id="cb41-55"><a href="anova1.html#cb41-55" aria-hidden="true" tabindex="-1"></a><span class="co"># the data from the &#39;objection&#39; groups</span></span>
<span id="cb41-56"><a href="anova1.html#cb41-56" aria-hidden="true" tabindex="-1"></a>robot_objection <span class="ot">&lt;-</span> </span>
<span id="cb41-57"><a href="anova1.html#cb41-57" aria-hidden="true" tabindex="-1"></a>  robot_data <span class="sc">%&gt;%</span> </span>
<span id="cb41-58"><a href="anova1.html#cb41-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(objection <span class="sc">==</span> <span class="st">&quot;objection&quot;</span>)</span>
<span id="cb41-59"><a href="anova1.html#cb41-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-60"><a href="anova1.html#cb41-60" aria-hidden="true" tabindex="-1"></a><span class="co"># use `anovaBF()` to look at effect of exchange in the objection groups</span></span>
<span id="cb41-61"><a href="anova1.html#cb41-61" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>( time <span class="sc">~</span> exchange, <span class="at">data =</span> <span class="fu">data.frame</span>(robot_objection) )</span>
<span id="cb41-62"><a href="anova1.html#cb41-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-63"><a href="anova1.html#cb41-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-64"><a href="anova1.html#cb41-64" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. The effect of exchange when the robot did not object</span></span>
<span id="cb41-65"><a href="anova1.html#cb41-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-66"><a href="anova1.html#cb41-66" aria-hidden="true" tabindex="-1"></a><span class="co"># use filter() to store only </span></span>
<span id="cb41-67"><a href="anova1.html#cb41-67" aria-hidden="true" tabindex="-1"></a><span class="co"># the data from the &#39;no_objection&#39; groups</span></span>
<span id="cb41-68"><a href="anova1.html#cb41-68" aria-hidden="true" tabindex="-1"></a>robot_no_objection <span class="ot">&lt;-</span> </span>
<span id="cb41-69"><a href="anova1.html#cb41-69" aria-hidden="true" tabindex="-1"></a>  robot_data <span class="sc">%&gt;%</span> </span>
<span id="cb41-70"><a href="anova1.html#cb41-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(objection <span class="sc">==</span> <span class="st">&quot;no_objection&quot;</span>)</span>
<span id="cb41-71"><a href="anova1.html#cb41-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-72"><a href="anova1.html#cb41-72" aria-hidden="true" tabindex="-1"></a><span class="co"># use `anovaBF()` to look at effect of exchange in the no objection groups</span></span>
<span id="cb41-73"><a href="anova1.html#cb41-73" aria-hidden="true" tabindex="-1"></a><span class="fu">anovaBF</span>( time <span class="sc">~</span> exchange, <span class="at">data =</span> <span class="fu">data.frame</span>(robot_no_objection) )</span>
<span id="cb41-74"><a href="anova1.html#cb41-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-75"><a href="anova1.html#cb41-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-76"><a href="anova1.html#cb41-76" aria-hidden="true" tabindex="-1"></a><span class="co"># For the interpretation of main effects:</span></span>
<span id="cb41-77"><a href="anova1.html#cb41-77" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb41-78"><a href="anova1.html#cb41-78" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain M and SE for the main effect of objection</span></span>
<span id="cb41-79"><a href="anova1.html#cb41-79" aria-hidden="true" tabindex="-1"></a>robot_data <span class="sc">%&gt;%</span> </span>
<span id="cb41-80"><a href="anova1.html#cb41-80" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(objection) <span class="sc">%&gt;%</span> </span>
<span id="cb41-81"><a href="anova1.html#cb41-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="at">M =</span> <span class="fu">mean</span>(time), </span>
<span id="cb41-82"><a href="anova1.html#cb41-82" aria-hidden="true" tabindex="-1"></a>             <span class="at">SE =</span> <span class="fu">sd</span>(time)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>()) )</span>
<span id="cb41-83"><a href="anova1.html#cb41-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-84"><a href="anova1.html#cb41-84" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain M and SE for the main effect of exchange</span></span>
<span id="cb41-85"><a href="anova1.html#cb41-85" aria-hidden="true" tabindex="-1"></a>robot_data <span class="sc">%&gt;%</span> </span>
<span id="cb41-86"><a href="anova1.html#cb41-86" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(exchange) <span class="sc">%&gt;%</span> </span>
<span id="cb41-87"><a href="anova1.html#cb41-87" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( <span class="at">M =</span> <span class="fu">mean</span>(time), </span>
<span id="cb41-88"><a href="anova1.html#cb41-88" aria-hidden="true" tabindex="-1"></a>             <span class="at">SE =</span> <span class="fu">sd</span>(time)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>()) )</span></code></pre></div>
</div>
<p><br />
</p>
<div class="webex-solution">
<button>
Hint - interpretation
</button>
<p>To aid your interpretation of the main effects and interaction, look at the mean of the scores in each group. In which groups is the <code>time</code> taken to switch off the robot longer than others? How does <code>time</code> differ according to type of <code>exchange</code>? How does <code>time</code> differ according to type of <code>objection</code>? Does the effect of <code>exchange</code> seem to be the same at each level of <code>objection</code>?</p>
</div>
<div class="webex-solution">
<button>
Solution - interpretation
</button>
<p>There was substantial evidence for a main effect of objection on the time it took for a participant to switch off a robot (BF = 6.29). Participants took longer when the robot had previously mentioned that it objected to being switched off (<em>M</em> = 10.00 seconds, <em>SE</em> = 2.21), compared to when no objection was mentioned (<em>M</em> = 4.69, <em>SE</em> = 0.37).</p>
<p>There was insufficient evidence for a main effect of exchange, given that the Bayes factor was inconclusive (BF = 0.74). Thus, there was no evidence to suggest that the time to switch off a robot differed according to whether the type of exchange was functional (<em>M</em> = 8.69, <em>SE</em> = 2.00) or social (<em>M</em> = 5.54, <em>SE</em> = 0.57).</p>
<p>The main effects should be viewed in light of the substantial evidence for an interaction between exchange and objection (BF = 3.28). This indicated that it took people longer to switch the robot off when the exchange had been functional, rather than social, but only if the robot had objected to being switched off (<em>M</em> functional = 14.40, <em>SE</em> = 4.11 vs. <em>M</em> social = 6.19, <em>SE</em> = 1.15). When the robot had not previously objected to being switched off, the times were similar following functional and social exchanges (<em>M</em> functional = 4.28, SE = 0.59, vs. <em>M</em> social = 5.05, SE = 0.48). Follow-up tests indicated insufficient evidence for the effect of exchange at each level of objection (i.e., BFs &lt; 3 and BFs &gt; 0.33): The Bayes factor for the effect of exchange when the robot objected was 1.55, and the Bayes factor for the effect of exchange when the robot did not object was 0.47.</p>
</div>
</div>
<p><br />
</p>
</div>
<div id="summary-1" class="section level2" number="3.6">
<h2><span class="header-section-number">3.6</span> Summary</h2>
<ul>
<li>ANOVA is a special case of regression when the predictor variables are entirely categorical.</li>
<li>A <strong>one-way between-subjects ANOVA</strong> has one independent variable, and separate groups of participants for each level of the independent variable. The test looks at whether the mean scores differ between groups.</li>
<li>A <strong>two-way between-subjects ANOVA</strong> has two independent variables (factors). Each factor has levels. Researchers examine evidence for the main effect of each factor and their interaction.</li>
<li>The interaction examines the effect of one factor at each level of the other factor.</li>
<li>If there's evidence for an interaction, follow-up comparisons can be performed.</li>
<li>Use <code>anovaBF()</code> to obtain Bayes factors for the main effects and interaction.</li>
</ul>
<p><br />
</p>
</div>
<div id="references-2" class="section level2" number="3.7">
<h2><span class="header-section-number">3.7</span> References</h2>
<p>Beutel M.E., Tibubos A.N., Klein E.M., Schmutzer G., Reiner I., Kocalevent R-D., et al. (2017) Childhood adversities and distress - The role of resilience in a representative sample. <em>PLoS ONE</em>, <em>12</em>(3): e0173826. <a href="https://doi.org/10.1371/journal.pone.0173826" class="uri">https://doi.org/10.1371/journal.pone.0173826</a></p>
<p>Glass G.V., Peckham P.D., Sanders J.R. (1972). Consequences of failure to meet assumptions underlying the fixed effects analyses of variance and covariance. <em>Review of Educational Research</em>. <em>42</em>, 237–288. <a href="https://doi.org/10.3102%2F00346543042003237" class="uri">https://doi.org/10.3102%2F00346543042003237</a></p>
<p>Horstmann A.C., Bock N., Linhuber E., Szczuka J.M., Straßmann C., Kramer N.C. (2018) Do a
robot’s social skills and its objection discourage interactants from switching the robot off? <em>PLoS ONE</em>, <em>13</em>(7): e0201581. <a href="https://doi.org/10.1371/journal.pone.0201581" class="uri">https://doi.org/10.1371/journal.pone.0201581</a></p>
<p>Meidenbauer, K. L., Stenfors, C. U., Bratman, G. N., Gross, J. J., Schertz, K. E., Choe, K. W., &amp; Berman, M. G. (2020). The affective benefits of nature exposure: What's nature got to do with it?. <em>Journal of Environmental Psychology</em>, <em>72</em>, 101498. <a href="https://doi.org/10.1016/j.jenvp.2020.101498" class="uri">https://doi.org/10.1016/j.jenvp.2020.101498</a></p>
<p>Schmider E., Ziegler M., Danay E., Beyer L., Bühner M. (2010). Is it really robust? <em>Methodology</em>. <em>6</em>, 147–151. <a href="https://doi.org/10.1027/1614-2241/a000016" class="uri">https://doi.org/10.1027/1614-2241/a000016</a></p>

</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="multiple1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mutliple2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
