<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Session 8 Mixed Models | PSYC761 Data Analysis</title>
  <meta name="description" content="Course materials for PSYC761 2025" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Session 8 Mixed Models | PSYC761 Data Analysis" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course materials for PSYC761 2025" />
  <meta name="github-repo" content="datafluencyCB" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Session 8 Mixed Models | PSYC761 Data Analysis" />
  
  <meta name="twitter:description" content="Course materials for PSYC761 2025" />
  

<meta name="author" content="Chris Berry" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="prepost.html"/>
<link rel="next" href="assessment2025.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />



<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="include/psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include/webex.css" type="text/css" />
<link rel="stylesheet" href="include/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PSYC761 Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="simple1.html"><a href="simple1.html"><i class="fa fa-check"></i><b>1</b> Simple Regression</a>
<ul>
<li class="chapter" data-level="1.1" data-path="simple1.html"><a href="simple1.html#overview-1"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="simple1.html"><a href="simple1.html#worked-example"><i class="fa fa-check"></i><b>1.2</b> Worked Example</a></li>
<li class="chapter" data-level="1.3" data-path="simple1.html"><a href="simple1.html#predicting"><i class="fa fa-check"></i><b>1.3</b> Predicting</a></li>
<li class="chapter" data-level="1.4" data-path="simple1.html"><a href="simple1.html#residuals"><i class="fa fa-check"></i><b>1.4</b> Residuals</a></li>
<li class="chapter" data-level="1.5" data-path="simple1.html"><a href="simple1.html#evaluating-the-model"><i class="fa fa-check"></i><b>1.5</b> Evaluating the model</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="simple1.html"><a href="simple1.html#r2"><i class="fa fa-check"></i><b>1.5.1</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="1.5.2" data-path="simple1.html"><a href="simple1.html#bayes-factor"><i class="fa fa-check"></i><b>1.5.2</b> Bayes factor</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="simple1.html"><a href="simple1.html#exercise"><i class="fa fa-check"></i><b>1.6</b> Exercise</a></li>
<li class="chapter" data-level="1.7" data-path="simple1.html"><a href="simple1.html#further-exercises"><i class="fa fa-check"></i><b>1.7</b> Further Exercises</a></li>
<li class="chapter" data-level="1.8" data-path="simple1.html"><a href="simple1.html#going-further-p-values"><i class="fa fa-check"></i><b>1.8</b> Going further: <em>p</em>-values</a></li>
<li class="chapter" data-level="1.9" data-path="simple1.html"><a href="simple1.html#summary"><i class="fa fa-check"></i><b>1.9</b> Summary</a></li>
<li class="chapter" data-level="1.10" data-path="simple1.html"><a href="simple1.html#references"><i class="fa fa-check"></i><b>1.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="multiple1.html"><a href="multiple1.html"><i class="fa fa-check"></i><b>2</b> Multiple regression: multiple continuous predictors</a>
<ul>
<li class="chapter" data-level="2.1" data-path="multiple1.html"><a href="multiple1.html#overview-2"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="multiple1.html"><a href="multiple1.html#worked-example-1"><i class="fa fa-check"></i><b>2.2</b> Worked example</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="multiple1.html"><a href="multiple1.html#residual-plot"><i class="fa fa-check"></i><b>2.2.1</b> Residual plot</a></li>
<li class="chapter" data-level="2.2.2" data-path="multiple1.html"><a href="multiple1.html#evaluating-the-model-bayes-factor"><i class="fa fa-check"></i><b>2.2.2</b> Evaluating the model: Bayes factor</a></li>
<li class="chapter" data-level="2.2.3" data-path="multiple1.html"><a href="multiple1.html#evaluating-the-model-r2"><i class="fa fa-check"></i><b>2.2.3</b> Evaluating the model: R<sup>2</sup></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="multiple1.html"><a href="multiple1.html#understanding-the-contribution-of-individual-predictors"><i class="fa fa-check"></i><b>2.3</b> Understanding the contribution of individual predictors</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="multiple1.html"><a href="multiple1.html#r2-in-simple-vs.-multiple-regression"><i class="fa fa-check"></i><b>2.3.1</b> R<sup>2</sup> in simple vs. multiple regression</a></li>
<li class="chapter" data-level="2.3.2" data-path="multiple1.html"><a href="multiple1.html#venn-diagrams"><i class="fa fa-check"></i><b>2.3.2</b> Venn Diagrams</a></li>
<li class="chapter" data-level="2.3.3" data-path="multiple1.html"><a href="multiple1.html#using-bayes-factors-to-assess-the-unique-contribution-of-predictors"><i class="fa fa-check"></i><b>2.3.3</b> Using Bayes factors to assess the unique contribution of predictors</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="multiple1.html"><a href="multiple1.html#multicollinearity"><i class="fa fa-check"></i><b>2.4</b> Multicollinearity</a></li>
<li class="chapter" data-level="2.5" data-path="multiple1.html"><a href="multiple1.html#exercise-1"><i class="fa fa-check"></i><b>2.5</b> Exercise</a></li>
<li class="chapter" data-level="2.6" data-path="multiple1.html"><a href="multiple1.html#further-exercises-1"><i class="fa fa-check"></i><b>2.6</b> Further exercises</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="multiple1.html"><a href="multiple1.html#regressionbf"><i class="fa fa-check"></i><b>2.6.1</b> <code>regressionBF()</code></a></li>
<li class="chapter" data-level="2.6.2" data-path="multiple1.html"><a href="multiple1.html#predicting-new-data"><i class="fa fa-check"></i><b>2.6.2</b> Predicting new data</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="multiple1.html"><a href="multiple1.html#going-further-p-values-1"><i class="fa fa-check"></i><b>2.7</b> Going further: <em>p</em>-values</a></li>
<li class="chapter" data-level="2.8" data-path="multiple1.html"><a href="multiple1.html#summary-of-key-points"><i class="fa fa-check"></i><b>2.8</b> Summary of key points</a></li>
<li class="chapter" data-level="2.9" data-path="multiple1.html"><a href="multiple1.html#references-1"><i class="fa fa-check"></i><b>2.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="anova1.html"><a href="anova1.html"><i class="fa fa-check"></i><b>3</b> ANOVA: between-subjects designs</a>
<ul>
<li class="chapter" data-level="3.1" data-path="anova1.html"><a href="anova1.html#overview-3"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="anova1.html"><a href="anova1.html#one-way-between-subjects-anova"><i class="fa fa-check"></i><b>3.2</b> One-way between subjects ANOVA</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="anova1.html"><a href="anova1.html#worked-example-2"><i class="fa fa-check"></i><b>3.2.1</b> Worked Example</a></li>
<li class="chapter" data-level="3.2.2" data-path="anova1.html"><a href="anova1.html#read-in-the-data"><i class="fa fa-check"></i><b>3.2.2</b> Read in the data</a></li>
<li class="chapter" data-level="3.2.3" data-path="anova1.html"><a href="anova1.html#convert-the-independent-variable-to-a-factor"><i class="fa fa-check"></i><b>3.2.3</b> Convert the independent variable to a factor</a></li>
<li class="chapter" data-level="3.2.4" data-path="anova1.html"><a href="anova1.html#n-of-each-group"><i class="fa fa-check"></i><b>3.2.4</b> n of each group</a></li>
<li class="chapter" data-level="3.2.5" data-path="anova1.html"><a href="anova1.html#visualise-the-data"><i class="fa fa-check"></i><b>3.2.5</b> Visualise the data</a></li>
<li class="chapter" data-level="3.2.6" data-path="anova1.html"><a href="anova1.html#plot-the-means"><i class="fa fa-check"></i><b>3.2.6</b> Plot the means</a></li>
<li class="chapter" data-level="3.2.7" data-path="anova1.html"><a href="anova1.html#descriptives-mean-of-each-group"><i class="fa fa-check"></i><b>3.2.7</b> Descriptives: Mean of each group</a></li>
<li class="chapter" data-level="3.2.8" data-path="anova1.html"><a href="anova1.html#bayes-factor-1"><i class="fa fa-check"></i><b>3.2.8</b> Bayes factor</a></li>
<li class="chapter" data-level="3.2.9" data-path="anova1.html"><a href="anova1.html#r2-1"><i class="fa fa-check"></i><b>3.2.9</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="3.2.10" data-path="anova1.html"><a href="anova1.html#follow-up-tests"><i class="fa fa-check"></i><b>3.2.10</b> Follow-up tests</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="anova1.html"><a href="anova1.html#two-way-between-subjects-anova"><i class="fa fa-check"></i><b>3.3</b> Two-way between-subjects ANOVA</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="anova1.html"><a href="anova1.html#worked-example-3"><i class="fa fa-check"></i><b>3.3.1</b> Worked example</a></li>
<li class="chapter" data-level="3.3.2" data-path="anova1.html"><a href="anova1.html#read-in-the-data-1"><i class="fa fa-check"></i><b>3.3.2</b> Read in the data</a></li>
<li class="chapter" data-level="3.3.3" data-path="anova1.html"><a href="anova1.html#convert-the-independent-variables-to-factors"><i class="fa fa-check"></i><b>3.3.3</b> Convert the independent variables to factors</a></li>
<li class="chapter" data-level="3.3.4" data-path="anova1.html"><a href="anova1.html#n-in-each-group"><i class="fa fa-check"></i><b>3.3.4</b> n in each group</a></li>
<li class="chapter" data-level="3.3.5" data-path="anova1.html"><a href="anova1.html#visualise-the-data-1"><i class="fa fa-check"></i><b>3.3.5</b> Visualise the data</a></li>
<li class="chapter" data-level="3.3.6" data-path="anova1.html"><a href="anova1.html#plot-the-means-1"><i class="fa fa-check"></i><b>3.3.6</b> Plot the means</a></li>
<li class="chapter" data-level="3.3.7" data-path="anova1.html"><a href="anova1.html#bayes-factors"><i class="fa fa-check"></i><b>3.3.7</b> Bayes factors</a></li>
<li class="chapter" data-level="3.3.8" data-path="anova1.html"><a href="anova1.html#r2-2"><i class="fa fa-check"></i><b>3.3.8</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="3.3.9" data-path="anova1.html"><a href="anova1.html#follow-up-comparisons"><i class="fa fa-check"></i><b>3.3.9</b> Follow-up comparisons</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="anova1.html"><a href="anova1.html#exercise-one-way"><i class="fa fa-check"></i><b>3.4</b> Exercise: one-way</a></li>
<li class="chapter" data-level="3.5" data-path="anova1.html"><a href="anova1.html#exercise-two-way"><i class="fa fa-check"></i><b>3.5</b> Exercise: two-way</a></li>
<li class="chapter" data-level="3.6" data-path="anova1.html"><a href="anova1.html#summary-1"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
<li class="chapter" data-level="3.7" data-path="anova1.html"><a href="anova1.html#references-2"><i class="fa fa-check"></i><b>3.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multiple2.html"><a href="multiple2.html"><i class="fa fa-check"></i><b>4</b> Multiple regression: one continuous, one categorical</a>
<ul>
<li class="chapter" data-level="4.1" data-path="multiple2.html"><a href="multiple2.html#overview-4"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="multiple2.html"><a href="multiple2.html#worked-example-4"><i class="fa fa-check"></i><b>4.2</b> Worked example</a></li>
<li class="chapter" data-level="4.3" data-path="multiple2.html"><a href="multiple2.html#read-in-the-data-2"><i class="fa fa-check"></i><b>4.3</b> Read in the data</a></li>
<li class="chapter" data-level="4.4" data-path="multiple2.html"><a href="multiple2.html#visualise-the-data-2"><i class="fa fa-check"></i><b>4.4</b> Visualise the data</a></li>
<li class="chapter" data-level="4.5" data-path="multiple2.html"><a href="multiple2.html#evidence-for-the-interaction"><i class="fa fa-check"></i><b>4.5</b> Evidence for the interaction</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="multiple2.html"><a href="multiple2.html#model-without-the-interaction"><i class="fa fa-check"></i><b>4.5.1</b> Model without the interaction</a></li>
<li class="chapter" data-level="4.5.2" data-path="multiple2.html"><a href="multiple2.html#model-with-the-interaction"><i class="fa fa-check"></i><b>4.5.2</b> Model with the interaction</a></li>
<li class="chapter" data-level="4.5.3" data-path="multiple2.html"><a href="multiple2.html#compare-the-model-with-and-without-the-interaction"><i class="fa fa-check"></i><b>4.5.3</b> Compare the model with and without the interaction</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="multiple2.html"><a href="multiple2.html#simple-slopes-analysis"><i class="fa fa-check"></i><b>4.6</b> Simple slopes analysis</a></li>
<li class="chapter" data-level="4.7" data-path="multiple2.html"><a href="multiple2.html#exercises"><i class="fa fa-check"></i><b>4.7</b> Exercises</a></li>
<li class="chapter" data-level="4.8" data-path="multiple2.html"><a href="multiple2.html#further-exercise"><i class="fa fa-check"></i><b>4.8</b> Further exercise</a></li>
<li class="chapter" data-level="4.9" data-path="multiple2.html"><a href="multiple2.html#further-knowledge"><i class="fa fa-check"></i><b>4.9</b> Further knowledge</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="multiple2.html"><a href="multiple2.html#moderation"><i class="fa fa-check"></i><b>4.9.1</b> Moderation</a></li>
<li class="chapter" data-level="4.9.2" data-path="multiple2.html"><a href="multiple2.html#coefficients"><i class="fa fa-check"></i><b>4.9.2</b> Coefficients</a></li>
<li class="chapter" data-level="4.9.3" data-path="multiple2.html"><a href="multiple2.html#centering"><i class="fa fa-check"></i><b>4.9.3</b> Centering</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="multiple2.html"><a href="multiple2.html#summary-2"><i class="fa fa-check"></i><b>4.10</b> Summary</a></li>
<li class="chapter" data-level="4.11" data-path="multiple2.html"><a href="multiple2.html#references-3"><i class="fa fa-check"></i><b>4.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="multiple3.html"><a href="multiple3.html"><i class="fa fa-check"></i><b>5</b> Multiple regression: hierarchical regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="multiple3.html"><a href="multiple3.html#overview-5"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="multiple3.html"><a href="multiple3.html#worked-example-1-wellbeing"><i class="fa fa-check"></i><b>5.2</b> Worked example 1: wellbeing</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="multiple3.html"><a href="multiple3.html#read-in-the-data-3"><i class="fa fa-check"></i><b>5.2.1</b> Read in the data</a></li>
<li class="chapter" data-level="5.2.2" data-path="multiple3.html"><a href="multiple3.html#visualisation"><i class="fa fa-check"></i><b>5.2.2</b> Visualisation</a></li>
<li class="chapter" data-level="5.2.3" data-path="multiple3.html"><a href="multiple3.html#correlations"><i class="fa fa-check"></i><b>5.2.3</b> Correlations</a></li>
<li class="chapter" data-level="5.2.4" data-path="multiple3.html"><a href="multiple3.html#hierarchical-regression"><i class="fa fa-check"></i><b>5.2.4</b> Hierarchical regression</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="multiple3.html"><a href="multiple3.html#exercise-1-1"><i class="fa fa-check"></i><b>5.3</b> Exercise 1</a></li>
<li class="chapter" data-level="5.4" data-path="multiple3.html"><a href="multiple3.html#worked-exercise-2-controlling-for-categorical-variables"><i class="fa fa-check"></i><b>5.4</b> Worked Exercise 2: Controlling for categorical variables</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="multiple3.html"><a href="multiple3.html#visualisation-1"><i class="fa fa-check"></i><b>5.4.1</b> Visualisation</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="multiple3.html"><a href="multiple3.html#exercise-2"><i class="fa fa-check"></i><b>5.5</b> Exercise 2</a></li>
<li class="chapter" data-level="5.6" data-path="multiple3.html"><a href="multiple3.html#further-knowledge-and-exercises"><i class="fa fa-check"></i><b>5.6</b> Further knowledge and exercises</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="multiple3.html"><a href="multiple3.html#standardised-coefficients"><i class="fa fa-check"></i><b>5.6.1</b> Standardised Coefficients</a></li>
<li class="chapter" data-level="5.6.2" data-path="multiple3.html"><a href="multiple3.html#prediction"><i class="fa fa-check"></i><b>5.6.2</b> Prediction</a></li>
<li class="chapter" data-level="5.6.3" data-path="multiple3.html"><a href="multiple3.html#residuals-1"><i class="fa fa-check"></i><b>5.6.3</b> Residuals</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="multiple3.html"><a href="multiple3.html#summary-3"><i class="fa fa-check"></i><b>5.7</b> Summary</a></li>
<li class="chapter" data-level="5.8" data-path="multiple3.html"><a href="multiple3.html#references-4"><i class="fa fa-check"></i><b>5.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="anova2.html"><a href="anova2.html"><i class="fa fa-check"></i><b>6</b> ANOVA: Repeated measures</a>
<ul>
<li class="chapter" data-level="6.1" data-path="anova2.html"><a href="anova2.html#overview-6"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="anova2.html"><a href="anova2.html#one-way-repeated-measures-anova"><i class="fa fa-check"></i><b>6.2</b> One-way repeated measures ANOVA</a></li>
<li class="chapter" data-level="6.3" data-path="anova2.html"><a href="anova2.html#long-format-data"><i class="fa fa-check"></i><b>6.3</b> Long format data</a></li>
<li class="chapter" data-level="6.4" data-path="anova2.html"><a href="anova2.html#worked-example-5"><i class="fa fa-check"></i><b>6.4</b> Worked Example</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="anova2.html"><a href="anova2.html#read-in-the-data-4"><i class="fa fa-check"></i><b>6.4.1</b> Read in the data</a></li>
<li class="chapter" data-level="6.4.2" data-path="anova2.html"><a href="anova2.html#convert-the-data-to-long-format"><i class="fa fa-check"></i><b>6.4.2</b> Convert the data to long format</a></li>
<li class="chapter" data-level="6.4.3" data-path="anova2.html"><a href="anova2.html#convert-the-participant-and-the-categorical-variable-to-factors"><i class="fa fa-check"></i><b>6.4.3</b> Convert the participant and the categorical variable to factors</a></li>
<li class="chapter" data-level="6.4.4" data-path="anova2.html"><a href="anova2.html#visualise-the-data-3"><i class="fa fa-check"></i><b>6.4.4</b> Visualise the data</a></li>
<li class="chapter" data-level="6.4.5" data-path="anova2.html"><a href="anova2.html#plot-the-means-2"><i class="fa fa-check"></i><b>6.4.5</b> Plot the means</a></li>
<li class="chapter" data-level="6.4.6" data-path="anova2.html"><a href="anova2.html#descriptives-mean-of-each-condition"><i class="fa fa-check"></i><b>6.4.6</b> Descriptives: Mean of each condition</a></li>
<li class="chapter" data-level="6.4.7" data-path="anova2.html"><a href="anova2.html#bayes-factor-2"><i class="fa fa-check"></i><b>6.4.7</b> Bayes factor</a></li>
<li class="chapter" data-level="6.4.8" data-path="anova2.html"><a href="anova2.html#follow-up-tests-1"><i class="fa fa-check"></i><b>6.4.8</b> Follow-up tests</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="anova2.html"><a href="anova2.html#two-way-within-subjects-anova"><i class="fa fa-check"></i><b>6.5</b> Two-way within subjects ANOVA</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="anova2.html"><a href="anova2.html#worked-example-6"><i class="fa fa-check"></i><b>6.5.1</b> Worked Example</a></li>
<li class="chapter" data-level="6.5.2" data-path="anova2.html"><a href="anova2.html#read-in-the-data-5"><i class="fa fa-check"></i><b>6.5.2</b> Read in the data</a></li>
<li class="chapter" data-level="6.5.3" data-path="anova2.html"><a href="anova2.html#visualise-the-data-4"><i class="fa fa-check"></i><b>6.5.3</b> Visualise the data</a></li>
<li class="chapter" data-level="6.5.4" data-path="anova2.html"><a href="anova2.html#plot-the-means-3"><i class="fa fa-check"></i><b>6.5.4</b> Plot the means</a></li>
<li class="chapter" data-level="6.5.5" data-path="anova2.html"><a href="anova2.html#descriptive-statistics---mean"><i class="fa fa-check"></i><b>6.5.5</b> Descriptive statistics - mean</a></li>
<li class="chapter" data-level="6.5.6" data-path="anova2.html"><a href="anova2.html#convert-participant-and-categorical-variables-to-factors"><i class="fa fa-check"></i><b>6.5.6</b> Convert participant and categorical variables to factors</a></li>
<li class="chapter" data-level="6.5.7" data-path="anova2.html"><a href="anova2.html#bayes-factor-3"><i class="fa fa-check"></i><b>6.5.7</b> Bayes factor</a></li>
<li class="chapter" data-level="6.5.8" data-path="anova2.html"><a href="anova2.html#follow-up-comparisons-1"><i class="fa fa-check"></i><b>6.5.8</b> Follow up comparisons</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="anova2.html"><a href="anova2.html#exercise-two-way-mixed-anova"><i class="fa fa-check"></i><b>6.6</b> Exercise: two-way mixed ANOVA</a></li>
<li class="chapter" data-level="6.7" data-path="anova2.html"><a href="anova2.html#further-knowledge---within-subject-errorbars"><i class="fa fa-check"></i><b>6.7</b> Further knowledge - within-subject errorbars</a></li>
<li class="chapter" data-level="6.8" data-path="anova2.html"><a href="anova2.html#further-knowledge---r-squared"><i class="fa fa-check"></i><b>6.8</b> Further knowledge - R-squared</a></li>
<li class="chapter" data-level="6.9" data-path="anova2.html"><a href="anova2.html#summary-4"><i class="fa fa-check"></i><b>6.9</b> Summary</a></li>
<li class="chapter" data-level="6.10" data-path="anova2.html"><a href="anova2.html#references-5"><i class="fa fa-check"></i><b>6.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="prepost.html"><a href="prepost.html"><i class="fa fa-check"></i><b>7</b> Pre-post data, clinically significant change</a>
<ul>
<li class="chapter" data-level="7.1" data-path="prepost.html"><a href="prepost.html#overview-7"><i class="fa fa-check"></i><b>7.1</b> Overview</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="prepost.html"><a href="prepost.html#worked-example-7"><i class="fa fa-check"></i><b>7.1.1</b> Worked example</a></li>
<li class="chapter" data-level="7.1.2" data-path="prepost.html"><a href="prepost.html#read-in-the-data-6"><i class="fa fa-check"></i><b>7.1.2</b> Read in the data</a></li>
<li class="chapter" data-level="7.1.3" data-path="prepost.html"><a href="prepost.html#plot-the-means-4"><i class="fa fa-check"></i><b>7.1.3</b> Plot the means</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="prepost.html"><a href="prepost.html#approach-1---difference-scores"><i class="fa fa-check"></i><b>7.2</b> Approach 1 - Difference scores</a></li>
<li class="chapter" data-level="7.3" data-path="prepost.html"><a href="prepost.html#approach-2---mixed-anova"><i class="fa fa-check"></i><b>7.3</b> Approach 2 - Mixed ANOVA</a></li>
<li class="chapter" data-level="7.4" data-path="prepost.html"><a href="prepost.html#approach-3---ancova"><i class="fa fa-check"></i><b>7.4</b> Approach 3 - ANCOVA</a></li>
<li class="chapter" data-level="7.5" data-path="prepost.html"><a href="prepost.html#which-approach-should-you-use"><i class="fa fa-check"></i><b>7.5</b> Which approach should you use?</a></li>
<li class="chapter" data-level="7.6" data-path="prepost.html"><a href="prepost.html#clinical-significance"><i class="fa fa-check"></i><b>7.6</b> Clinical Significance</a></li>
<li class="chapter" data-level="7.7" data-path="prepost.html"><a href="prepost.html#exercises-1"><i class="fa fa-check"></i><b>7.7</b> Exercises</a></li>
<li class="chapter" data-level="7.8" data-path="prepost.html"><a href="prepost.html#further-knowledge-1"><i class="fa fa-check"></i><b>7.8</b> Further Knowledge</a></li>
<li class="chapter" data-level="7.9" data-path="prepost.html"><a href="prepost.html#summary-5"><i class="fa fa-check"></i><b>7.9</b> Summary</a></li>
<li class="chapter" data-level="7.10" data-path="prepost.html"><a href="prepost.html#references-6"><i class="fa fa-check"></i><b>7.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="mixed.html"><a href="mixed.html"><i class="fa fa-check"></i><b>8</b> Mixed Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="mixed.html"><a href="mixed.html#overview-8"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="mixed.html"><a href="mixed.html#types-of-mixed-model"><i class="fa fa-check"></i><b>8.2</b> Types of mixed model</a></li>
<li class="chapter" data-level="8.3" data-path="mixed.html"><a href="mixed.html#lme4"><i class="fa fa-check"></i><b>8.3</b> <code>lme4</code></a></li>
<li class="chapter" data-level="8.4" data-path="mixed.html"><a href="mixed.html#fixed-and-random-effects"><i class="fa fa-check"></i><b>8.4</b> Fixed and Random effects</a></li>
<li class="chapter" data-level="8.5" data-path="mixed.html"><a href="mixed.html#specifying-the-model"><i class="fa fa-check"></i><b>8.5</b> Specifying the model</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="mixed.html"><a href="mixed.html#fixed-effect-model-with-random-intercepts"><i class="fa fa-check"></i><b>8.5.1</b> Fixed effect model with random intercepts</a></li>
<li class="chapter" data-level="8.5.2" data-path="mixed.html"><a href="mixed.html#fixed-effect-model-with-random-intercepts-and-slopes"><i class="fa fa-check"></i><b>8.5.2</b> Fixed effect model with random intercepts AND slopes</a></li>
<li class="chapter" data-level="8.5.3" data-path="mixed.html"><a href="mixed.html#multiple-fixed-effects-random-intercepts-and-slopes"><i class="fa fa-check"></i><b>8.5.3</b> Multiple fixed effects, random intercepts AND slopes</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="mixed.html"><a href="mixed.html#the-analysis-do-rts-differ-across-modality-conditions"><i class="fa fa-check"></i><b>8.6</b> The analysis: Do RTs differ across modality conditions?</a></li>
<li class="chapter" data-level="8.7" data-path="mixed.html"><a href="mixed.html#inspecting-the-model"><i class="fa fa-check"></i><b>8.7</b> Inspecting the model</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="mixed.html"><a href="mixed.html#convergence-issues"><i class="fa fa-check"></i><b>8.7.1</b> Convergence issues</a></li>
<li class="chapter" data-level="8.7.2" data-path="mixed.html"><a href="mixed.html#coefficients-1"><i class="fa fa-check"></i><b>8.7.2</b> Coefficients</a></li>
<li class="chapter" data-level="8.7.3" data-path="mixed.html"><a href="mixed.html#graph"><i class="fa fa-check"></i><b>8.7.3</b> Graph</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="mixed.html"><a href="mixed.html#going-further-multiple-factors"><i class="fa fa-check"></i><b>8.8</b> Going further: Multiple factors</a></li>
<li class="chapter" data-level="8.9" data-path="mixed.html"><a href="mixed.html#summary-6"><i class="fa fa-check"></i><b>8.9</b> Summary</a></li>
<li class="chapter" data-level="8.10" data-path="mixed.html"><a href="mixed.html#references-7"><i class="fa fa-check"></i><b>8.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="assessment2025.html"><a href="assessment2025.html"><i class="fa fa-check"></i><b>9</b> Data Analysis Assessment 2025</a></li>
<li class="chapter" data-level="10" data-path="faqs.html"><a href="faqs.html"><i class="fa fa-check"></i><b>10</b> FAQs</a>
<ul>
<li class="chapter" data-level="10.1" data-path="faqs.html"><a href="faqs.html#e-meaning"><i class="fa fa-check"></i><b>10.1</b> What does it mean if RStudio prints out "e-" next to a number?</a></li>
<li class="chapter" data-level="10.2" data-path="faqs.html"><a href="faqs.html#how-can-i-find-out-more-about-a-particular-function-so-i-can-explore-its-settings-etc."><i class="fa fa-check"></i><b>10.2</b> How can I find out more about a particular function, so I can explore its settings etc.?</a></li>
<li class="chapter" data-level="10.3" data-path="faqs.html"><a href="faqs.html#how-do-i-import-a-data-file-to-r-studio"><i class="fa fa-check"></i><b>10.3</b> How do I import a data file to R Studio?</a></li>
<li class="chapter" data-level="10.4" data-path="faqs.html"><a href="faqs.html#how-should-i-write-up-the-report"><i class="fa fa-check"></i><b>10.4</b> How should I write up the report?</a></li>
<li class="chapter" data-level="10.5" data-path="faqs.html"><a href="faqs.html#after-downloading-my-.rmd-file-to-my-computer-how-do-i-open-it-again-in-rstudio"><i class="fa fa-check"></i><b>10.5</b> After downloading my .Rmd file to my computer, how do I open it again in RStudio?</a></li>
<li class="chapter" data-level="10.6" data-path="faqs.html"><a href="faqs.html#on-the-word-count-are-figure-captions-included"><i class="fa fa-check"></i><b>10.6</b> On the word count, are figure captions included?</a></li>
<li class="chapter" data-level="10.7" data-path="faqs.html"><a href="faqs.html#should-i-make-code-visible-in-my-html-report"><i class="fa fa-check"></i><b>10.7</b> Should I make code visible in my html report?</a></li>
<li class="chapter" data-level="10.8" data-path="faqs.html"><a href="faqs.html#do-i-need-to-include-references"><i class="fa fa-check"></i><b>10.8</b> Do I need to include references?</a></li>
<li class="chapter" data-level="10.9" data-path="faqs.html"><a href="faqs.html#can-there-be-overlap-in-the-variables-used-in-each-question"><i class="fa fa-check"></i><b>10.9</b> Can there be overlap in the variables used in each question?</a></li>
<li class="chapter" data-level="10.10" data-path="faqs.html"><a href="faqs.html#do-we-have-to-include-a-certain-number-of-variables-to-achieve-a-good-grade"><i class="fa fa-check"></i><b>10.10</b> Do we have to include a certain number of variables to achieve a good grade?</a></li>
<li class="chapter" data-level="10.11" data-path="faqs.html"><a href="faqs.html#can-i-include-more-than-one-figure"><i class="fa fa-check"></i><b>10.11</b> Can I include more than one figure?</a></li>
<li class="chapter" data-level="10.12" data-path="faqs.html"><a href="faqs.html#can-i-include-categorical-predictor-variables-in-a-hierarchical-regression"><i class="fa fa-check"></i><b>10.12</b> Can I include categorical predictor variables in a hierarchical regression?</a></li>
<li class="chapter" data-level="10.13" data-path="faqs.html"><a href="faqs.html#how-do-i-apply-for-extenuating-circumstances"><i class="fa fa-check"></i><b>10.13</b> How do I apply for extenuating circumstances?</a></li>
<li class="chapter" data-level="10.14" data-path="faqs.html"><a href="faqs.html#can-a-book-a-slot-in-your-office-hours"><i class="fa fa-check"></i><b>10.14</b> Can a book a slot in your office hours?</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>11</b> Reading</a>
<ul>
<li class="chapter" data-level="11.1" data-path="reading.html"><a href="reading.html#recommended-texts-and-resources"><i class="fa fa-check"></i><b>11.1</b> Recommended texts and resources</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="reading.html"><a href="reading.html#library-books"><i class="fa fa-check"></i><b>11.1.1</b> Library books</a></li>
<li class="chapter" data-level="11.1.2" data-path="reading.html"><a href="reading.html#electronic-resources-and-books"><i class="fa fa-check"></i><b>11.1.2</b> Electronic resources and books</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="reading.html"><a href="reading.html#data-preprocessing"><i class="fa fa-check"></i><b>11.2</b> Data preprocessing</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSYC761 Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="mixed" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Session 8</span> Mixed Models<a href="mixed.html#mixed" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><em>Chris Berry</em><br />
<em>2025</em></p>
<!--
commented text
commented text
-->
<style>
div.exercise { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<style>
div.tip { background-color:#D5F5E3; border-radius: 5px; padding: 20px;}
</style>
<div id="overview-8" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Overview<a href="mixed.html#overview-8" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><strong>Slides</strong> from the lecture part of the session: <a href="slides/PSYC761_L8_MixedModels.pptx">Download</a></li>
<li><strong>R Studio online</strong> <a href="https://psyrstudio.plymouth.ac.uk/">Access here using University log-in</a></li>
</ul>
<p><br />
</p>
<p>The use of mixed models is becoming more and more popular in the analysis of psychological experiments. This session is introductory, and for more detailed overviews, students should consult the Reference list.</p>
<p><br />
</p>
<div class="tip">
<p><strong>Mixed effects models</strong> or <strong>mixed models</strong> are an extension of multiple regression that allow the <em>dependencies</em> among groups of data points to be explicitly accounted for via additional random effects parameters. Dependency can arise because responses come from the same participant, stimulus set, or cluster (e.g., classroom or hospital).</p>
<p>This can also be useful in experiments where researchers measure responses across a set of <strong>items</strong>. Rather than deriving a single score across all items or trials (e.g., an accuracy measure, or a mean), all the responses can be entered into the analysis and the variance associated with the responses to each item across participants explicitly modelled.</p>
<p>This technique can also circumvent the need to discard participants or trials with missing responses from the analysis (provided data are missing at random).</p>
</div>
<p><br />
</p>
</div>
<div id="types-of-mixed-model" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Types of mixed model<a href="mixed.html#types-of-mixed-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When the outcome variable is <strong>continuous</strong> (e.g., response time) the model is called a <strong>Linear Mixed Model (LMM)</strong>.</p>
<p>If the outcome is <strong>binary</strong> (e.g., correct vs. incorrect), the model is called a <strong>Generalised Linear Mixed Model (GLMM)</strong> and a different approach must be used to the one in this worksheet. (See the References for more detail.)</p>
<p><br />
</p>
</div>
<div id="lme4" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> <code>lme4</code><a href="mixed.html#lme4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Mixed models can be run using the <code>lme4</code> package (Bates et al., 2015).</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="mixed.html#cb251-1" tabindex="-1"></a><span class="co"># load lme4</span></span>
<span id="cb251-2"><a href="mixed.html#cb251-2" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code></pre></div>
<p>We will use data from <a href="https://journals.sagepub.com/doi/10.1177/2515245920960351">Brown (2021)</a>:</p>
<ul>
<li>The data are from a response time (RT) experiment in which 53 participants were presented with a word on each trial.</li>
<li>Each word was presented either auditorily (audio-only condition), or both auditorily and visually (they saw each word spoken in a video clip) (audiovisual condition). There were 543 words in total.</li>
<li>The participant's task was to listen to and repeat back each word while simultaneously performing a response time task.</li>
<li>Each participant was presented with words in both conditions.</li>
</ul>
<p><br />
</p>
<p>The data is publicly avaialble via the Open Science Framework at <a href="https://osf.io/download/53wc4/" class="uri">https://osf.io/download/53wc4/</a>.</p>
<p><br />
</p>
<p>Load the data and store it in <code>rt_data</code>.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="mixed.html#cb252-1" tabindex="-1"></a><span class="co"># load data from Brown (2021), located on OSF</span></span>
<span id="cb252-2"><a href="mixed.html#cb252-2" tabindex="-1"></a>rt_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://osf.io/download/53wc4/&quot;</span>)</span></code></pre></div>
<p><br />
</p>
<p>Take a look at the first six rows of the data:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="mixed.html#cb253-1" tabindex="-1"></a><span class="co"># preview the data using head()</span></span>
<span id="cb253-2"><a href="mixed.html#cb253-2" tabindex="-1"></a>rt_data <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">PID</th>
<th align="right">RT</th>
<th align="left">modality</th>
<th align="left">stim</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">301</td>
<td align="right">1024</td>
<td align="left">Audio-only</td>
<td align="left">gown</td>
</tr>
<tr class="even">
<td align="right">301</td>
<td align="right">838</td>
<td align="left">Audio-only</td>
<td align="left">might</td>
</tr>
<tr class="odd">
<td align="right">301</td>
<td align="right">1060</td>
<td align="left">Audio-only</td>
<td align="left">fern</td>
</tr>
<tr class="even">
<td align="right">301</td>
<td align="right">882</td>
<td align="left">Audio-only</td>
<td align="left">vane</td>
</tr>
<tr class="odd">
<td align="right">301</td>
<td align="right">971</td>
<td align="left">Audio-only</td>
<td align="left">pup</td>
</tr>
<tr class="even">
<td align="right">301</td>
<td align="right">1064</td>
<td align="left">Audio-only</td>
<td align="left">rise</td>
</tr>
</tbody>
</table>
</div>
<p>About the data in each column:</p>
<ul>
<li><code>PID</code> contains the unique identifier for each participant.</li>
<li><code>RT</code> contains the response time for each trial.</li>
<li><code>modality</code> contains the label for each condition (<code>Audio-only</code> or <code>Audiovisual</code>)</li>
<li><code>stim</code> contains the word that was presented on each trial</li>
</ul>
<p><br />
</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-39" class="exercise"><strong>Exercise 8.1  </strong></span><strong>Design Check</strong></p>
<ul>
<li><p>What is the name of the dependent variable? <select class='webex-select'><option value='blank'></option><option value=''>PID</option><option value='answer'>RT</option><option value=''>modality</option><option value=''>stim</option></select></p></li>
<li><p>Is <code>modality</code> of presentation manipulated within- or between-subjects? <select class='webex-select'><option value='blank'></option><option value=''>between</option><option value='answer'>within</option></select></p></li>
<li><p>How many levels does <code>modality</code> have? <select class='webex-select'><option value='blank'></option><option value=''>1</option><option value='answer'>2</option><option value=''>4</option></select></p></li>
<li><p>How many participants were there? <select class='webex-select'><option value='blank'></option><option value=''>21,679</option><option value='answer'>53</option><option value=''>543</option><option value=''>4</option></select></p></li>
<li><p>How many unique stimuli (words) were there? <select class='webex-select'><option value='blank'></option><option value=''>21,679</option><option value=''>53</option><option value='answer'>543</option><option value=''>4</option></select></p></li>
<li><p>What format is the data in <code>rt_data</code> in? <select class='webex-select'><option value='blank'></option><option value=''>wide format</option><option value='answer'>long format</option></select></p></li>
</ul>
<div class="webex-solution">
<button>
Hint: count()
</button>
<p>A simple way to obtain the number of participants in long format data is as follows:</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="mixed.html#cb254-1" tabindex="-1"></a><span class="co"># n ppts</span></span>
<span id="cb254-2"><a href="mixed.html#cb254-2" tabindex="-1"></a><span class="co"># take rt_data, group_by ppt, then look at number of rows in tibble</span></span>
<span id="cb254-3"><a href="mixed.html#cb254-3" tabindex="-1"></a>rt_data <span class="sc">%&gt;%</span> </span>
<span id="cb254-4"><a href="mixed.html#cb254-4" tabindex="-1"></a>  <span class="fu">group_by</span>(PID) <span class="sc">%&gt;%</span> </span>
<span id="cb254-5"><a href="mixed.html#cb254-5" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div>
<p><br />
</p>
<p>Likewise, for the number of items:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="mixed.html#cb255-1" tabindex="-1"></a><span class="co"># n items</span></span>
<span id="cb255-2"><a href="mixed.html#cb255-2" tabindex="-1"></a><span class="co"># take rt_data, group_by item, then look at number of rows in tibble</span></span>
<span id="cb255-3"><a href="mixed.html#cb255-3" tabindex="-1"></a>rt_data <span class="sc">%&gt;%</span> </span>
<span id="cb255-4"><a href="mixed.html#cb255-4" tabindex="-1"></a>  <span class="fu">group_by</span>(stim) <span class="sc">%&gt;%</span> </span>
<span id="cb255-5"><a href="mixed.html#cb255-5" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div>
</div>
</div>
<p><br />
</p>
</div>
<div id="fixed-and-random-effects" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Fixed and Random effects<a href="mixed.html#fixed-and-random-effects" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="tip">
<p>Mixed models comprise fixed and random effects.</p>
<p><strong>Fixed effect</strong>: A population-level effect, assumed to persist across experiments with different participants or items. They are used to model average trends. Typically the independent variable is the fixed effect, for example, levels of difficulty in an experiment, manipulated by an experimenter.</p>
<p><strong>Random effect</strong>: Represents the extent to which the fixed effect randomly varies across a grouping variable (e.g., participants, or items). For example, the behaviour of individual participants or items may differ from the average trend (some may do better than others). The random effects are always <em>categorical variables</em>. They should have at least 5 or 6 levels.</p>
</div>
<p><br />
</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-40" class="exercise"><strong>Exercise 8.2  </strong></span>For the Brown (2021) dataset:</p>
<ul>
<li><p>What would be the fixed effect? <select class='webex-select'><option value='blank'></option><option value=''>PID</option><option value=''>RT</option><option value='answer'>modality</option><option value=''>stim</option></select></p></li>
<li><p>What would be one random effect? <select class='webex-select'><option value='blank'></option><option value='answer'>PID</option><option value=''>RT</option><option value=''>modality</option><option value='answer'>stim</option></select></p></li>
<li><p>What would be a second random effect? <select class='webex-select'><option value='blank'></option><option value='answer'>PID</option><option value=''>RT</option><option value=''>modality</option><option value='answer'>stim</option></select></p></li>
</ul>
</div>
<p><br />
</p>
<p>In this design, we are justified in including both <code>participants</code> and <code>items</code> as random effects because you can think of modality as having been manipulated both within-subjects <strong>and</strong> within-items:</p>
<ul>
<li><p><strong>Within-subjects</strong>: The participants provided responses in <em>both</em> conditions.</p></li>
<li><p><strong>Within-items</strong>: Each item was also presented in <em>both</em> conditions. That is, for some participants a word was presented in the <code>Audio-only</code> condition and for other participants it appeared in the <code>Audiovisual</code> condition.</p></li>
</ul>
<p>In other words, we have scores for each participant in each condition, and also scores for each item in each condition. If the items in each condition were different, it wouldn't make sense to include item as a random effect.</p>
<p><br />
</p>
</div>
<div id="specifying-the-model" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Specifying the model<a href="mixed.html#specifying-the-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="tip">
<p>A mixed model approach allows for the variability across items and participants to be modelled via <strong>random intercepts</strong> and <strong>random slopes</strong>. For each, you can have by-participant and by-item effects.</p>
<ul>
<li><strong>Random intercepts</strong>:
<ul>
<li>by-participant: accounts for individual differences in participants' RTs.</li>
<li>by-item: accounts for differences in RTs to particular words.</li>
</ul></li>
<li><strong>Random slopes</strong>:
<ul>
<li>by-participant: accounts for individual differences in the effect of modality on RT.</li>
<li>by-item: accounts for differences in the effect of modality on particular words.</li>
</ul></li>
</ul>
<p>Note that if random slopes and intercepts are included, correlations between them will also be estimated. A correlation could occur, for example, if slower participants show larger effects of modality.</p>
</div>
<p><br />
</p>
<p>Models with different combinations of random effects can be specified and compared to test whether there's evidence for particular components or not.</p>
<p><br />
</p>
<div id="fixed-effect-model-with-random-intercepts" class="section level3 hasAnchor" number="8.5.1">
<h3><span class="header-section-number">8.5.1</span> Fixed effect model with random intercepts<a href="mixed.html#fixed-effect-model-with-random-intercepts" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The simplest random effects model has random intercepts only.</p>
<p><br />
</p>
<p>The general formula is:</p>
<p><code>lmer(outcome ~ predictor + (1|participant) + (1|item), data = data)</code></p>
<p><br />
</p>
<p>Note that fixed effects are specified <strong>outside</strong> parentheses:</p>
<ul>
<li><code>predictor</code> means include the fixed effect of predictor</li>
</ul>
<p><br />
</p>
<p>Random effects are specified <strong>inside</strong> parentheses:
Things to the left of <code>|</code> vary according to things on the right.</p>
<ul>
<li><code>(1|participant)</code> means the intercept (represented with '1') varies according to <code>participant.</code></li>
<li><code>(1|item)</code> means the intercept (1) varies according to <code>item.</code></li>
</ul>
<p><br />
</p>
<p>So, in words, the formula means "model the <code>outcome</code> variable as a function of the fixed effect of the <code>predictor</code>, with random intercepts for <code>participant</code> and <code>item</code>."</p>
<p><br />
</p>
</div>
<div id="fixed-effect-model-with-random-intercepts-and-slopes" class="section level3 hasAnchor" number="8.5.2">
<h3><span class="header-section-number">8.5.2</span> Fixed effect model with random intercepts AND slopes<a href="mixed.html#fixed-effect-model-with-random-intercepts-and-slopes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The effect of modality can be allowed to differ across participants and items by including <strong>random slopes</strong>.</p>
<p><br />
</p>
<p>The general formula is:</p>
<p><code>lmer(outcome ~ predictor + (1 + predictor|participant) + (1 + predictor|item), data = data)</code></p>
<p><br />
</p>
<p>Where:</p>
<ul>
<li><code>(1 + predictor|participant)</code> means the intercept (<code>1</code>) <em>and</em> fixed effect (<code>predictor</code>) varies according to <code>participant</code>.</li>
<li><code>(1 + predictor|item)</code> means the intercept (<code>1</code>) and fixed effect (<code>predictor</code>) varies according to <code>item</code>.</li>
</ul>
<p><br />
</p>
</div>
<div id="multiple-fixed-effects-random-intercepts-and-slopes" class="section level3 hasAnchor" number="8.5.3">
<h3><span class="header-section-number">8.5.3</span> Multiple fixed effects, random intercepts AND slopes<a href="mixed.html#multiple-fixed-effects-random-intercepts-and-slopes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For multiple fixed effects, e.g., <code>predictor1</code> and <code>predictor2</code>, an example of the formula used could be:</p>
<p><code>lmer(outcome ~ predictor1 + predictor2 + (1 + predictor1 + predictor2|participant) + (1 + predictor1|item), data = data)</code></p>
<p><br />
</p>
<p>Where:</p>
<ul>
<li><code>predictor1</code> means include the fixed effect of <code>predictor1</code>.</li>
<li><code>predictor2</code> means include the fixed effect of <code>predictor2</code>.</li>
<li><code>(1 + predictor1 + predictor2|participant)</code> means include random intercepts (1) for <code>participant</code> and also by-participant random slopes for <code>predictor1</code> and <code>predictor2</code>.</li>
<li><code>(1 + predictor1|item)</code> means include random intercepts for <code>item</code> and by-item random slopes for <code>predictor1</code>.</li>
</ul>
<p><br />
</p>
</div>
</div>
<div id="the-analysis-do-rts-differ-across-modality-conditions" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> The analysis: Do RTs differ across modality conditions?<a href="mixed.html#the-analysis-do-rts-differ-across-modality-conditions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The researchers wanted to know whether RTs differ according to the <code>modality</code> condition.</p>
<p>As covered in the lecture, the first step is to specify the maximal (full) model permitted by the design. Here, it's one that includes random intercepts and slopes for participant and stimulus.</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="mixed.html#cb256-1" tabindex="-1"></a><span class="co"># Specify the full model and store in rt_full_model</span></span>
<span id="cb256-2"><a href="mixed.html#cb256-2" tabindex="-1"></a>rt_full_model <span class="ot">&lt;-</span> </span>
<span id="cb256-3"><a href="mixed.html#cb256-3" tabindex="-1"></a>  <span class="fu">lmer</span>(RT <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> modality <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> modality<span class="sc">|</span>PID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> modality<span class="sc">|</span>stim), <span class="at">data =</span> rt_data)</span></code></pre></div>
<p>This "maximal" model for the data includes:</p>
<ul>
<li>The <strong>fixed effect</strong> of <code>modality</code></li>
<li>By-participant and by-item <strong>random intercepts</strong></li>
<li>By-participant and by-item <strong>random slopes</strong></li>
</ul>
<p><br />
</p>
<p>For comparison, we need to specify the <em>reduced</em> model, which is identical except it does not contain the fixed effect.</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="mixed.html#cb257-1" tabindex="-1"></a><span class="co"># Specify the reduced model and store in rt_reduced_model</span></span>
<span id="cb257-2"><a href="mixed.html#cb257-2" tabindex="-1"></a>rt_reduced_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> modality<span class="sc">|</span>PID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> modality<span class="sc">|</span>stim), <span class="at">data =</span> rt_data)</span></code></pre></div>
<p>To compare the full and reduced models use <code>anova(model_1, model_2)</code>, that is,</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="mixed.html#cb258-1" tabindex="-1"></a><span class="co"># compare the reduced and full models</span></span>
<span id="cb258-2"><a href="mixed.html#cb258-2" tabindex="-1"></a><span class="fu">anova</span>(rt_reduced_model, rt_full_model)</span></code></pre></div>
<p><img src="images/8_anova_lmm.png" /></p>
<ul>
<li>This tests a null hypothesis that the full and reduced models are statistically equivalent.</li>
<li>Specifically, a <strong>likelihood ratio test</strong> is performed, which involves obtaining the likelihood of each model and then comparing the likelihoods.</li>
<li>The <em>p</em>-value is the probability of obtaining a test statistic at least as extreme as the one observed, if the null hypothesis is true.</li>
<li>If the <em>p</em>-value for the test is less than 0.05, then, by convention, we say the test is statistically significant.</li>
<li>The <em>p</em>-value is shown in the <code>Pr(&gt;ChiSq)</code> column and is a very small number (e.g., 1.26e-08), being clearly less than 0.05.</li>
<li>This means that the full model fits the data significantly better than the reduced model, and we have evidence for the fixed effect.</li>
</ul>
<p><br />
</p>
</div>
<div id="inspecting-the-model" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> Inspecting the model<a href="mixed.html#inspecting-the-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now we know that we have evidence for the full model containing the fixed effect, we can look at it in detail:</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="mixed.html#cb259-1" tabindex="-1"></a><span class="co"># display results from the full model</span></span>
<span id="cb259-2"><a href="mixed.html#cb259-2" tabindex="-1"></a><span class="fu">summary</span>(rt_full_model)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: RT ~ 1 + modality + (1 + modality | PID) + (1 + modality | stim)
##    Data: rt_data
## 
## REML criterion at convergence: 302385.7
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.3646 -0.6964 -0.0141  0.5886  5.0003 
## 
## Random effects:
##  Groups   Name                Variance Std.Dev. Corr 
##  stim     (Intercept)           304.0   17.44        
##           modalityAudiovisual   216.9   14.73   0.16 
##  PID      (Intercept)         28559.0  168.99        
##           modalityAudiovisual  7709.0   87.80   -0.17
##  Residual                     65258.8  255.46        
## Number of obs: 21679, groups:  stim, 543; PID, 53
## 
## Fixed effects:
##                     Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)          1044.14      23.36   52.12  44.700  &lt; 2e-16 ***
## modalityAudiovisual    83.18      12.57   52.10   6.615 2.02e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr)
## modltyAdvsl -0.178</code></pre>
<p>In the output:</p>
<ul>
<li>REML stands for <strong>Restricted Maximum Likelihood</strong>. This is the method that was used to fit the model to the data.</li>
<li>The formula entered for the mixed model is given again.</li>
<li>Information about the variance in the residuals is given.</li>
</ul>
<p><strong>Random effects:</strong></p>
<ul>
<li>The values in <code>Std. Dev</code> are the estimates of the variance in the random intercepts and slopes in participants (<code>PID</code>) and items (<code>stim</code>).</li>
<li>The values in <code>Corr</code> are the estimates of the correlation between the random intercept and random slopes (by-participant and by-item).
<ul>
<li>The correlation of 0.16 means that the effect was larger for items that took longer to respond to.</li>
<li>The correlation of -0.17 means that the effect of modality was smaller in participants who took longer to respond.</li>
</ul></li>
</ul>
<p>To interpret the fixed effects, we need to consider how the levels of modality were coded.</p>
<ul>
<li>R uses dummy coding (0s and 1s) to code the levels of a factor (or a character variable).</li>
<li>modality has levels <code>Audio-only</code> and <code>Audiovisual</code></li>
<li>R assigns the 0s and 1s in dummy coding alphabetically.</li>
<li><code>Audio-only</code> is therefore coded with 0s.</li>
<li><code>Audiovisual</code> is therefore coded with 1s.</li>
</ul>
<p><strong>Fixed effects:</strong></p>
<ul>
<li>The estimate of the intercept is given as 1044.14. This represents the average RT in the <code>Audio-only</code> group (the condition coded with zeros).</li>
<li>The estimate of the fixed effect of modality is given as <strong>83.18</strong>. This represents how much greater the mean is in the <code>Audiovisual</code> condition (coded with 1s), <em>once participant and items have been taken into account</em>.</li>
</ul>
<p>The researchers in this experiment thought RTs would be slower in Audio-visual condition than the audio-only condition. Seeing a word in addition to hearing it may be associated with greater cognitive effort.</p>
<p>Are the researchers correct or not? <select class='webex-select'><option value='blank'></option><option value=''>No</option><option value='answer'>Yes</option></select></p>
<div class="webex-solution">
<button>
Explain
</button>
<p>Because the fixed effect of modality is 83.18, and because <code>Audio-visual</code> was (dummy) coded with 1s and <code>Audio-only</code> was coded with 0s, this means that the mean of the <code>Audiovisual</code> condition is 83.18 <em>greater</em> than that of the <code>Audiovisual</code> condition. The outcome variable is RT, which means that <strong>responses in the Audiovisual condition were 83 ms slower, on average, as expected by the researchers.</strong></p>
</div>
<p><br />
</p>
<div id="convergence-issues" class="section level3 hasAnchor" number="8.7.1">
<h3><span class="header-section-number">8.7.1</span> Convergence issues<a href="mixed.html#convergence-issues" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="tip">
<p>It is common when running LMMs for the model to not <strong>converge</strong> successfully, meaning that R was unable to estimate all the parameters of the model.</p>
<p>This is especially common with more complex models, such as those with multiple fixed and random effects and their interactions.</p>
<p>If you receive a warning saying that the model did not converge, or that the fit is singular, you should not report the results from the model.</p>
<p>One solution is to explore all the fitting options in <code>lmer()</code> that do allow for convergence.</p>
<p>Handily, this can be done for you automatically using the <code>allFit()</code> function in the <code>afex</code> package:</p>
</div>
<p><br />
</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="mixed.html#cb261-1" tabindex="-1"></a><span class="fu">allFit</span>(rt_full_model)</span></code></pre></div>
<pre><code>## bobyqa : [OK]
## Nelder_Mead : [OK]
## nlminbwrap : [OK]
## optimx.L-BFGS-B : [OK]
## nloptwrap.NLOPT_LN_NELDERMEAD : [OK]
## nloptwrap.NLOPT_LN_BOBYQA : [OK]
## original model:
## RT ~ 1 + modality + (1 + modality | PID) + (1 + modality | stim) 
## data:  rt_data 
## optimizers (6): bobyqa, Nelder_Mead, nlminbwrap, optimx.L-BFGS-B,nloptwrap.NLOPT_LN_NELDERME...
## differences in negative log-likelihoods:
## max= 0.00015 ; std dev= 6.08e-05</code></pre>
<p>This will provide a list of the optimisers (e.g., <code>bobyqa</code>, <code>Nelder_Mead</code>) in <code>lmer()</code> that produce convergence warnings or singular fits or do successfully converge <code>[OK]</code>.</p>
<p><br />
</p>
<p>An optimiser from this list can then be manually specified using <code>lmerControl</code> when running the model:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="mixed.html#cb263-1" tabindex="-1"></a>rt_full_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> modality <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> modality<span class="sc">|</span>PID) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> modality<span class="sc">|</span>stim), </span>
<span id="cb263-2"><a href="mixed.html#cb263-2" tabindex="-1"></a>                      <span class="at">data =</span> rt_data,</span>
<span id="cb263-3"><a href="mixed.html#cb263-3" tabindex="-1"></a>                      <span class="at">control =</span> <span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</span></code></pre></div>
<p>Other things that may improve convergence are:</p>
<ul>
<li>increase the number of iterations the optimisation routine performs (with <code>control = lmerControl(optCtr = list(maxfun = 1e9))</code>)</li>
<li>remove the derivative calculations that occur after the model has reached a solution (via. <code>control = lmerControl(calc.derivs = FALSE)</code> )</li>
</ul>
<p><br />
</p>
<p>If the model still does not converge, then the complexity of the model should be systematically reduced. For example, remove a component such as a random slope term and re-run it, repeating the process of removing more and more components until it converges.</p>
<p>Ideally, the random effects you include in the model should be psychologically principled and guided by theory.</p>
<p><br />
</p>
</div>
<div id="coefficients-1" class="section level3 hasAnchor" number="8.7.2">
<h3><span class="header-section-number">8.7.2</span> Coefficients<a href="mixed.html#coefficients-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For learning purposes only, let's see for ourselves that each participant in the final model has their own estimate of the intercept and slope, using <code>coef()</code></p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="mixed.html#cb264-1" tabindex="-1"></a><span class="co"># get the random intercept and slope for each participant</span></span>
<span id="cb264-2"><a href="mixed.html#cb264-2" tabindex="-1"></a><span class="fu">coef</span>(rt_full_model)<span class="sc">$</span>PID <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">(Intercept)</th>
<th align="right">modalityAudiovisual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">301</td>
<td align="right">1024.0672</td>
<td align="right">-16.936244</td>
</tr>
<tr class="even">
<td align="left">302</td>
<td align="right">1044.1377</td>
<td align="right">1.843072</td>
</tr>
<tr class="odd">
<td align="left">303</td>
<td align="right">882.8292</td>
<td align="right">57.790549</td>
</tr>
<tr class="even">
<td align="left">304</td>
<td align="right">1232.7548</td>
<td align="right">-27.919783</td>
</tr>
<tr class="odd">
<td align="left">306</td>
<td align="right">1042.3427</td>
<td align="right">33.886178</td>
</tr>
<tr class="even">
<td align="left">307</td>
<td align="right">1111.3621</td>
<td align="right">-9.938361</td>
</tr>
</tbody>
</table>
</div>
<p><br />
</p>
<p>See also the random intercepts and slopes for each item:</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="mixed.html#cb265-1" tabindex="-1"></a><span class="co"># get random intercept and slope for each stimulus</span></span>
<span id="cb265-2"><a href="mixed.html#cb265-2" tabindex="-1"></a><span class="fu">coef</span>(rt_full_model)<span class="sc">$</span>stim <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">(Intercept)</th>
<th align="right">modalityAudiovisual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">babe</td>
<td align="right">1038.919</td>
<td align="right">82.11841</td>
</tr>
<tr class="even">
<td align="left">back</td>
<td align="right">1050.914</td>
<td align="right">86.52439</td>
</tr>
<tr class="odd">
<td align="left">bad</td>
<td align="right">1041.122</td>
<td align="right">81.12280</td>
</tr>
<tr class="even">
<td align="left">bag</td>
<td align="right">1042.892</td>
<td align="right">86.41081</td>
</tr>
<tr class="odd">
<td align="left">bake</td>
<td align="right">1039.394</td>
<td align="right">81.75528</td>
</tr>
<tr class="even">
<td align="left">balk</td>
<td align="right">1042.558</td>
<td align="right">84.17974</td>
</tr>
</tbody>
</table>
</div>
<p>You wouldn't report these, but looking at them helps to make it concrete that each participant and stimulus has its own intercept and effect of modality (slope) in this model.</p>
<p><br />
</p>
</div>
<div id="graph" class="section level3 hasAnchor" number="8.7.3">
<h3><span class="header-section-number">8.7.3</span> Graph<a href="mixed.html#graph" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>emmeans()</code> package can be used to obtain the means from the model for a figure.</p>
<div class="tip">
<p><strong>EMM</strong> stands for Estimated Marginal Means. These are means for conditions or contrasts, estimated by the model that was fit to the data.</p>
</div>
<p><br />
</p>
<p>Obtain the estimates of mean RT in the two modality conditions:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="mixed.html#cb266-1" tabindex="-1"></a><span class="co"># load emmeans package</span></span>
<span id="cb266-2"><a href="mixed.html#cb266-2" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb266-3"><a href="mixed.html#cb266-3" tabindex="-1"></a></span>
<span id="cb266-4"><a href="mixed.html#cb266-4" tabindex="-1"></a><span class="co"># obtain the emms from the model, for each level of modality</span></span>
<span id="cb266-5"><a href="mixed.html#cb266-5" tabindex="-1"></a>emms <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(rt_full_model, <span class="sc">~</span> modality)</span></code></pre></div>
<p>If you get a warning that tells us that it can't calculate the degrees of freedom, then don't worry since we don't need these right now.</p>
<p><br />
</p>
<p>To see the EMMs:</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="mixed.html#cb267-1" tabindex="-1"></a>emms</span></code></pre></div>
<pre><code>##  modality    emmean   SE  df asymp.LCL asymp.UCL
##  Audio-only    1044 23.4 Inf       998      1090
##  Audiovisual   1127 24.5 Inf      1079      1175
## 
## Degrees-of-freedom method: asymptotic 
## Confidence level used: 0.95</code></pre>
<ul>
<li>The EMMs are in the <code>emmean</code> column.</li>
<li>Associated standard errors are in <code>SE</code>.</li>
<li>The values in the <code>asymp.LCL</code> column are the lower 95% confidence interval limits of the means.</li>
<li>The values in the <code>asymp.UCL</code> column are the upper 95% confidence interval limits of the means.</li>
</ul>
<p><br />
</p>
<ul>
<li>The estimated mean of the <code>Audio-only</code> condition is <select class='webex-select'><option value='blank'></option><option value='answer'>1044</option><option value=''>23.4</option><option value=''>1127</option></select></li>
<li>The estimated mean of the <code>Audiovisual</code> condition is <select class='webex-select'><option value='blank'></option><option value=''>1079</option><option value='answer'>1127</option><option value=''>23.4</option><option value=''>1044</option></select></li>
</ul>
<p><br />
</p>
<p>To create a figure showing these means in <code>ggplot()</code>:</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="mixed.html#cb269-1" tabindex="-1"></a><span class="co"># use emms, convert to tibble for ggplot, </span></span>
<span id="cb269-2"><a href="mixed.html#cb269-2" tabindex="-1"></a><span class="co"># plot means and errorbars</span></span>
<span id="cb269-3"><a href="mixed.html#cb269-3" tabindex="-1"></a></span>
<span id="cb269-4"><a href="mixed.html#cb269-4" tabindex="-1"></a><span class="fu">as_tibble</span>(emms) <span class="sc">%&gt;%</span> </span>
<span id="cb269-5"><a href="mixed.html#cb269-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> modality, <span class="at">y =</span> emmean)) <span class="sc">+</span></span>
<span id="cb269-6"><a href="mixed.html#cb269-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">group =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb269-7"><a href="mixed.html#cb269-7" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> asymp.LCL, <span class="at">ymax =</span> asymp.UCL, <span class="at">width =</span> <span class="fl">0.2</span>)) <span class="sc">+</span></span>
<span id="cb269-8"><a href="mixed.html#cb269-8" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Estimated marginal mean RT&quot;</span>) <span class="sc">+</span></span>
<span id="cb269-9"><a href="mixed.html#cb269-9" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Condition&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-17"></span>
<img src="08_mixed_models_files/figure-html/unnamed-chunk-17-1.png" alt="Estimated marginal mean RT in each modality condition, controlling for participant and stimulus. Error bars denote the 95% confidence interval." width="75%" />
<p class="caption">
Figure 5.2: Estimated marginal mean RT in each modality condition, controlling for participant and stimulus. Error bars denote the 95% confidence interval.
</p>
</div>
<p><br />
</p>
<p>These means in the figure are technically based on estimates of parameters from the model. That is, they are the mean of the levels of the fixed effect after accounting for the random effects, and so won't necessarily be the same as the means you may calculate directly from the data.</p>
<p><br />
</p>
<div class="webex-solution">
<button>
Traditional analysis
</button>
<p>For learning purposes only, let's compare what the means would have been when calculated in the traditional way (without accounting for the random effects).</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="mixed.html#cb270-1" tabindex="-1"></a><span class="co"># average RTs across participants in each condition</span></span>
<span id="cb270-2"><a href="mixed.html#cb270-2" tabindex="-1"></a><span class="co"># then work out the mean across participants</span></span>
<span id="cb270-3"><a href="mixed.html#cb270-3" tabindex="-1"></a>rt_data <span class="sc">%&gt;%</span> </span>
<span id="cb270-4"><a href="mixed.html#cb270-4" tabindex="-1"></a>  <span class="fu">group_by</span>(PID, modality) <span class="sc">%&gt;%</span> </span>
<span id="cb270-5"><a href="mixed.html#cb270-5" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">M =</span> <span class="fu">mean</span>(RT)) <span class="sc">%&gt;%</span> </span>
<span id="cb270-6"><a href="mixed.html#cb270-6" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb270-7"><a href="mixed.html#cb270-7" tabindex="-1"></a>  <span class="fu">group_by</span>(modality) <span class="sc">%&gt;%</span> </span>
<span id="cb270-8"><a href="mixed.html#cb270-8" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">M_RT =</span> <span class="fu">mean</span>(M))</span></code></pre></div>
<p>In this case, the means come out the same.</p>
<p><br />
</p>
<p>Now see if the modality effect would be significant in a traditional paired <em>t</em>-test. Again, this is for learning purposes only - most LMMs would be more complex than only having a fixed factor with two levels!</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="mixed.html#cb271-1" tabindex="-1"></a>Ms <span class="ot">&lt;-</span> </span>
<span id="cb271-2"><a href="mixed.html#cb271-2" tabindex="-1"></a>  rt_data <span class="sc">%&gt;%</span> </span>
<span id="cb271-3"><a href="mixed.html#cb271-3" tabindex="-1"></a>    <span class="fu">group_by</span>(PID, modality) <span class="sc">%&gt;%</span> </span>
<span id="cb271-4"><a href="mixed.html#cb271-4" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">M =</span> <span class="fu">mean</span>(RT)) <span class="sc">%&gt;%</span> </span>
<span id="cb271-5"><a href="mixed.html#cb271-5" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from=</span>modality,<span class="at">values_from=</span>M)</span>
<span id="cb271-6"><a href="mixed.html#cb271-6" tabindex="-1"></a></span>
<span id="cb271-7"><a href="mixed.html#cb271-7" tabindex="-1"></a><span class="fu">t.test</span>(Ms<span class="sc">$</span><span class="st">`</span><span class="at">Audio-only</span><span class="st">`</span>, Ms<span class="sc">$</span>Audiovisual, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>The pattern of significance is the same in the t-test and LMM (there's a significant effect of condition).</p>
</div>
<p><br />
</p>
</div>
</div>
<div id="going-further-multiple-factors" class="section level2 hasAnchor" number="8.8">
<h2><span class="header-section-number">8.8</span> Going further: Multiple factors<a href="mixed.html#going-further-multiple-factors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="tip">
<p>The analysis above was for a very simple scenario where the fixed factor had two levels. It can be extended to include an additional fixed factor and interaction between the factors.</p>
</div>
<p><br />
</p>
<p>Load the extended data from Brown (2021) at "<a href="https://osf.io/download/vkfzn/" class="uri">https://osf.io/download/vkfzn/</a>" and store in <code>rt_data_interaction</code>.</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="mixed.html#cb272-1" tabindex="-1"></a><span class="co"># load data with additional fixed factor</span></span>
<span id="cb272-2"><a href="mixed.html#cb272-2" tabindex="-1"></a>rt_data_interaction <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://osf.io/download/vkfzn/&quot;</span>) </span></code></pre></div>
<pre><code>## Rows: 21679 Columns: 5
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (3): SNR, modality, stim
## dbl (2): PID, RT
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="exercise">
<p><span id="exr:unlabeled-div-41" class="exercise"><strong>Exercise 8.3  </strong></span></p>
<ul>
<li>The name of the column containing the new fixed factor is <select class='webex-select'><option value='blank'></option><option value=''>modality</option><option value=''>stim</option><option value='answer'>SNR</option><option value=''>PID</option><option value=''>RT</option></select></li>
<li>The levels of the new factor are <select class='webex-select'><option value='blank'></option><option value='answer'>Easy/Hard</option><option value=''>Audio-only/Audiovisual</option></select></li>
</ul>
</div>
<p><br />
</p>
<p>SNR stands for <em>Signal to Noise Ratio</em>. This manipulation involved changing the background noise to affect how difficult it was to hear the word on each trial.</p>
<ul>
<li>In the <code>Easy</code> condition, it was easy to hear the word against background noise.</li>
<li>In the <code>Hard</code> condition, it was difficult to hear the word against the background noise.</li>
</ul>
</div>
<p><br />
</p>
<p>To specify the full model with the interaction between the two fixed factors:</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="mixed.html#cb274-1" tabindex="-1"></a><span class="co"># Specify the LMM with an interaction term</span></span>
<span id="cb274-2"><a href="mixed.html#cb274-2" tabindex="-1"></a>rt_int.mod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> modality <span class="sc">+</span> SNR <span class="sc">+</span> modality<span class="sc">*</span>SNR <span class="sc">+</span></span>
<span id="cb274-3"><a href="mixed.html#cb274-3" tabindex="-1"></a>                     (<span class="dv">1</span> <span class="sc">+</span> modality <span class="sc">+</span> SNR<span class="sc">|</span>stim) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> modality <span class="sc">+</span> SNR<span class="sc">|</span>PID), </span>
<span id="cb274-4"><a href="mixed.html#cb274-4" tabindex="-1"></a>                   <span class="at">data =</span> rt_data_interaction)</span></code></pre></div>
<pre><code>## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
<ul>
<li>Notice that the interaction was specified by adding <code>modality:SNR</code>.</li>
<li>We could have alternatively used <code>modality*SNR</code> to add the interaction.</li>
<li>Notice that the model includes random intercepts and slopes for each factor (by participant and by-item).</li>
<li>Random effects for the interaction term have <em>not</em> been included. Doing so often leads to an oversaturated model and/or convergence issues. The researcher didn't include them.</li>
</ul>
<p>The model failed to converge and is singular.</p>
<p><br />
</p>
<p>Use <code>allFit()</code> from the <code>afex</code> package to see if another optimizer will work.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="mixed.html#cb276-1" tabindex="-1"></a><span class="co"># This code will take a while to run</span></span>
<span id="cb276-2"><a href="mixed.html#cb276-2" tabindex="-1"></a><span class="co"># as allFit() tries each different optimizer!</span></span>
<span id="cb276-3"><a href="mixed.html#cb276-3" tabindex="-1"></a><span class="fu">allFit</span>(rt_int.mod)</span></code></pre></div>
<p><br />
</p>
<p>To help convergence, Brown (2021) removed components of the model relating to the random effects of items. Specifically:</p>
<ul>
<li>The by-item random slopes associated with each fixed factor were removed. The component <code>(1 + modality + SNR| stim)</code> becomes <code>(1|stim)</code>.</li>
<li>The correlation between the random intercept for <code>stim</code> and the by-stimulus random slope for <code>modality</code> was also removed using <code>+ (0 + modality|stim)</code>. They weren't interested in that correlation.</li>
<li>The <code>allFit()</code> function indicated that the bobyqa optimizer led to convergence.</li>
</ul>
<p>Thus, their final model is:</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="mixed.html#cb277-1" tabindex="-1"></a>rt_int.mod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> modality <span class="sc">+</span> SNR <span class="sc">+</span> modality<span class="sc">:</span>SNR <span class="sc">+</span></span>
<span id="cb277-2"><a href="mixed.html#cb277-2" tabindex="-1"></a>                     (<span class="dv">0</span> <span class="sc">+</span> modality<span class="sc">|</span>stim) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>stim) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> modality <span class="sc">+</span> SNR<span class="sc">|</span>PID), </span>
<span id="cb277-3"><a href="mixed.html#cb277-3" tabindex="-1"></a>                   <span class="at">data =</span> rt_data_interaction,</span>
<span id="cb277-4"><a href="mixed.html#cb277-4" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">&#39;bobyqa&#39;</span>))</span></code></pre></div>
<pre><code>## boundary (singular) fit: see help(&#39;isSingular&#39;)</code></pre>
<p>This model still doesn't converge here for us though!</p>
<p><br />
</p>
<p>To help convergence, we'll try removing the <code>+ (0 + modality|stim)</code> term:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="mixed.html#cb279-1" tabindex="-1"></a>rt_int.mod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> modality <span class="sc">+</span> SNR <span class="sc">+</span> modality<span class="sc">:</span>SNR <span class="sc">+</span></span>
<span id="cb279-2"><a href="mixed.html#cb279-2" tabindex="-1"></a>                      (<span class="dv">1</span><span class="sc">|</span>stim) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> modality <span class="sc">+</span> SNR<span class="sc">|</span>PID), </span>
<span id="cb279-3"><a href="mixed.html#cb279-3" tabindex="-1"></a>                   <span class="at">data =</span> rt_data_interaction,</span>
<span id="cb279-4"><a href="mixed.html#cb279-4" tabindex="-1"></a>                   <span class="at">control =</span> <span class="fu">lmerControl</span>(<span class="at">optimizer =</span> <span class="st">&#39;bobyqa&#39;</span>))</span></code></pre></div>
<p>This model now contains random intercepts (by-item and by-participant), and also by-participant random slopes for the effects of modality and SNR.</p>
<p>The model converges!</p>
<p><br />
</p>
<p>Now we can look at the model results using <code>summary()</code>:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="mixed.html#cb280-1" tabindex="-1"></a><span class="fu">summary</span>(rt_int.mod)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: RT ~ 1 + modality + SNR + modality:SNR + (1 | stim) + (1 + modality +  
##     SNR | PID)
##    Data: rt_data_interaction
## Control: lmerControl(optimizer = &quot;bobyqa&quot;)
## 
## REML criterion at convergence: 301138.6
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -3.5317 -0.6951 -0.0044  0.5970  4.8640 
## 
## Random effects:
##  Groups   Name                Variance Std.Dev. Corr       
##  stim     (Intercept)           395     19.88              
##  PID      (Intercept)         25527    159.77              
##           modalityAudiovisual  8046     89.70   -0.03      
##           SNRHard             10357    101.77    0.02 -0.47
##  Residual                     61269    247.53              
## Number of obs: 21679, groups:  stim, 543; PID, 53
## 
## Fixed effects:
##                              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)                   998.829     22.218    52.745  44.957  &lt; 2e-16 ***
## modalityAudiovisual            98.510     13.190    58.894   7.469 4.39e-10 ***
## SNRHard                        92.346     14.792    58.015   6.243 5.39e-08 ***
## modalityAudiovisual:SNRHard   -29.556      6.756 21346.939  -4.374 1.22e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) mdltyA SNRHrd
## modltyAdvsl -0.063              
## SNRHard     -0.015 -0.354       
## mdltyA:SNRH  0.074 -0.247 -0.233</code></pre>
<ul>
<li>Significance tests on the main effects and interaction are conducted using <strong>Satterthwaite's method</strong>, which is a way of estimating degrees of freedom to enable a hypothesis test to be conducted.</li>
<li>There are significant main effects of modality, <em>t</em>(58.89) = 44.96, <em>p</em> &lt; .001, and SNR, <em>t</em>(58.01) = 6.24, <em>p</em> &lt; .001, and there's also a significant interaction between the factors, <em>t</em>(21346.94) = -4.37, <em>p</em> &lt; .001.</li>
</ul>
<p>It is possible to interpret the main effects and interaction by looking at the values of the coefficients (see Brown, 2021, p.14). An alternative way, however, is to obtain and then plot the EMMs of each condition:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="mixed.html#cb282-1" tabindex="-1"></a><span class="co"># obtain the EMMs for each condition</span></span>
<span id="cb282-2"><a href="mixed.html#cb282-2" tabindex="-1"></a>emms_interaction <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(rt_int.mod, <span class="sc">~</span>modality<span class="sc">*</span>SNR)</span>
<span id="cb282-3"><a href="mixed.html#cb282-3" tabindex="-1"></a></span>
<span id="cb282-4"><a href="mixed.html#cb282-4" tabindex="-1"></a><span class="co"># look at the emms</span></span>
<span id="cb282-5"><a href="mixed.html#cb282-5" tabindex="-1"></a>emms_interaction</span></code></pre></div>
<pre><code>##  modality    SNR  emmean   SE  df asymp.LCL asymp.UCL
##  Audio-only  Easy    999 22.2 Inf       955      1042
##  Audiovisual Easy   1097 25.1 Inf      1048      1147
##  Audio-only  Hard   1091 26.5 Inf      1039      1143
##  Audiovisual Hard   1160 26.1 Inf      1109      1211
## 
## Degrees-of-freedom method: asymptotic 
## Confidence level used: 0.95</code></pre>
<p><br />
</p>
<p>Now plot the means using <code>ggplot()</code>:</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="mixed.html#cb284-1" tabindex="-1"></a><span class="co"># use ggplot to plot the emms as points, with line connectors, and errorbars</span></span>
<span id="cb284-2"><a href="mixed.html#cb284-2" tabindex="-1"></a><span class="fu">as_tibble</span>(emms_interaction) <span class="sc">%&gt;%</span> </span>
<span id="cb284-3"><a href="mixed.html#cb284-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> modality, <span class="at">y =</span> emmean, <span class="at">color =</span> SNR)) <span class="sc">+</span></span>
<span id="cb284-4"><a href="mixed.html#cb284-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb284-5"><a href="mixed.html#cb284-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> SNR)) <span class="sc">+</span></span>
<span id="cb284-6"><a href="mixed.html#cb284-6" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> asymp.LCL, <span class="at">ymax =</span> asymp.UCL, <span class="at">width =</span> <span class="fl">0.1</span>)) <span class="sc">+</span></span>
<span id="cb284-7"><a href="mixed.html#cb284-7" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Estimated marginal mean RT&quot;</span>) <span class="sc">+</span></span>
<span id="cb284-8"><a href="mixed.html#cb284-8" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;SNR condition&quot;</span>) <span class="sc">+</span></span>
<span id="cb284-9"><a href="mixed.html#cb284-9" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">1300</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-27"></span>
<img src="08_mixed_models_files/figure-html/unnamed-chunk-27-1.png" alt="Estimated marginal mean RT in each condition, controlling for participant and stimulus. Error bars denote the 95% confidence interval." width="75%" />
<p class="caption">
Figure 8.1: Estimated marginal mean RT in each condition, controlling for participant and stimulus. Error bars denote the 95% confidence interval.
</p>
</div>
<ul>
<li>This figure reveals the nature of the significant interaction. The effect of modality is greater in the <code>Easy</code> vs. <code>Hard</code> SNR condition (98 ms vs. 69 ms, calculated from the EMMs in <code>emms_interaction</code>).</li>
</ul>
<p><br />
</p>
</div>
<div id="summary-6" class="section level2 hasAnchor" number="8.9">
<h2><span class="header-section-number">8.9</span> Summary<a href="mixed.html#summary-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>Mixed models provide a way of estimating <strong>fixed effects</strong>, while accounting for <strong>random effects</strong> of participants and items.</p></li>
<li><p>They are becoming increasingly common in the psychological literature.</p></li>
<li><p>Models can be more complex by having fixed effects with more than two levels, multiple fixed effects, and additional random effects.</p></li>
<li><p>Random effects structures often need to be simplified to allow the model to be fit successfully.</p></li>
<li><p>See <strong>Brown (2021)</strong> for an example with a binary response variable (e.g., accuracy = correct vs. incorrect); this analysis is called a generalised linear mixed model (GLMM). Jaeger (2008) also provides a tutorial.</p></li>
<li><p>For more guidance on reporting mixed models, see Meteyard and Davies (2020).</p></li>
</ul>
<p><br />
</p>
<p>Interested students should consult the articles below.</p>
<p><br />
</p>
</div>
<div id="references-7" class="section level2 hasAnchor" number="8.10">
<h2><span class="header-section-number">8.10</span> References<a href="mixed.html#references-7" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Recommended introductory texts:</strong></p>
<p>Brown, V. A. (2021). An introduction to linear mixed-effects modeling in R. <em>Advances in Methods and Practices in Psychological Science</em>, <em>4</em>(1), Article 2515245920960351. <a href="https://doi.org/10.1177/2515245920960351" class="uri">https://doi.org/10.1177/2515245920960351</a></p>
<p>Singmann, H., &amp; Kellen, D.(2019). An Introduction to Mixed Models for Experimental Psychology. In D.H. Spieler &amp; E. Schumacher(Eds.), <em>New Methods in Cognitive Psychology</em> (pp.4–31).Psychology Press. <a href="http://singmann.org/download/publications/singmann_kellen-introduction-mixed-models.pdf">[PDF link]</a></p>
<p><br />
</p>
<p><strong>Going further:</strong></p>
<p>Bates, D., Mächler, M., Bolker, B., &amp; Walker, S. (2015). Fitting Linear Mixed-Effects Models Using lme4. <em>Journal of Statistical Software</em>, <em>67</em>, 1-48. <a href="https://www.jstatsoft.org/index.php/jss/article/view/v067i01/946">[PDF link]</a></p>
<p>Bolker, B. M. (2015). Linear and generalized linear mixed models. <em>Ecological statistics: contemporary theory and application</em>, 309-333. <a href="https://ms.mcmaster.ca/~bolker/R/misc/foxchapter/14-Fox-Chap13.pdf">[PDF link]</a></p>
<p>Bono, R., Alarcón R., &amp; Blanca M.J. (2021). Report quality of generalized linear mixed models in psychology: a systematic review. <em>Frontiers in Psychology</em>. 12:666182 <a href="https://doi.org/10.3389/fpsyg.2021.666182">[Article]</a></p>
<p>Meteyard, L., &amp; Davies, R. A. (2020). Best practice guidance for linear mixed-effects models in psychological science. <em>Journal of Memory and Language</em>, <em>112</em>, 104092. <a href="https://doi.org/10.1016/j.jml.2020.104092">[Article]</a></p>
<p>Jaeger, T. F. (2008). Categorical data analysis: Away from ANOVAs (transformation or not) and towards logit mixed models. <em>Journal of Memory and Language</em>, <em>59</em>(4), 434–446. <a href="https://doi.org/10.1016/j.jml.2007.11.007">[Article]</a></p>

</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="prepost.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="assessment2025.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
