<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Session 2 Multiple regression: multiple continuous predictors | PSYC753 Data Fluency: Analysis</title>
  <meta name="description" content="Course materials for PSYC753 2022" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Session 2 Multiple regression: multiple continuous predictors | PSYC753 Data Fluency: Analysis" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://chrisjberry.github.io/datafluencyCB/" />
  
  <meta property="og:description" content="Course materials for PSYC753 2022" />
  <meta name="github-repo" content="datafluencyCB" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Session 2 Multiple regression: multiple continuous predictors | PSYC753 Data Fluency: Analysis" />
  
  <meta name="twitter:description" content="Course materials for PSYC753 2022" />
  

<meta name="author" content="Chris Berry" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="simple1.html"/>
<link rel="next" href="anova1.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />



<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="include/psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include/webex.css" type="text/css" />
<link rel="stylesheet" href="include/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PSYC753 Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="simple1.html"><a href="simple1.html"><i class="fa fa-check"></i><b>1</b> Simple Regression</a>
<ul>
<li class="chapter" data-level="1.1" data-path="simple1.html"><a href="simple1.html#overview-1"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="simple1.html"><a href="simple1.html#worked-example"><i class="fa fa-check"></i><b>1.2</b> Worked Example</a></li>
<li class="chapter" data-level="1.3" data-path="simple1.html"><a href="simple1.html#predicting"><i class="fa fa-check"></i><b>1.3</b> Predicting</a></li>
<li class="chapter" data-level="1.4" data-path="simple1.html"><a href="simple1.html#residuals"><i class="fa fa-check"></i><b>1.4</b> Residuals</a></li>
<li class="chapter" data-level="1.5" data-path="simple1.html"><a href="simple1.html#evaluating-the-model"><i class="fa fa-check"></i><b>1.5</b> Evaluating the model</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="simple1.html"><a href="simple1.html#r2"><i class="fa fa-check"></i><b>1.5.1</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="1.5.2" data-path="simple1.html"><a href="simple1.html#bayes-factor"><i class="fa fa-check"></i><b>1.5.2</b> Bayes Factor</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="simple1.html"><a href="simple1.html#exercise"><i class="fa fa-check"></i><b>1.6</b> Exercise</a></li>
<li class="chapter" data-level="1.7" data-path="simple1.html"><a href="simple1.html#further-exercises"><i class="fa fa-check"></i><b>1.7</b> Further Exercises</a></li>
<li class="chapter" data-level="1.8" data-path="simple1.html"><a href="simple1.html#summary"><i class="fa fa-check"></i><b>1.8</b> Summary</a></li>
<li class="chapter" data-level="1.9" data-path="simple1.html"><a href="simple1.html#references"><i class="fa fa-check"></i><b>1.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="multiple1.html"><a href="multiple1.html"><i class="fa fa-check"></i><b>2</b> Multiple regression: multiple continuous predictors</a>
<ul>
<li class="chapter" data-level="2.1" data-path="multiple1.html"><a href="multiple1.html#overview-2"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="multiple1.html"><a href="multiple1.html#worked-example-1"><i class="fa fa-check"></i><b>2.2</b> Worked example</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="multiple1.html"><a href="multiple1.html#residual-plot"><i class="fa fa-check"></i><b>2.2.1</b> Residual plot</a></li>
<li class="chapter" data-level="2.2.2" data-path="multiple1.html"><a href="multiple1.html#evaluating-the-model-bayes-factor"><i class="fa fa-check"></i><b>2.2.2</b> Evaluating the model: Bayes Factor</a></li>
<li class="chapter" data-level="2.2.3" data-path="multiple1.html"><a href="multiple1.html#evaluating-the-model-r2"><i class="fa fa-check"></i><b>2.2.3</b> Evaluating the model: R<sup>2</sup></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="multiple1.html"><a href="multiple1.html#understanding-the-contribution-of-individual-predictors"><i class="fa fa-check"></i><b>2.3</b> Understanding the contribution of individual predictors</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="multiple1.html"><a href="multiple1.html#r2-in-simple-vs.-multiple-regression"><i class="fa fa-check"></i><b>2.3.1</b> R<sup>2</sup> in simple vs. multiple regression</a></li>
<li class="chapter" data-level="2.3.2" data-path="multiple1.html"><a href="multiple1.html#venn-diagrams"><i class="fa fa-check"></i><b>2.3.2</b> Venn Diagrams</a></li>
<li class="chapter" data-level="2.3.3" data-path="multiple1.html"><a href="multiple1.html#using-bayes-factors-to-assess-the-unique-contribution-of-predictors"><i class="fa fa-check"></i><b>2.3.3</b> Using Bayes factors to assess the unique contribution of predictors</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="multiple1.html"><a href="multiple1.html#multicollinearity"><i class="fa fa-check"></i><b>2.4</b> Multicollinearity</a></li>
<li class="chapter" data-level="2.5" data-path="multiple1.html"><a href="multiple1.html#exercise-1"><i class="fa fa-check"></i><b>2.5</b> Exercise</a></li>
<li class="chapter" data-level="2.6" data-path="multiple1.html"><a href="multiple1.html#further-exercises-1"><i class="fa fa-check"></i><b>2.6</b> Further exercises</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="multiple1.html"><a href="multiple1.html#regressionbf"><i class="fa fa-check"></i><b>2.6.1</b> <code>regressionBF()</code></a></li>
<li class="chapter" data-level="2.6.2" data-path="multiple1.html"><a href="multiple1.html#predicting-new-data"><i class="fa fa-check"></i><b>2.6.2</b> Predicting new data</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="multiple1.html"><a href="multiple1.html#summary-of-key-points"><i class="fa fa-check"></i><b>2.7</b> Summary of key points</a></li>
<li class="chapter" data-level="2.8" data-path="multiple1.html"><a href="multiple1.html#references-1"><i class="fa fa-check"></i><b>2.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="anova1.html"><a href="anova1.html"><i class="fa fa-check"></i><b>3</b> ANOVA: between-subjects designs</a>
<ul>
<li class="chapter" data-level="3.1" data-path="anova1.html"><a href="anova1.html#overview-3"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="anova1.html"><a href="anova1.html#one-way-between-subjects-anova"><i class="fa fa-check"></i><b>3.2</b> One-way between subjects ANOVA</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="anova1.html"><a href="anova1.html#worked-example-2"><i class="fa fa-check"></i><b>3.2.1</b> Worked Example</a></li>
<li class="chapter" data-level="3.2.2" data-path="anova1.html"><a href="anova1.html#r2-1"><i class="fa fa-check"></i><b>3.2.2</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="3.2.3" data-path="anova1.html"><a href="anova1.html#pairwise-comparisons"><i class="fa fa-check"></i><b>3.2.3</b> Pairwise Comparisons</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="anova1.html"><a href="anova1.html#two-way-between-subjects-anova"><i class="fa fa-check"></i><b>3.3</b> Two-way between-subjects ANOVA</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="anova1.html"><a href="anova1.html#worked-example-3"><i class="fa fa-check"></i><b>3.3.1</b> Worked example</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="anova1.html"><a href="anova1.html#exercises"><i class="fa fa-check"></i><b>3.4</b> Exercises</a></li>
<li class="chapter" data-level="3.5" data-path="anova1.html"><a href="anova1.html#further-exercise"><i class="fa fa-check"></i><b>3.5</b> Further Exercise</a></li>
<li class="chapter" data-level="3.6" data-path="anova1.html"><a href="anova1.html#references-2"><i class="fa fa-check"></i><b>3.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="mutliple2.html"><a href="mutliple2.html"><i class="fa fa-check"></i><b>4</b> Multiple regression: one continuous, one categorical</a></li>
<li class="chapter" data-level="5" data-path="multiple3.html"><a href="multiple3.html"><i class="fa fa-check"></i><b>5</b> Multiple regression: evaluating and comparing models</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="multiple3.html"><a href="multiple3.html#using-anova-and-bayes-factors-to-compare-models"><i class="fa fa-check"></i><b>5.0.1</b> Using ANOVA and Bayes Factors to compare models</a></li>
<li class="chapter" data-level="5.0.2" data-path="multiple3.html"><a href="multiple3.html#overview-4"><i class="fa fa-check"></i><b>5.0.2</b> Overview</a></li>
<li class="chapter" data-level="5.1" data-path="multiple3.html"><a href="multiple3.html#comparing-models-using-anova"><i class="fa fa-check"></i><b>5.1</b> Comparing models using ANOVA</a></li>
<li class="chapter" data-level="5.2" data-path="multiple3.html"><a href="multiple3.html#comparing-models-using-bayes-factors"><i class="fa fa-check"></i><b>5.2</b> Comparing models using Bayes Factors</a></li>
<li class="chapter" data-level="5.3" data-path="multiple3.html"><a href="multiple3.html#exercise-2"><i class="fa fa-check"></i><b>5.3</b> Exercise</a></li>
<li class="chapter" data-level="5.4" data-path="multiple3.html"><a href="multiple3.html#summary-of-key-points-1"><i class="fa fa-check"></i><b>5.4</b> Summary of key points</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="anova2.html"><a href="anova2.html"><i class="fa fa-check"></i><b>6</b> ANOVA: Repeated measures</a></li>
<li class="chapter" data-level="7" data-path="prepost.html"><a href="prepost.html"><i class="fa fa-check"></i><b>7</b> Pre-post data, effect sizes, clinically significant change</a></li>
<li class="chapter" data-level="8" data-path="assessment2022.html"><a href="assessment2022.html"><i class="fa fa-check"></i><b>8</b> Data Analysis Assessment 2022</a></li>
<li class="chapter" data-level="9" data-path="faqs.html"><a href="faqs.html"><i class="fa fa-check"></i><b>9</b> FAQs</a>
<ul>
<li class="chapter" data-level="9.1" data-path="faqs.html"><a href="faqs.html#e-meaning"><i class="fa fa-check"></i><b>9.1</b> What does it mean if RStudio prints out "e-" next to a number?</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSYC753 Data Fluency: Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple1" class="section level1" number="2">
<h1><span class="header-section-number">Session 2</span> Multiple regression: multiple continuous predictors</h1>
<p><em>Chris Berry</em><br />
<em>2022</em></p>
<style>
div.exercise { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<style>
div.tip { background-color:#D5F5E3; border-radius: 5px; padding: 20px;}
</style>
<div id="overview-2" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Overview</h2>
<p><br />
</p>
<ul>
<li><strong>Slides</strong> from the lecture part of the session: <a href="slides/PSYC753_L2_MultipleRegression1.pptx">Download</a></li>
</ul>
<p><br />
</p>
<p>This worksheet assumes you have gone through the previous one on <a href="simple1.html#simple1">simple regression</a>.</p>
<p><br />
</p>
<p>When we want to determine the extent to which an outcome variable (e.g., psychological wellbeing) is predicted by <strong>multiple continuous predictors</strong> (e.g., both <em>worry</em> <strong>and</strong> <em>mindfulness</em> scores), we can use <strong>multiple regression</strong>.</p>
<p>Adding multiple predictors to a model may serve to <em>improve</em> the prediction of the outcome variable. It can also be a way to test specific theories or hypotheses.</p>
<p><br />
</p>
<div class="tip">
<p><strong>Simple vs. Multiple Regression</strong></p>
<ul>
<li><p><strong>Simple regression</strong> is a linear model of the relationship between <em>one outcome variable and one predictor variable</em>. For example, can we predict <em>wellbeing</em> on the basis of <em>worry</em> scores?</p></li>
<li><p><strong>Multiple regression</strong> is a linear model of the relationship between <em>one outcome variable and more than one predictor variable</em>. For example, can we predict <em>wellbeing</em> based on <em>worry</em>, <em>mindfulness</em>, and <em>emotional intelligence</em> scores?</p></li>
</ul>
</div>
</div>
<div id="worked-example-1" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Worked example</h2>
<p>Iani et al. (2019) looked at factors associated with psychological wellbeing and distress in 66 individuals with generalised anxiety disorder. For educational purposes, we'll focus on a subset of their data, namely whether <strong>wellbeing</strong> is predicted by <strong>worry</strong> and <strong>describing</strong> scores in a multiple regression. <em>Describing</em> is the mindfulness skill of being able to describe one's inner experiences and feelings with words.</p>
<p><br />
</p>
<p>Read the data to R. The data are stored at:</p>
<p><a href="https://raw.githubusercontent.com/chrisjberry/Teaching/master/2_wellbeing_data.csv" class="uri">https://raw.githubusercontent.com/chrisjberry/Teaching/master/2_wellbeing_data.csv</a></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="multiple1.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First ensure tidyverse is loaded, i.e., &#39;library(tidyverse)&#39;</span></span>
<span id="cb1-2"><a href="multiple1.html#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="multiple1.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># read in the data using read_csv(), store in wellbeing_data</span></span>
<span id="cb1-4"><a href="multiple1.html#cb1-4" aria-hidden="true" tabindex="-1"></a>wellbeing_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://raw.githubusercontent.com/chrisjberry/Teaching/master/2_wellbeing_data.csv&#39;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="multiple1.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># preview the data with glimpse()</span></span>
<span id="cb2-2"><a href="multiple1.html#cb2-2" aria-hidden="true" tabindex="-1"></a>wellbeing_data <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>() </span></code></pre></div>
<p>We'll use these three variables in the dataset:</p>
<ul>
<li><code>wellbeing</code>: Higher scores indicate higher wellbeing.</li>
<li><code>worry</code>: Higher scores indicate higher levels of worry.</li>
<li><code>describing</code>: Higher scores indicate higher self-reported ability to describe one's inner experiences.</li>
</ul>
<p>(<em>Note.</em> The data are publicly available, but I've changed the variable names for clarity. As in Iani et al. (2019), missing values were replaced with the mean of the relevant variable.)</p>
<p><br />
</p>
<p>Visualise the data with a scatterplot. Place the outcome variable <code>wellbeing</code> on the y-axis, the predictor <code>worry</code> on the x-axis, and let the <em>size</em> of each point represent the second predictor, the <code>describing</code> score:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="multiple1.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatterplot of all three variables</span></span>
<span id="cb3-2"><a href="multiple1.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Use alpha to alter transparency of points</span></span>
<span id="cb3-3"><a href="multiple1.html#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># to make overlap easier to see</span></span>
<span id="cb3-4"><a href="multiple1.html#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="multiple1.html#cb3-5" aria-hidden="true" tabindex="-1"></a>wellbeing_data <span class="sc">%&gt;%</span> </span>
<span id="cb3-6"><a href="multiple1.html#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> worry, <span class="at">y =</span> wellbeing, <span class="at">size =</span> describing)) <span class="sc">+</span></span>
<span id="cb3-7"><a href="multiple1.html#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">colour =</span> <span class="st">&quot;cornflowerblue&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-4"></span>
<img src="02_multiple_regression_1_files/figure-html/unnamed-chunk-4-1.png" alt="Scatterplot of wellbeing scores vs. worry and describing" width="75%" />
<p class="caption">
Figure 2.1: Scatterplot of wellbeing scores vs. worry and describing
</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-1" class="exercise"><strong>Exercise 2.1  </strong></span>From inspection of the scatterplot:</p>
<ul>
<li>Greater <code>worry</code> scores tend to be associated with <select class='webex-select'><option value='blank'></option><option value='answer'>lower</option><option value=''>constant</option><option value=''>higher</option></select> <code>wellbeing</code> scores.</li>
</ul>
<div class="webex-solution">
<button>
Explain
</button>
<p>A negative trend between <code>worry</code> and <code>wellbeing</code> is evident in the scatterplot</p>
</div>
<p><br />
</p>
<ul>
<li>Greater <code>describing</code> scores tend to be associated with <select class='webex-select'><option value='blank'></option><option value=''>lower</option><option value=''>constant</option><option value='answer'>higher</option></select> <code>wellbeing</code> scores.</li>
</ul>
<div class="webex-solution">
<button>
Explain
</button>
<p>The size of the <code>describing</code> points tend to be larger when <code>wellbeing</code> scores are higher.</p>
</div>
<p><br />
</p>
<p>The above trends are also apparent in the Pearson correlations between variables:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="multiple1.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># select the relevant columns from wellbeing_data and </span></span>
<span id="cb4-2"><a href="multiple1.html#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># use correlate() to obtain the correlations</span></span>
<span id="cb4-3"><a href="multiple1.html#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="multiple1.html#cb4-4" aria-hidden="true" tabindex="-1"></a>wellbeing_data <span class="sc">%&gt;%</span> </span>
<span id="cb4-5"><a href="multiple1.html#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(wellbeing, worry, describing) <span class="sc">%&gt;%</span> </span>
<span id="cb4-6"><a href="multiple1.html#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlate</span>(<span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;background-color: lightblue !important;">
term
</th>
<th style="text-align:right;background-color: lightblue !important;">
wellbeing
</th>
<th style="text-align:right;background-color: lightblue !important;">
worry
</th>
<th style="text-align:right;background-color: lightblue !important;">
describing
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;background-color: lightblue !important;">
wellbeing
</td>
<td style="text-align:right;background-color: lightblue !important;">
NA
</td>
<td style="text-align:right;background-color: lightblue !important;">
-0.5419352
</td>
<td style="text-align:right;background-color: lightblue !important;">
0.5356548
</td>
</tr>
<tr>
<td style="text-align:left;background-color: lightblue !important;">
worry
</td>
<td style="text-align:right;background-color: lightblue !important;">
-0.5419352
</td>
<td style="text-align:right;background-color: lightblue !important;">
NA
</td>
<td style="text-align:right;background-color: lightblue !important;">
-0.2477970
</td>
</tr>
<tr>
<td style="text-align:left;background-color: lightblue !important;">
describing
</td>
<td style="text-align:right;background-color: lightblue !important;">
0.5356548
</td>
<td style="text-align:right;background-color: lightblue !important;">
-0.2477970
</td>
<td style="text-align:right;background-color: lightblue !important;">
NA
</td>
</tr>
</tbody>
</table>
<ul>
<li>The correlation between <code>wellbeing</code> and <code>worry</code> (to 2 decimal places) is <em>r</em> = <input class='webex-solveme nospaces' size='5' data-answer='["-0.54","-.54"]'/></li>
<li>The correlation between <code>wellbeing</code> and <code>describing</code> (to 2 decimal places) is <em>r</em> = <input class='webex-solveme nospaces' size='4' data-answer='[".54","0.54"]'/></li>
<li>The correlation between the two predictors (<code>worry</code> and <code>describing</code>) (to 2 decimal places) is <em>r</em> = <input class='webex-solveme nospaces' size='5' data-answer='["-.25","-0.25"]'/></li>
</ul>
</div>
<p><br />
</p>
<p><br />
</p>
<div class="tip">
<p><strong>Multiple regression using <code>lm()</code></strong></p>
<p>To include more than one predictor in a regression model, use the <code>+</code> symbol when specifying the model with <code>lm()</code>:</p>
<p><code>lm(outcome ~ predictor_1 + predictor_2 + predictor_3.... , data = mydata)</code></p>
<p>This runs a model of the form:</p>
<p><span class="math inline">\(Predicted \ outcome = a + b_1(Predictor \ 1) + b_2(Predictor \ 2) + b_3(Predictor \ 3) ...\)</span></p>
<p>Note that we don't need to specify the intercept <strong>a</strong> in <code>lm()</code> since it is included automatically by R (as is the case with simple regression).</p>
</div>
<p><br />
</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="multiple1.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># conduct a multiple regression, store it in multiple1</span></span>
<span id="cb5-2"><a href="multiple1.html#cb5-2" aria-hidden="true" tabindex="-1"></a>multiple1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> worry <span class="sc">+</span> describing, <span class="at">data =</span> wellbeing_data) </span>
<span id="cb5-3"><a href="multiple1.html#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="multiple1.html#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the coefficients</span></span>
<span id="cb5-5"><a href="multiple1.html#cb5-5" aria-hidden="true" tabindex="-1"></a>multiple1</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = wellbeing ~ worry + describing, data = wellbeing_data)
## 
## Coefficients:
## (Intercept)        worry   describing  
##     70.7306      -0.7708       1.2484</code></pre>
<ul>
<li><code>(Intercept)</code> is the value of the intercept <strong>a</strong> in the regression equation. Type to two decimal places:<input class='webex-solveme nospaces' size='5' data-answer='["70.73"]'/></li>
<li><code>worry</code> is the value of the coefficient <span class="math inline">\(b_1\)</span> for the <code>worry</code> predictor. <input class='webex-solveme nospaces' size='5' data-answer='["-0.77"]'/></li>
<li><code>describing</code> is the value of the coefficient <span class="math inline">\(b_2\)</span> for the <code>describing</code> predictor. <input class='webex-solveme nospaces' size='4' data-answer='["1.25"]'/></li>
</ul>
<p><br />
</p>
<p>The regression equation is therefore written as:</p>
<p><br />
</p>
<p><span class="math inline">\(Predicted\ wellbeing = 70.73 - 0.77(worry) + 1.25(describing)\)</span></p>
<p><br />
</p>
<div id="residual-plot" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Residual plot</h3>
<p>We can obtain a plot of the predicted values vs. the residuals in the same way as for simple regression by using <code>augment()</code> in the <code>broom</code> package.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="multiple1.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(multiple1) <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="multiple1.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span></span>
<span id="cb7-3"><a href="multiple1.html#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="multiple1.html#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-8"></span>
<img src="02_multiple_regression_1_files/figure-html/unnamed-chunk-8-1.png" alt="Scatterplot of the predicted values vs. residuals" width="60%" />
<p class="caption">
Figure 2.2: Scatterplot of the predicted values vs. residuals
</p>
</div>
<p>The points seem randomly and evenly distributed around the horizontal, in line with assumptions of homoscedasticity (equal variance of residuals at each predicted value), and independence of residuals.</p>
<p><br />
</p>
</div>
<div id="evaluating-the-model-bayes-factor" class="section level3" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Evaluating the model: Bayes Factor</h3>
<p><br />
</p>
<div class="tip">
<p>The Bayes Factor tells us how many more times likely the multiple regression model is, relative to the intercept-only model.</p>
</div>
<p><br />
</p>
<p>Use <code>lmBF()</code> to obtain the Bayes Factor for the multiple regression model:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="multiple1.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># store the BF for the model in multiple1_BF</span></span>
<span id="cb8-2"><a href="multiple1.html#cb8-2" aria-hidden="true" tabindex="-1"></a>multiple1_BF <span class="ot">&lt;-</span> <span class="fu">lmBF</span>(wellbeing <span class="sc">~</span> worry <span class="sc">+</span> describing, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb8-3"><a href="multiple1.html#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="multiple1.html#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># show the BF</span></span>
<span id="cb8-5"><a href="multiple1.html#cb8-5" aria-hidden="true" tabindex="-1"></a>multiple1_BF</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] worry + describing : 4190994 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The Bayes Factor for the model is <input class='webex-solveme nospaces' size='4,190,994' data-answer='["4190994"]'/>. This tells us that the model with <code>worry</code> and <code>describing</code> is over four million times more likely than an <code>Intercept only</code> model (one with no predictors). Thus, there's strong evidence that the multiple regression model explains <code>wellbeing</code>.</p>
<p><br />
</p>
</div>
<div id="evaluating-the-model-r2" class="section level3" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Evaluating the model: R<sup>2</sup></h3>
<p><br />
</p>
<div class="tip">
<p>R<sup>2</sup> tells us how much variance in the outcome variable is explained by the multiple regression model.</p>
</div>
<p><br />
</p>
<p>Use <code>glance()</code> in the <code>broom</code> package to obtain the R<sup>2</sup> for the model:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="multiple1.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(multiple1)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr>
<th style="text-align:right;">
r.squared
</th>
<th style="text-align:right;">
adj.r.squared
</th>
<th style="text-align:right;">
sigma
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
logLik
</th>
<th style="text-align:right;">
AIC
</th>
<th style="text-align:right;">
BIC
</th>
<th style="text-align:right;">
deviance
</th>
<th style="text-align:right;">
df.residual
</th>
<th style="text-align:right;">
nobs
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.4653263
</td>
<td style="text-align:right;">
0.4483526
</td>
<td style="text-align:right;">
9.393314
</td>
<td style="text-align:right;">
27.41444
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
-239.9547
</td>
<td style="text-align:right;">
487.9093
</td>
<td style="text-align:right;">
496.6679
</td>
<td style="text-align:right;">
5558.763
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:right;">
66
</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li><code>r.squared</code> is <strong>R<sup>2</sup></strong>, the proportion of variance in <code>wellbeing</code> explained by the model. Thus, the model explains 0.4653, or 46.53% of the variance in <code>wellbeing</code>.</li>
<li><code>adj.r.squared</code> is the <strong>Adjusted R<sup>2</sup></strong> value, which is R<sup>2</sup> adjusted for the sample size and the number of predictors in the model. It is an estimate of R<sup>2</sup> for the population (not merely the scores we have in the sample), and is always less than R<sup>2</sup>. You'll see researchers reporting either R<sup>2</sup> or the adjusted R<sup>2</sup> in the literature. If you're not sure which one to use, report the adjusted R<sup>2</sup>, and say so (e.g., "adjusted R<sup>2</sup> = 44.83%").</li>
</ul>
<p>The adjusted R<sup>2</sup> value is 0.4483, so in a report we could say that a model with <code>worry</code> and <code>describing</code> explains <strong>44.83%</strong> of the variance in <code>wellbeing</code>.</p>
<p><br />
</p>
</div>
</div>
<div id="understanding-the-contribution-of-individual-predictors" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Understanding the contribution of individual predictors</h2>
<div class="tip">
<p>Because predictor variables are often correlated to a degree, some of the variance they explain in the outcome will be <strong>shared</strong>. A predictor's contribution to a model must therefore only be interpreted <em>after</em> the other predictors in the model have been taken into account. This is explained in more detail below.</p>
</div>
<div id="r2-in-simple-vs.-multiple-regression" class="section level3" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> R<sup>2</sup> in simple vs. multiple regression</h3>
<p>In a simple regression of <code>wellbeing ~ worry</code>, the variance in <code>wellbeing</code> explained by <code>worry</code> is <strong>R<sup>2</sup> = 29.37%</strong>:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="multiple1.html#cb11-1" aria-hidden="true" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> worry, <span class="at">data =</span> wellbeing_data)</span>
<span id="cb11-2"><a href="multiple1.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(s1)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr>
<th style="text-align:right;">
r.squared
</th>
<th style="text-align:right;">
adj.r.squared
</th>
<th style="text-align:right;">
sigma
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
logLik
</th>
<th style="text-align:right;">
AIC
</th>
<th style="text-align:right;">
BIC
</th>
<th style="text-align:right;">
deviance
</th>
<th style="text-align:right;">
df.residual
</th>
<th style="text-align:right;">
nobs
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.2936938
</td>
<td style="text-align:right;">
0.2826578
</td>
<td style="text-align:right;">
10.71152
</td>
<td style="text-align:right;">
26.61226
</td>
<td style="text-align:right;">
2.6e-06
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
-249.1416
</td>
<td style="text-align:right;">
504.2832
</td>
<td style="text-align:right;">
510.8522
</td>
<td style="text-align:right;">
7343.15
</td>
<td style="text-align:right;">
64
</td>
<td style="text-align:right;">
66
</td>
</tr>
</tbody>
</table>
</div>
<p><br />
</p>
<p>In a simple regression of <code>wellbeing ~ describing</code>, the variance in <code>wellbeing</code> explained by <code>describing</code> is <strong>R<sup>2</sup> = 28.69%</strong></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="multiple1.html#cb12-1" aria-hidden="true" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> describing, <span class="at">data =</span> wellbeing_data)</span>
<span id="cb12-2"><a href="multiple1.html#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(s2)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr>
<th style="text-align:right;">
r.squared
</th>
<th style="text-align:right;">
adj.r.squared
</th>
<th style="text-align:right;">
sigma
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
logLik
</th>
<th style="text-align:right;">
AIC
</th>
<th style="text-align:right;">
BIC
</th>
<th style="text-align:right;">
deviance
</th>
<th style="text-align:right;">
df.residual
</th>
<th style="text-align:right;">
nobs
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.286926
</td>
<td style="text-align:right;">
0.2757842
</td>
<td style="text-align:right;">
10.76272
</td>
<td style="text-align:right;">
25.75226
</td>
<td style="text-align:right;">
3.6e-06
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
-249.4563
</td>
<td style="text-align:right;">
504.9126
</td>
<td style="text-align:right;">
511.4816
</td>
<td style="text-align:right;">
7413.512
</td>
<td style="text-align:right;">
64
</td>
<td style="text-align:right;">
66
</td>
</tr>
</tbody>
</table>
</div>
<p><br />
</p>
<p>So, by looking at the (non-adjusted) R<sup>2</sup> values of our simple and multiple regressions so far, an interesting pattern is evident:</p>
<ul>
<li><p>In the simple regression of <code>wellbeing ~ worry</code>, R<sup>2</sup> = <strong>29.37%</strong></p></li>
<li><p>In the simple regression of <code>wellbeing ~ describing</code>, R<sup>2</sup> = <strong>28.69%</strong></p></li>
<li><p>Yet, in a multiple regression of <code>wellbeing ~ worry + describing</code>, R<sup>2</sup> = <strong>46.56%</strong>, which is <strong><em>less</em></strong> than the sum of R<sup>2</sup> from the simple regressions (29.37 + 28.69 = 58.06%).</p></li>
</ul>
<p>The reason why the R<sup>2</sup> values from the simple regressions don't add up to the same value as the R<sup>2</sup> for the multiple regression is because <code>worry</code> and <code>describing</code> are <em>correlated</em> (<em>r</em> = -0.25, as you obtained earlier). This means that some of the variance that they explain in <code>wellbeing</code> is <em>shared</em>.</p>
<p><br />
</p>
</div>
<div id="venn-diagrams" class="section level3" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Venn Diagrams</h3>
<div class="tip">
<p>Venn diagrams are useful for understanding the variance that predictors explain in the outcome variable. They are especially useful for understanding R<sup>2</sup> in multiple regression. Here, I use them to explain why the R<sup>2</sup> values from simple regressions don't necessarily add up to R<sup>2</sup> when the same predictors are in a multiple regression.</p>
</div>
<p><br />
</p>
<p>Suppose the rectangle below represents all of the <em>variance</em> in <code>wellbeing</code> to be explained.</p>
<p><img src="images/Venn1.jpg" style="width:70.0%" /></p>
<p>The area of the circle below represents the variance in <code>wellbeing</code> explained by <code>worry</code> in the first simple regression. If this diagram were drawn to scale (it's not!), the area of the circle would be equal to the value of <span class="math inline">\(R^2\)</span> (i.e., 29.37%).</p>
<p><img src="images/Venn2.jpg" style="width:70.0%" /></p>
<p>The part of the rectangle not inside the circle represents the variance in <code>wellbeing</code> that is <em>not</em> explained by the model (i.e., the unexplained or <em>residual</em> variance).</p>
<p>We'll now add <code>describing</code> to the model with <code>worry</code>. We could represent this on a Venn diagram as follows:</p>
<p><img src="images/Venn3.jpg" style="width:60.0%" /></p>
<p>The correlation is represented as an <em>overlap</em> in the circles. Their total area (R<sup>2</sup> for the multiple regression model = 46.56%) is <em>less</em> than the area they'd explain if there were no overlap (58.06%).</p>
<p><strong>This highlights an important point</strong>: Predictors are often correlated to some degree, so in multiple regression it only really makes sense to talk about the contribution a predictor makes <em>in the context of the other predictors in the model</em>. That is, a given predictor explains variance in the outcome variable only <em>after the other predictors in the model have been taken into account</em>.</p>
<p>Given that the <strong>unique</strong> contributions of <code>worry</code> and <code>describing</code> are lower in a multiple regression model, we must ask whether there's evidence that each predictor makes a unique contribution, over an above the other predictor. For example, is there sufficient evidence for a unique contribution of <code>worry</code>, once <code>describing</code> has been taken into account? If not, we probably wouldn't include it in the model.</p>
<p><br />
</p>
</div>
<div id="using-bayes-factors-to-assess-the-unique-contribution-of-predictors" class="section level3" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Using Bayes factors to assess the unique contribution of predictors</h3>
<div class="tip">
<p>We can compare Bayes Factors to determine whether a given predictor in a multiple regression model makes a unique contribution to the prediction of the outcome variable.</p>
</div>
<p><br />
</p>
<p>First, obtain the Bayes Factor for the model in which <code>predictor_1</code> has been left out of the full model. Then obtain the Bayes Factor for model in which <code>predictor_2</code> has been left out of the model. Repeat this for as many predictors you have in the model.</p>
<p>In our example, this involves obtaining the BFs of the model of <code>wellbeing ~ describing</code>, and the BF of the model of <code>wellbeing ~ worry</code>:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="multiple1.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># BF for wellbeing ~ describing</span></span>
<span id="cb13-2"><a href="multiple1.html#cb13-2" aria-hidden="true" tabindex="-1"></a>describing_BF <span class="ot">&lt;-</span> <span class="fu">lmBF</span>(wellbeing <span class="sc">~</span> describing, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb13-3"><a href="multiple1.html#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="multiple1.html#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># BF for wellbeing ~ worry</span></span>
<span id="cb13-5"><a href="multiple1.html#cb13-5" aria-hidden="true" tabindex="-1"></a>worry_BF <span class="ot">&lt;-</span> <span class="fu">lmBF</span>(wellbeing <span class="sc">~</span> worry, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span></code></pre></div>
<p>We also need the BF for the full model:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="multiple1.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># BF for wellbeing ~ worry + describing</span></span>
<span id="cb14-2"><a href="multiple1.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (this is the same as multiple1_BF above, but </span></span>
<span id="cb14-3"><a href="multiple1.html#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  with a different name, which will help us see what&#39;s going on later)</span></span>
<span id="cb14-4"><a href="multiple1.html#cb14-4" aria-hidden="true" tabindex="-1"></a>worry_describing_BF <span class="ot">&lt;-</span> <span class="fu">lmBF</span>(wellbeing <span class="sc">~</span> worry <span class="sc">+</span> describing, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span></code></pre></div>
<p><br />
</p>
<div class="tip">
<p><strong>Comparing models</strong></p>
<p>We can use the following general formula to determine whether there's evidence for a more complex version of a model, relative to a simpler model:</p>
<p><code>BF_more_complex_model / BF_simpler_model</code></p>
<p>That is, we divide the BF for the more complex model by the BF for the simpler one. This then tells us <em>how many more times more likely the more complex model is, relative to the simpler one.</em></p>
<p>For example, if <code>BF_more_complex_model = 10</code> and <code>BF_simpler_model = 2</code>, then the more complex model is five times more likely than the simpler one (because 10 / 2 = 5). There'd be substantial evidence to prefer the more complex model.</p>
</div>
<p><br />
</p>
<p>In our case, we can compare Bayes Factor of the full model (<code>worry_describing_BF</code>) with that of our simpler models (<code>describing_BF</code>) and (<code>worry_BF</code>) in order to determine whether each predictor makes a unique contribution to the full model or not.</p>
<p><br />
</p>
<p>To determine if there's evidence for the unique contribution of <code>worry</code> to the model:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="multiple1.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare BFs for the full model and one in which worry is left out</span></span>
<span id="cb15-2"><a href="multiple1.html#cb15-2" aria-hidden="true" tabindex="-1"></a>worry_describing_BF <span class="sc">/</span> describing_BF</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] worry + describing : 981.4912 ±0%
## 
## Against denominator:
##   wellbeing ~ describing 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The BF for the comparison is <strong>981.49</strong>, indicating that there's substantial evidence that the addition of <code>worry</code> to a model containing <code>describing</code> improves the model. In other words, there's evidence for a unique contribution of <code>worry</code> to the prediction of <code>wellbeing</code>.</p>
<p><br />
</p>
<p>To determine if there's evidence for the unique contribution of <code>describing</code> to the model:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="multiple1.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the BFs for the full model and one in which describing is left out</span></span>
<span id="cb17-2"><a href="multiple1.html#cb17-2" aria-hidden="true" tabindex="-1"></a>worry_describing_BF <span class="sc">/</span> worry_BF</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] worry + describing : 738.4095 ±0%
## 
## Against denominator:
##   wellbeing ~ worry 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The BF comparing the full model with one containing <code>worry</code> alone is <strong>738.41</strong>. This indicates that the model with both <code>worry</code> and <code>describing</code> is over seven hundred times more likely than the model with <code>worry</code> alone. The BF is greater than 3, so this indicates substantial evidence for the unique contribution of <code>describing</code> to the prediction of <code>wellbeing</code>.</p>
<p>Thus, in a multiple regression model, there's substantial evidence that both <code>worry</code> and <code>describing</code> predict <code>wellbeing</code> overall (BF = 4,190,994). There's also substantial evidence that <code>worry</code> (BF = 981.49) and <code>describing</code> (BF = 738.41) make unique contributions to this model. The model with both predictors included therefore seems justified.</p>
<p><br />
</p>
</div>
</div>
<div id="multicollinearity" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Multicollinearity</h2>
<div class="tip">
<p>If the correlation between predictors is very high (greater than <em>r</em> = 0.8 or less than -0.8), this is known as <strong>multicollinearity</strong>.</p>
</div>
<p><br />
</p>
<p>Multicollinearity can be a problem in multiple regression. Predictors may explain a large amount of variance in the outcome variable, but their 'unique' contribution in a multiple regression may be small. In an extreme scenario, <em>neither</em> predictor makes a unique contribution, even though the overall regression explains a large amount of variance in the outcome variable! On a Venn diagram, the circles representing the predictors would almost completely overlap:</p>
<p><img src="images/Venn_multi.jpg" style="width:75.0%" /></p>
<p>Multicollinearity should be avoided. Therefore, check for extreme correlations between your predictor variables before including them in a multiple regression.</p>
<p>The correlation between the predictor variables in the model of <code>wellbeing ~ worry + describing</code> was <input class='webex-solveme nospaces' size='-.25' data-answer='["-0.25"]'/>, and multicollinearity was therefore <select class='webex-select'><option value='blank'></option><option value=''>of concern</option><option value='answer'>of no concern</option><option value=''>not possible to determine</option></select>.</p>
<p><br />
</p>
<div class="tip">
<p><strong>How many predictor variables should be included in a model?</strong></p>
<p>If adding predictors to the regression improves the prediction of the outcome variable, you may think that we can simply keep adding in variables to the model, until all the residual variance has been explained. This seems fine until we learn that if we were to add as many predictors to the model as there are rows in our data (e.g., 66 participants in<code>wellbeing_data</code>), then we'd perfectly predict the outcome variable, and have a (non-adjusted) <span class="math inline">\(R^2\)</span> of 100%! This would be true even if the predictors consisted of random values. Our model would clearly be meaningless though.</p>
<p>We ideally want to explain the outcome variable with relatively few predictors, or for our selection of predictors to be guided by specific hypotheses or theory.</p>
</div>
<p><br />
</p>
</div>
<div id="exercise-1" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Exercise</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-2" class="exercise"><strong>Exercise 2.2  </strong></span>Main Exercise</p>
<p>The <code>wellbeing_data</code> also contain these columns:</p>
<ul>
<li><code>gad</code> : Severity of symptoms of GAD (Generalised Anxiety Disorder). Higher scores indicate greater severity of symptoms.</li>
<li><code>brooding</code> : Higher scores indicate higher levels of brooding (i.e., being preoccupied with depressing, morbid, or painful memories or thoughts).</li>
<li><code>observing</code> : Higher scores indicate greater tendency to notice things in one's environment (e.g., smells, sounds, visual elements). It's another measure of mindfulness.</li>
</ul>
<p><br />
</p>
<p><strong>Use multiple regression to investigate the extent to which <code>brooding</code> and <code>observing</code> predict <code>gad</code>. Adapt the code in this worksheet to do the following things (and try not to look at the solution until you've attempted the question):</strong></p>
<p><br />
</p>
<p><strong>1. Visualise the relationship between <code>gad</code>, <code>brooding</code> and <code>observing</code> in a scatterplot.</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Pipe <code>wellbeing_data</code> to <code>ggplot()</code> and use <code>geom_point()</code>. Use the <code>size</code> option to specify the second predictor variable in <code>aes()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="multiple1.html#cb19-1" aria-hidden="true" tabindex="-1"></a>wellbeing_data <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="multiple1.html#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> brooding, <span class="at">y =</span> gad, <span class="at">size =</span> observing)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="multiple1.html#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb19-4"><a href="multiple1.html#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Brooding&quot;</span>) <span class="sc">+</span> </span>
<span id="cb19-5"><a href="multiple1.html#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;GAD severity of symptoms score&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-6"><a href="multiple1.html#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-17"></span>
<img src="02_multiple_regression_1_files/figure-html/unnamed-chunk-17-1.png" alt="GAD vs. brooding and observing scores" width="50%" />
<p class="caption">
Figure 2.3: GAD vs. brooding and observing scores
</p>
</div>
<p>In the scatterplot, <code>observing</code> could have also been swapped around with <code>brooding</code>. Try both ways.</p>
</div>
<ul>
<li>Greater <code>brooding</code> scores tend to be associated with <select class='webex-select'><option value='blank'></option><option value=''>lower</option><option value=''>no appreciable change in</option><option value='answer'>higher</option></select> <code>gad</code> scores.</li>
<li>Greater <code>observing</code> scores tend to be associated with <select class='webex-select'><option value='blank'></option><option value=''>lower</option><option value='answer'>no appreciable change in</option><option value=''>higher</option></select> <code>gad</code> scores.</li>
</ul>
<p><br />
</p>
<p><strong>2. Obtain the correlations between <code>gad</code>, <code>brooding</code>, and <code>observing</code></strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Pipe the <code>wellbeing_data</code> to <code>select()</code> and use <code>correlate()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="multiple1.html#cb20-1" aria-hidden="true" tabindex="-1"></a>wellbeing_data <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="multiple1.html#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(gad, brooding, observing) <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="multiple1.html#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlate</span>(<span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
</div>
<p><strong>State the correlations to two decimal places:</strong></p>
<ul>
<li>The correlation between the GAD score and brooding is <em>r</em> = <input class='webex-solveme nospaces' size='4' data-answer='["0.60",".60"]'/></li>
<li>The correlation between the GAD score and observing is <em>r</em> = <input class='webex-solveme nospaces' size='5' data-answer='["-0.12","-.12"]'/></li>
<li>The correlation between brooding and observing is <em>r</em> = <input class='webex-solveme nospaces' size='5' data-answer='["-0.18","-.18"]'/></li>
</ul>
<p><br />
</p>
<p><strong>Is multicollinearity a concern between the two predictor variables?</strong> <select class='webex-select'><option value='blank'></option><option value=''>yes</option><option value='answer'>no</option><option value=''>cannot determine</option></select></p>
<div class="webex-solution">
<button>
Explanation
</button>
<p>The correlation between the predictor variables is <em>r</em> = -.18. Although they are weakly correlated, this does not exceed r = -.80, and therefore multicolinearity is not a concern.</p>
</div>
<p><br />
</p>
<p><strong>3. Conduct a multiple regression, with <code>gad</code> as the outcome variable, and <code>brooding</code> and <code>observing</code> as the predictor variables</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Use <code>lm()</code> to specify the simple regression. Store it in <code>multiple2</code>.</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="multiple1.html#cb21-1" aria-hidden="true" tabindex="-1"></a>multiple2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(gad <span class="sc">~</span> brooding <span class="sc">+</span> observing, <span class="at">data =</span> wellbeing_data)</span>
<span id="cb21-2"><a href="multiple1.html#cb21-2" aria-hidden="true" tabindex="-1"></a>multiple2</span></code></pre></div>
</div>
<p>What is the value of the intercept a (to two decimal places)? <input class='webex-solveme nospaces' size='4' data-answer='["0.07"]'/></p>
<p>What is the value of the coefficient for <code>brooding</code> (to two decimal places)? <input class='webex-solveme nospaces' size='4' data-answer='["0.89"]'/></p>
<p>What is the value of the coefficient for <code>observing</code> (to two decimal places)? <input class='webex-solveme nospaces' size='5' data-answer='["-0.02"]'/></p>
<p><br />
</p>
<p>What is the regression equation?</p>
<div id="radio_SJODLFJRSJ" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_SJODLFJRSJ" value=""></input> <span>Predicted GAD score = 0.07 - 0.89(brooding) + 0.02(observing)</span></label><label><input type="radio" autocomplete="off" name="radio_SJODLFJRSJ" value=""></input> <span>Predicted GAD score = 0.07 + 0.02(brooding) - 0.89(observing)</span></label><label><input type="radio" autocomplete="off" name="radio_SJODLFJRSJ" value="answer"></input> <span>Predicted GAD score = 0.07 + 0.89(brooding) - 0.02(observing)</span></label>
</div>
<p><br />
</p>
<p><strong>4. Obtain R<sup>2</sup> for the model</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Make sure you have stored the regression results (e.g., in <code>mutliple2</code>), then use <code>glance()</code> with that variable.</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="multiple1.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(multiple2)</span></code></pre></div>
</div>
<p>What proportion of variance in the GAD score is explained by the model containing <code>brooding</code> and <code>observing</code>? (Report the adjusted R-squared value as a proportion, to two decimal places) <input class='webex-solveme nospaces' size='4' data-answer='["0.34",".34"]'/></p>
<p>Report the value of adjusted R-squared as a percentage, to two decimal places: The adjusted R<sup>2</sup> value is equal to <input class='webex-solveme nospaces' size='5' data-answer='["34.50"]'/>%</p>
<p><br />
</p>
<p><strong>5. Obtain the Bayes Factor for the model</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Use <code>lmBF()</code> to specify the multiple regression model</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="multiple1.html#cb23-1" aria-hidden="true" tabindex="-1"></a>multiple2_BF <span class="ot">&lt;-</span> <span class="fu">lmBF</span>(gad <span class="sc">~</span> brooding <span class="sc">+</span> observing, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span></code></pre></div>
</div>
<p>How many times more likely is the model with <code>brooding</code> and <code>observing</code> as a predictor of <code>gad</code>, compared to an intercept-only model? (to two decimal places) <input class='webex-solveme nospaces' size='8' data-answer='["26889.69"]'/></p>
<p><br />
</p>
<p><strong>6. Plot the predicted values against the residuals.</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Use <code>augment()</code> with <code>ggplot()</code> and <code>geom_point()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="multiple1.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(multiple2) <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="multiple1.html#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span> </span>
<span id="cb24-3"><a href="multiple1.html#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb24-4"><a href="multiple1.html#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>)</span></code></pre></div>
</div>
<p><strong>What type of trend is evident between the predicted values and the residuals <select class='webex-select'><option value='blank'></option><option value=''>positive trend</option><option value='answer'>there's no association</option><option value=''>negative association</option></select></strong></p>
<div class="webex-solution">
<button>
Further interpretation
</button>
<p>Although there's a slight negative association for lower predicted values, the assumptions of homoscedasticity and independence of residuals appear to be met. You could also try adding the code <code>+ geom_smooth(method = "lm", se = FALSE)</code> to your plot to see what the (linear) trend line would actually be.</p>
</div>
<p><br />
</p>
<p><strong>7. Using <code>lmBF()</code>, determine whether there's evidence for a unique contribution of <code>brooding</code> and <code>observing</code> to prediction of <code>gad</code></strong></p>
<ul>
<li><p>The BF associated with the unique contribution of <code>observing</code> is <input class='webex-solveme nospaces' size='4' data-answer='["0.19"]'/></p></li>
<li><p>The BF associated with the unique contribution of <code>brooding</code> is <input class='webex-solveme nospaces' size='8' data-answer='["71841.28"]'/></p></li>
</ul>
<div class="webex-solution">
<button>
Hint 1
</button>
<ul>
<li>Use <code>lmBF()</code> to obtain the BF for both simple regressions and the multiple regression.</li>
<li>Then use the general formula <code>BF_more_complex_model / BF_simpler_model</code> to obtain the BF for the unique contribution of each predictor.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Hint 2
</button>
<p>To get the BF for the two simple regressions:</p>
<p><code>BF_brooding &lt;- lmBF(gad ~ brooding, data = data.frame(wellbeing_data))</code></p>
<p><code>BF_observing &lt;- lmBF(gad ~ observing, data = data.frame(wellbeing_data))</code></p>
<p><br />
</p>
<p>The multiple regression BF (same as <code>multiple2_BF</code>):</p>
<p><code>BF_brooding_observing &lt;- lmBF(gad ~ brooding + observing, data = data.frame(wellbeing_data))</code></p>
<p><br />
Then the BFs for relevant models need to be compared, using:</p>
<p><code>BF_more_complex_model / BF_simpler_model</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="multiple1.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># BF for gad ~ brooding</span></span>
<span id="cb25-2"><a href="multiple1.html#cb25-2" aria-hidden="true" tabindex="-1"></a>BF_brooding <span class="ot">&lt;-</span> <span class="fu">lmBF</span>(gad <span class="sc">~</span> brooding, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb25-3"><a href="multiple1.html#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="multiple1.html#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># BF for gad ~ observing</span></span>
<span id="cb25-5"><a href="multiple1.html#cb25-5" aria-hidden="true" tabindex="-1"></a>BF_observing <span class="ot">&lt;-</span> <span class="fu">lmBF</span>(gad <span class="sc">~</span> observing, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb25-6"><a href="multiple1.html#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="multiple1.html#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co"># BF for full model</span></span>
<span id="cb25-8"><a href="multiple1.html#cb25-8" aria-hidden="true" tabindex="-1"></a>BF_brooding_observing <span class="ot">&lt;-</span> <span class="fu">lmBF</span>(gad <span class="sc">~</span> brooding <span class="sc">+</span> observing, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb25-9"><a href="multiple1.html#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="multiple1.html#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="multiple1.html#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># BF for the unique contribution of observing</span></span>
<span id="cb25-12"><a href="multiple1.html#cb25-12" aria-hidden="true" tabindex="-1"></a>BF_brooding_observing <span class="sc">/</span> BF_brooding</span>
<span id="cb25-13"><a href="multiple1.html#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="multiple1.html#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co"># BF for the unique contribution of brooding</span></span>
<span id="cb25-15"><a href="multiple1.html#cb25-15" aria-hidden="true" tabindex="-1"></a>BF_brooding_observing <span class="sc">/</span> BF_observing</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>8. On balance, is there evidence for a model containing both brooding and observing as predictors of GAD scores?</strong></p>
<div class="webex-solution">
<button>
Hint
</button>
<p>Look at BF for the unique contributions. If the BF is greater than 3, this indicates substantial evidence for the inclusion of that predictor in the model. If the BF is less than 0.33, then there's substantial evidence against its inclusion (the simpler model is preferable). Intermediate BFs are inconclusive, and the predictor should therefore be left out.</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<p>Together, <code>brooding</code> and <code>observing</code> explain 34.50% of the variance in GAD scores (adjusted R<sup>2</sup>), and there was strong evidence for this model, compared to an intercept only model, BF = 26889.69. There was, however, no evidence for a unique contribution of <code>observing</code> to the model (BF = 0.19), but there was substantial evidence for a unique contribution of <code>brooding</code> to the model, BF = 741841.28, whereby greater GAD scores were associated with higher <code>brooding</code> scores. In the interest of parsimony (not making models more complex than they need to be), the results suggest that only <code>brooding</code> predicts GAD and <code>observing</code> should not be included in the model that also contains <code>brooding</code>.</p>
</div>
</div>
<p><br />
</p>
<p><br />
</p>
</div>
<div id="further-exercises-1" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> Further exercises</h2>
<p>Not essential. For those confident with everything.</p>
<div id="regressionbf" class="section level3" number="2.6.1">
<h3><span class="header-section-number">2.6.1</span> <code>regressionBF()</code></h3>
<p>When determining the BF for the unique contribution of a predictor, as a shortcut, we could have used <code>regressionBF()</code>, rather than using <code>lmBF()</code> multiple times. <code>regressionBF()</code> automatically calculates the BFs for all permutations of a set of predictors in a model.</p>
<p>For our first model of <code>wellbeing</code> on the basis of <code>worry</code> and <code>describing</code>:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="multiple1.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain BFs for all permutations of the model predictors</span></span>
<span id="cb26-2"><a href="multiple1.html#cb26-2" aria-hidden="true" tabindex="-1"></a>all_BFs <span class="ot">&lt;-</span> <span class="fu">regressionBF</span>(wellbeing <span class="sc">~</span> worry <span class="sc">+</span> describing, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb26-3"><a href="multiple1.html#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="multiple1.html#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the BFs</span></span>
<span id="cb26-5"><a href="multiple1.html#cb26-5" aria-hidden="true" tabindex="-1"></a>all_BFs</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] worry              : 5675.703 ±0%
## [2] describing         : 4270.027 ±0%
## [3] worry + describing : 4190994  ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<ul>
<li>"[1]" is the BF for the model with <code>worry</code> as the sole predictor of <code>wellbeing</code></li>
<li>"[2]" is the BF for the model with <code>describing</code> as the sole predictor of <code>wellbeing</code></li>
<li>"[3]" is the BF for the model with <code>worry</code> and <code>describing</code> as predictors</li>
</ul>
<p><br />
</p>
<p>Comparing the BF for [3] and [2] will tell us whether there's evidence that <code>worry</code> makes a unique contribution.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="multiple1.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare multiple regression with simple regression 2</span></span>
<span id="cb28-2"><a href="multiple1.html#cb28-2" aria-hidden="true" tabindex="-1"></a>all_BFs[<span class="dv">3</span>] <span class="sc">/</span> all_BFs[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] worry + describing : 981.4912 ±0%
## 
## Against denominator:
##   wellbeing ~ describing 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The BF for this comparison is <strong>981.49</strong>, which matches the BF for the unique contribution of <code>describing</code> calculated earlier.</p>
<p><br />
</p>
<p>Comparing the BF for [3] and [1] will therefore tell us whether there's evidence that <code>describing</code> makes a unique contribution to the model:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="multiple1.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the BF for [3] and [1]</span></span>
<span id="cb30-2"><a href="multiple1.html#cb30-2" aria-hidden="true" tabindex="-1"></a>all_BFs[<span class="dv">3</span>] <span class="sc">/</span> all_BFs[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] worry + describing : 738.4095 ±0%
## 
## Against denominator:
##   wellbeing ~ worry 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The BF for this comparison is <strong>738.41</strong>, which matches the BF for the unique contribution of <code>describing</code> calculated earlier.</p>
<p><br />
</p>
<p>Thus, the BFs derived by this method are the same as when we used <code>lmBF()</code> in the main section of the worksheet.</p>
<p><br />
</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-3" class="exercise"><strong>Exercise 2.3  </strong></span>Further exercise 1</p>
<p>Use <code>regressionBF()</code> to obtain the BFs for the unique contribution of <code>brooding</code> and <code>observation</code> in the model in the Main Exercise (i.e., <code>gad ~ brooding + observation</code>), and check that they are the same as the ones produced when you used <code>lmBF()</code></p>
</div>
<p><br />
</p>
</div>
<div id="predicting-new-data" class="section level3" number="2.6.2">
<h3><span class="header-section-number">2.6.2</span> Predicting new data</h3>
<p>As with simple regression, we can use <code>augment()</code> to predict what the outcome variable would be, given new data. For example, for a new individual with a <code>worry</code> score of 20 and <code>describing</code> score of 15:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="multiple1.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specify the new data (for each predictor in the model)</span></span>
<span id="cb32-2"><a href="multiple1.html#cb32-2" aria-hidden="true" tabindex="-1"></a>new_scores <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">worry =</span> <span class="dv">20</span>, </span>
<span id="cb32-3"><a href="multiple1.html#cb32-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">describing =</span> <span class="dv">15</span>)</span>
<span id="cb32-4"><a href="multiple1.html#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="multiple1.html#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># use augment() in the broom package to obtain the prediction</span></span>
<span id="cb32-6"><a href="multiple1.html#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb32-7"><a href="multiple1.html#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(multiple1, <span class="at">newdata =</span> new_scores)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr>
<th style="text-align:right;">
worry
</th>
<th style="text-align:right;">
describing
</th>
<th style="text-align:right;">
.fitted
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
74.03992
</td>
</tr>
</tbody>
</table>
</div>
<p><code>.fitted</code> contains the predicted <code>wellbeing</code> score, and is equal to 74.04.</p>
<p><br />
</p>
<p>To derive predictions for several new participants, use <code>c(score1, score2...)</code> when specifying the <code>new_scores</code>. To add another individual with a <code>worry</code> score of 25 and <code>describing</code> score of 10</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="multiple1.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specify the new data (for both predictors)</span></span>
<span id="cb33-2"><a href="multiple1.html#cb33-2" aria-hidden="true" tabindex="-1"></a>new_scores <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">worry =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">25</span>), </span>
<span id="cb33-3"><a href="multiple1.html#cb33-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">describing =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">10</span>))</span>
<span id="cb33-4"><a href="multiple1.html#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="multiple1.html#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># use augment() in the broom package for the predictions</span></span>
<span id="cb33-6"><a href="multiple1.html#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(multiple1, <span class="at">newdata =</span> new_scores)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr>
<th style="text-align:right;">
worry
</th>
<th style="text-align:right;">
describing
</th>
<th style="text-align:right;">
.fitted
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
74.03992
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
63.94410
</td>
</tr>
</tbody>
</table>
</div>
<p>Each row contains the details for a new person. The <code>.fitted</code> column contains the predicted <code>wellbeing</code> scores: <strong>74.04</strong> and <strong>63.94</strong>.</p>
<p><br />
</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-4" class="exercise"><strong>Exercise 2.4  </strong></span>Predicting data</p>
<p>For the model in the main exercise (i.e., <code>gad ~ brooding + observing</code>), what are the predicted values of <code>gad</code> for three new individuals with <code>brooding</code> scores of 10, 15, and 20, and <code>observing</code> scores of 3, 6 and 9, respectively.</p>
<ul>
<li>Predicted GAD of participant 1 (to one decimal place) = <input class='webex-solveme nospaces' size='3' data-answer='["8.9"]'/></li>
<li>Predicted GAD of participant 2 (to one decimal place) = <input class='webex-solveme nospaces' size='4' data-answer='["13.2"]'/></li>
<li>Predicted GAD of participant 3 (to one decimal place) = <input class='webex-solveme nospaces' size='4' data-answer='["17.6"]'/></li>
</ul>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="multiple1.html#cb34-1" aria-hidden="true" tabindex="-1"></a>new_scores <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">brooding =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>),</span>
<span id="cb34-2"><a href="multiple1.html#cb34-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">observing =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">9</span>))</span>
<span id="cb34-3"><a href="multiple1.html#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="multiple1.html#cb34-4" aria-hidden="true" tabindex="-1"></a>multiple2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(gad <span class="sc">~</span> brooding <span class="sc">+</span> observing, <span class="at">data =</span> wellbeing_data)</span>
<span id="cb34-5"><a href="multiple1.html#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="multiple1.html#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(multiple2, <span class="at">newdata =</span> new_scores)</span></code></pre></div>
</div>
</div>
<p><br />
</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-5" class="exercise"><strong>Exercise 2.5  </strong></span>Further exercise</p>
<p>Not essential. Only for if you are <em>really</em> confident with everything.</p>
<p>The variables <code>attention</code>, <code>clarity</code> and <code>repair</code> in the <code>wellbeing_data</code> are measures of emotional intelligence. To what extent do these three predictors uniquely explain <code>wellbeing</code> in a multiple regression?</p>
<ul>
<li>The BF for the unique contribution of <code>attention</code> = <input class='webex-solveme nospaces' size='5' data-answer='["81.01"]'/></li>
<li>The BF for the unique contribution of <code>clarity</code> = <input class='webex-solveme nospaces' size='4' data-answer='["3.84"]'/></li>
<li>The BF for the unique contribution of <code>repair</code> = <input class='webex-solveme nospaces' size='5' data-answer='["82.36"]'/></li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<p>Obtain the BF for the full model and the BFs for the models in which each of the predictors have been left out. Compare the BF for the full model with that of the model with the predictor left out in order to obtain the BF for the unique contribution of that predictor.</p>
</div>
<p><br />
</p>
<div class="webex-solution">
<button>
Solution
</button>
<p>Check correlations:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="multiple1.html#cb35-1" aria-hidden="true" tabindex="-1"></a>wellbeing_data <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="multiple1.html#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(wellbeing, attention, clarity, repair) <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="multiple1.html#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">correlate</span>(<span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<pre><code>## 
## Correlation method: &#39;pearson&#39;
## Missing treated using: &#39;pairwise.complete.obs&#39;</code></pre>
<div class="kable-table">
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
wellbeing
</th>
<th style="text-align:right;">
attention
</th>
<th style="text-align:right;">
clarity
</th>
<th style="text-align:right;">
repair
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
wellbeing
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
-0.3162625
</td>
<td style="text-align:right;">
0.3755731
</td>
<td style="text-align:right;">
0.5002038
</td>
</tr>
<tr>
<td style="text-align:left;">
attention
</td>
<td style="text-align:right;">
-0.3162625
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.1560582
</td>
<td style="text-align:right;">
0.0216476
</td>
</tr>
<tr>
<td style="text-align:left;">
clarity
</td>
<td style="text-align:right;">
0.3755731
</td>
<td style="text-align:right;">
0.1560582
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.4078774
</td>
</tr>
<tr>
<td style="text-align:left;">
repair
</td>
<td style="text-align:right;">
0.5002038
</td>
<td style="text-align:right;">
0.0216476
</td>
<td style="text-align:right;">
0.4078774
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
</div>
<p> </p>
<p>Run multiple regression:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="multiple1.html#cb37-1" aria-hidden="true" tabindex="-1"></a>multiple3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(wellbeing <span class="sc">~</span> attention <span class="sc">+</span> clarity <span class="sc">+</span> repair, <span class="at">data =</span> wellbeing_data)</span></code></pre></div>
<p><br />
</p>
<p>Adjusted R<sup>2</sup> for the overall model:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="multiple1.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>( multiple3 )</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr>
<th style="text-align:right;">
r.squared
</th>
<th style="text-align:right;">
adj.r.squared
</th>
<th style="text-align:right;">
sigma
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
logLik
</th>
<th style="text-align:right;">
AIC
</th>
<th style="text-align:right;">
BIC
</th>
<th style="text-align:right;">
deviance
</th>
<th style="text-align:right;">
df.residual
</th>
<th style="text-align:right;">
nobs
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.4167062
</td>
<td style="text-align:right;">
0.3884823
</td>
<td style="text-align:right;">
9.889914
</td>
<td style="text-align:right;">
14.76431
</td>
<td style="text-align:right;">
2e-07
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
-242.8268
</td>
<td style="text-align:right;">
495.6536
</td>
<td style="text-align:right;">
506.6019
</td>
<td style="text-align:right;">
6064.245
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
66
</td>
</tr>
</tbody>
</table>
</div>
<p><br />
</p>
<p>Using <code>lmBF()</code>:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="multiple1.html#cb39-1" aria-hidden="true" tabindex="-1"></a>BF_attention_clarity_repair <span class="ot">&lt;-</span></span>
<span id="cb39-2"><a href="multiple1.html#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lmBF</span>(wellbeing <span class="sc">~</span> attention <span class="sc">+</span> clarity <span class="sc">+</span> repair, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb39-3"><a href="multiple1.html#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="multiple1.html#cb39-4" aria-hidden="true" tabindex="-1"></a>BF_attention_clarity <span class="ot">&lt;-</span></span>
<span id="cb39-5"><a href="multiple1.html#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lmBF</span>(wellbeing <span class="sc">~</span> attention <span class="sc">+</span> clarity, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb39-6"><a href="multiple1.html#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="multiple1.html#cb39-7" aria-hidden="true" tabindex="-1"></a>BF_attention_repair <span class="ot">&lt;-</span></span>
<span id="cb39-8"><a href="multiple1.html#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lmBF</span>(wellbeing <span class="sc">~</span> attention <span class="sc">+</span> repair, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb39-9"><a href="multiple1.html#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="multiple1.html#cb39-10" aria-hidden="true" tabindex="-1"></a>BF_clarity_repair <span class="ot">&lt;-</span></span>
<span id="cb39-11"><a href="multiple1.html#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lmBF</span>(wellbeing <span class="sc">~</span> clarity <span class="sc">+</span> repair, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb39-12"><a href="multiple1.html#cb39-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-13"><a href="multiple1.html#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="co"># unique contribution of attention</span></span>
<span id="cb39-14"><a href="multiple1.html#cb39-14" aria-hidden="true" tabindex="-1"></a>BF_attention_clarity_repair <span class="sc">/</span> BF_clarity_repair</span>
<span id="cb39-15"><a href="multiple1.html#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="multiple1.html#cb39-16" aria-hidden="true" tabindex="-1"></a><span class="co"># unique contribution of clarity</span></span>
<span id="cb39-17"><a href="multiple1.html#cb39-17" aria-hidden="true" tabindex="-1"></a>BF_attention_clarity_repair <span class="sc">/</span> BF_attention_repair</span>
<span id="cb39-18"><a href="multiple1.html#cb39-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-19"><a href="multiple1.html#cb39-19" aria-hidden="true" tabindex="-1"></a><span class="co"># unique contribution of repair</span></span>
<span id="cb39-20"><a href="multiple1.html#cb39-20" aria-hidden="true" tabindex="-1"></a>BF_attention_clarity_repair <span class="sc">/</span> BF_attention_clarity</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] attention + clarity + repair : 81.00941 ±0%
## 
## Against denominator:
##   wellbeing ~ clarity + repair 
## ---
## Bayes factor type: BFlinearModel, JZS
## 
## Bayes factor analysis
## --------------
## [1] attention + clarity + repair : 3.836891 ±0%
## 
## Against denominator:
##   wellbeing ~ attention + repair 
## ---
## Bayes factor type: BFlinearModel, JZS
## 
## Bayes factor analysis
## --------------
## [1] attention + clarity + repair : 82.35924 ±0%
## 
## Against denominator:
##   wellbeing ~ attention + clarity 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p><br />
</p>
<p>Using <code>regressionBF()</code>:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="multiple1.html#cb41-1" aria-hidden="true" tabindex="-1"></a>all_BFs <span class="ot">&lt;-</span></span>
<span id="cb41-2"><a href="multiple1.html#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">regressionBF</span>(wellbeing <span class="sc">~</span> attention <span class="sc">+</span> clarity <span class="sc">+</span> repair, <span class="at">data =</span> <span class="fu">data.frame</span>(wellbeing_data))</span>
<span id="cb41-3"><a href="multiple1.html#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="multiple1.html#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># look at output</span></span>
<span id="cb41-5"><a href="multiple1.html#cb41-5" aria-hidden="true" tabindex="-1"></a>all_BFs</span>
<span id="cb41-6"><a href="multiple1.html#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="multiple1.html#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># unique contribution of attention</span></span>
<span id="cb41-8"><a href="multiple1.html#cb41-8" aria-hidden="true" tabindex="-1"></a>all_BFs[<span class="dv">7</span>] <span class="sc">/</span> all_BFs[<span class="dv">6</span>]</span>
<span id="cb41-9"><a href="multiple1.html#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="multiple1.html#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="co"># unique contribution of clarity</span></span>
<span id="cb41-11"><a href="multiple1.html#cb41-11" aria-hidden="true" tabindex="-1"></a>all_BFs[<span class="dv">7</span>] <span class="sc">/</span> all_BFs[<span class="dv">5</span>]</span>
<span id="cb41-12"><a href="multiple1.html#cb41-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-13"><a href="multiple1.html#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="co"># unique contribution of repair</span></span>
<span id="cb41-14"><a href="multiple1.html#cb41-14" aria-hidden="true" tabindex="-1"></a>all_BFs[<span class="dv">7</span>] <span class="sc">/</span> all_BFs[<span class="dv">4</span>]</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] attention                    : 4.759631 ±0%
## [2] clarity                      : 18.08091 ±0.01%
## [3] repair                       : 960.1706 ±0%
## [4] attention + clarity          : 874.9426 ±0%
## [5] attention + repair           : 18780.73 ±0%
## [6] clarity + repair             : 889.5214 ±0%
## [7] attention + clarity + repair : 72059.61 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS
## 
## Bayes factor analysis
## --------------
## [1] attention + clarity + repair : 81.00941 ±0%
## 
## Against denominator:
##   wellbeing ~ clarity + repair 
## ---
## Bayes factor type: BFlinearModel, JZS
## 
## Bayes factor analysis
## --------------
## [1] attention + clarity + repair : 3.836891 ±0%
## 
## Against denominator:
##   wellbeing ~ attention + repair 
## ---
## Bayes factor type: BFlinearModel, JZS
## 
## Bayes factor analysis
## --------------
## [1] attention + clarity + repair : 82.35924 ±0%
## 
## Against denominator:
##   wellbeing ~ attention + clarity 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p><br />
</p>
</div>
</div>
<p><br />
</p>
</div>
</div>
<div id="summary-of-key-points" class="section level2" number="2.7">
<h2><span class="header-section-number">2.7</span> Summary of key points</h2>
<ul>
<li><p>Predictors can be added to a model in <code>lm</code> using the <code>+</code> symbol</p>
<ul>
<li>e.g., <code>lm(wellbeing ~ worry + describing + predictor_3 + ....)</code></li>
</ul></li>
<li><p>Predictor variables are often <em>correlated</em> to some extent. This can affect the interpretation of individual predictor variables. Venn diagrams can help to understand the unique contributions of predictors</p></li>
<li><p>In multiple regression, it's important to understand that each predictor makes a contribution to explaining the outcome variable only <strong>after taking into account the other predictors in the model</strong>.</p></li>
<li><p>The Bayes Factor for a multiple regression model tells us how much more likely it is, compared to an intercept-only model.</p></li>
<li><p>To know whether there's evidence for the unique contribution of a predictor, we have to compare Bayes Factors for the more complex model (which includes it), versus the simpler model (in which the predictor is left out). i.e., <code>BF_more_complex_model / BF_simpler_model</code>.</p></li>
<li><p><strong>Multicollinearity</strong> exists when predictors are highly correlated (<em>r</em> above 0.8 or below -0.8) and should be avoided by dropping one of the predictors.</p></li>
</ul>
<p><br />
</p>
</div>
<div id="references-1" class="section level2" number="2.8">
<h2><span class="header-section-number">2.8</span> References</h2>
<p>Iani, L., Quinto, R. M., Lauriola, M., Crosta, M. L., &amp; Pozzi, G. (2019). Psychological well-being and distress in patients with generalized anxiety disorder: The roles of positive and negative functioning. <em>PloS one</em>, <em>14</em>(11), e0225646. <a href="https://doi.org/10.1371/journal.pone.0225646" class="uri">https://doi.org/10.1371/journal.pone.0225646</a></p>

</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="simple1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anova1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
