<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Session 4 Multiple regression: one continuous, one categorical | PSYC761 Data Analysis</title>
  <meta name="description" content="Course materials for PSYC761 2024" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Session 4 Multiple regression: one continuous, one categorical | PSYC761 Data Analysis" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course materials for PSYC761 2024" />
  <meta name="github-repo" content="datafluencyCB" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Session 4 Multiple regression: one continuous, one categorical | PSYC761 Data Analysis" />
  
  <meta name="twitter:description" content="Course materials for PSYC761 2024" />
  

<meta name="author" content="Chris Berry" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="anova1.html"/>
<link rel="next" href="multiple3.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />



<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="include/psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include/webex.css" type="text/css" />
<link rel="stylesheet" href="include/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PSYC761 Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="1" data-path="simple1.html"><a href="simple1.html"><i class="fa fa-check"></i><b>1</b> Simple Regression</a>
<ul>
<li class="chapter" data-level="1.1" data-path="simple1.html"><a href="simple1.html#overview-1"><i class="fa fa-check"></i><b>1.1</b> Overview</a></li>
<li class="chapter" data-level="1.2" data-path="simple1.html"><a href="simple1.html#worked-example"><i class="fa fa-check"></i><b>1.2</b> Worked Example</a></li>
<li class="chapter" data-level="1.3" data-path="simple1.html"><a href="simple1.html#predicting"><i class="fa fa-check"></i><b>1.3</b> Predicting</a></li>
<li class="chapter" data-level="1.4" data-path="simple1.html"><a href="simple1.html#residuals"><i class="fa fa-check"></i><b>1.4</b> Residuals</a></li>
<li class="chapter" data-level="1.5" data-path="simple1.html"><a href="simple1.html#evaluating-the-model"><i class="fa fa-check"></i><b>1.5</b> Evaluating the model</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="simple1.html"><a href="simple1.html#r2"><i class="fa fa-check"></i><b>1.5.1</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="1.5.2" data-path="simple1.html"><a href="simple1.html#bayes-factor"><i class="fa fa-check"></i><b>1.5.2</b> Bayes factor</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="simple1.html"><a href="simple1.html#exercise"><i class="fa fa-check"></i><b>1.6</b> Exercise</a></li>
<li class="chapter" data-level="1.7" data-path="simple1.html"><a href="simple1.html#further-exercises"><i class="fa fa-check"></i><b>1.7</b> Further Exercises</a></li>
<li class="chapter" data-level="1.8" data-path="simple1.html"><a href="simple1.html#going-further-p-values"><i class="fa fa-check"></i><b>1.8</b> Going further: <em>p</em>-values</a></li>
<li class="chapter" data-level="1.9" data-path="simple1.html"><a href="simple1.html#summary"><i class="fa fa-check"></i><b>1.9</b> Summary</a></li>
<li class="chapter" data-level="1.10" data-path="simple1.html"><a href="simple1.html#references"><i class="fa fa-check"></i><b>1.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="multiple1.html"><a href="multiple1.html"><i class="fa fa-check"></i><b>2</b> Multiple regression: multiple continuous predictors</a>
<ul>
<li class="chapter" data-level="2.1" data-path="multiple1.html"><a href="multiple1.html#overview-2"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="multiple1.html"><a href="multiple1.html#worked-example-1"><i class="fa fa-check"></i><b>2.2</b> Worked example</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="multiple1.html"><a href="multiple1.html#residual-plot"><i class="fa fa-check"></i><b>2.2.1</b> Residual plot</a></li>
<li class="chapter" data-level="2.2.2" data-path="multiple1.html"><a href="multiple1.html#evaluating-the-model-bayes-factor"><i class="fa fa-check"></i><b>2.2.2</b> Evaluating the model: Bayes factor</a></li>
<li class="chapter" data-level="2.2.3" data-path="multiple1.html"><a href="multiple1.html#evaluating-the-model-r2"><i class="fa fa-check"></i><b>2.2.3</b> Evaluating the model: R<sup>2</sup></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="multiple1.html"><a href="multiple1.html#understanding-the-contribution-of-individual-predictors"><i class="fa fa-check"></i><b>2.3</b> Understanding the contribution of individual predictors</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="multiple1.html"><a href="multiple1.html#r2-in-simple-vs.-multiple-regression"><i class="fa fa-check"></i><b>2.3.1</b> R<sup>2</sup> in simple vs. multiple regression</a></li>
<li class="chapter" data-level="2.3.2" data-path="multiple1.html"><a href="multiple1.html#venn-diagrams"><i class="fa fa-check"></i><b>2.3.2</b> Venn Diagrams</a></li>
<li class="chapter" data-level="2.3.3" data-path="multiple1.html"><a href="multiple1.html#using-bayes-factors-to-assess-the-unique-contribution-of-predictors"><i class="fa fa-check"></i><b>2.3.3</b> Using Bayes factors to assess the unique contribution of predictors</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="multiple1.html"><a href="multiple1.html#multicollinearity"><i class="fa fa-check"></i><b>2.4</b> Multicollinearity</a></li>
<li class="chapter" data-level="2.5" data-path="multiple1.html"><a href="multiple1.html#exercise-1"><i class="fa fa-check"></i><b>2.5</b> Exercise</a></li>
<li class="chapter" data-level="2.6" data-path="multiple1.html"><a href="multiple1.html#further-exercises-1"><i class="fa fa-check"></i><b>2.6</b> Further exercises</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="multiple1.html"><a href="multiple1.html#regressionbf"><i class="fa fa-check"></i><b>2.6.1</b> <code>regressionBF()</code></a></li>
<li class="chapter" data-level="2.6.2" data-path="multiple1.html"><a href="multiple1.html#predicting-new-data"><i class="fa fa-check"></i><b>2.6.2</b> Predicting new data</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="multiple1.html"><a href="multiple1.html#going-further-p-values-1"><i class="fa fa-check"></i><b>2.7</b> Going further: <em>p</em>-values</a></li>
<li class="chapter" data-level="2.8" data-path="multiple1.html"><a href="multiple1.html#summary-of-key-points"><i class="fa fa-check"></i><b>2.8</b> Summary of key points</a></li>
<li class="chapter" data-level="2.9" data-path="multiple1.html"><a href="multiple1.html#references-1"><i class="fa fa-check"></i><b>2.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="anova1.html"><a href="anova1.html"><i class="fa fa-check"></i><b>3</b> ANOVA: between-subjects designs</a>
<ul>
<li class="chapter" data-level="3.1" data-path="anova1.html"><a href="anova1.html#overview-3"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="anova1.html"><a href="anova1.html#one-way-between-subjects-anova"><i class="fa fa-check"></i><b>3.2</b> One-way between subjects ANOVA</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="anova1.html"><a href="anova1.html#worked-example-2"><i class="fa fa-check"></i><b>3.2.1</b> Worked Example</a></li>
<li class="chapter" data-level="3.2.2" data-path="anova1.html"><a href="anova1.html#read-in-the-data"><i class="fa fa-check"></i><b>3.2.2</b> Read in the data</a></li>
<li class="chapter" data-level="3.2.3" data-path="anova1.html"><a href="anova1.html#convert-the-independent-variable-to-a-factor"><i class="fa fa-check"></i><b>3.2.3</b> Convert the independent variable to a factor</a></li>
<li class="chapter" data-level="3.2.4" data-path="anova1.html"><a href="anova1.html#n-of-each-group"><i class="fa fa-check"></i><b>3.2.4</b> n of each group</a></li>
<li class="chapter" data-level="3.2.5" data-path="anova1.html"><a href="anova1.html#visualise-the-data"><i class="fa fa-check"></i><b>3.2.5</b> Visualise the data</a></li>
<li class="chapter" data-level="3.2.6" data-path="anova1.html"><a href="anova1.html#plot-the-means"><i class="fa fa-check"></i><b>3.2.6</b> Plot the means</a></li>
<li class="chapter" data-level="3.2.7" data-path="anova1.html"><a href="anova1.html#descriptives-mean-of-each-group"><i class="fa fa-check"></i><b>3.2.7</b> Descriptives: Mean of each group</a></li>
<li class="chapter" data-level="3.2.8" data-path="anova1.html"><a href="anova1.html#bayes-factor-1"><i class="fa fa-check"></i><b>3.2.8</b> Bayes factor</a></li>
<li class="chapter" data-level="3.2.9" data-path="anova1.html"><a href="anova1.html#r2-1"><i class="fa fa-check"></i><b>3.2.9</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="3.2.10" data-path="anova1.html"><a href="anova1.html#follow-up-tests"><i class="fa fa-check"></i><b>3.2.10</b> Follow-up tests</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="anova1.html"><a href="anova1.html#two-way-between-subjects-anova"><i class="fa fa-check"></i><b>3.3</b> Two-way between-subjects ANOVA</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="anova1.html"><a href="anova1.html#worked-example-3"><i class="fa fa-check"></i><b>3.3.1</b> Worked example</a></li>
<li class="chapter" data-level="3.3.2" data-path="anova1.html"><a href="anova1.html#read-in-the-data-1"><i class="fa fa-check"></i><b>3.3.2</b> Read in the data</a></li>
<li class="chapter" data-level="3.3.3" data-path="anova1.html"><a href="anova1.html#convert-the-independent-variables-to-factors"><i class="fa fa-check"></i><b>3.3.3</b> Convert the independent variables to factors</a></li>
<li class="chapter" data-level="3.3.4" data-path="anova1.html"><a href="anova1.html#n-in-each-group"><i class="fa fa-check"></i><b>3.3.4</b> n in each group</a></li>
<li class="chapter" data-level="3.3.5" data-path="anova1.html"><a href="anova1.html#visualise-the-data-1"><i class="fa fa-check"></i><b>3.3.5</b> Visualise the data</a></li>
<li class="chapter" data-level="3.3.6" data-path="anova1.html"><a href="anova1.html#plot-the-means-1"><i class="fa fa-check"></i><b>3.3.6</b> Plot the means</a></li>
<li class="chapter" data-level="3.3.7" data-path="anova1.html"><a href="anova1.html#bayes-factors"><i class="fa fa-check"></i><b>3.3.7</b> Bayes factors</a></li>
<li class="chapter" data-level="3.3.8" data-path="anova1.html"><a href="anova1.html#r2-2"><i class="fa fa-check"></i><b>3.3.8</b> R<sup>2</sup></a></li>
<li class="chapter" data-level="3.3.9" data-path="anova1.html"><a href="anova1.html#follow-up-comparisons"><i class="fa fa-check"></i><b>3.3.9</b> Follow-up comparisons</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="anova1.html"><a href="anova1.html#exercise-one-way"><i class="fa fa-check"></i><b>3.4</b> Exercise: one-way</a></li>
<li class="chapter" data-level="3.5" data-path="anova1.html"><a href="anova1.html#exercise-two-way"><i class="fa fa-check"></i><b>3.5</b> Exercise: two-way</a></li>
<li class="chapter" data-level="3.6" data-path="anova1.html"><a href="anova1.html#summary-1"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
<li class="chapter" data-level="3.7" data-path="anova1.html"><a href="anova1.html#references-2"><i class="fa fa-check"></i><b>3.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multiple2.html"><a href="multiple2.html"><i class="fa fa-check"></i><b>4</b> Multiple regression: one continuous, one categorical</a>
<ul>
<li class="chapter" data-level="4.1" data-path="multiple2.html"><a href="multiple2.html#overview-4"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="multiple2.html"><a href="multiple2.html#worked-example-4"><i class="fa fa-check"></i><b>4.2</b> Worked example</a></li>
<li class="chapter" data-level="4.3" data-path="multiple2.html"><a href="multiple2.html#read-in-the-data-2"><i class="fa fa-check"></i><b>4.3</b> Read in the data</a></li>
<li class="chapter" data-level="4.4" data-path="multiple2.html"><a href="multiple2.html#visualise-the-data-2"><i class="fa fa-check"></i><b>4.4</b> Visualise the data</a></li>
<li class="chapter" data-level="4.5" data-path="multiple2.html"><a href="multiple2.html#evidence-for-the-interaction"><i class="fa fa-check"></i><b>4.5</b> Evidence for the interaction</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="multiple2.html"><a href="multiple2.html#model-without-the-interaction"><i class="fa fa-check"></i><b>4.5.1</b> Model without the interaction</a></li>
<li class="chapter" data-level="4.5.2" data-path="multiple2.html"><a href="multiple2.html#model-with-the-interaction"><i class="fa fa-check"></i><b>4.5.2</b> Model with the interaction</a></li>
<li class="chapter" data-level="4.5.3" data-path="multiple2.html"><a href="multiple2.html#compare-the-model-with-and-without-the-interaction"><i class="fa fa-check"></i><b>4.5.3</b> Compare the model with and without the interaction</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="multiple2.html"><a href="multiple2.html#simple-slopes-analysis"><i class="fa fa-check"></i><b>4.6</b> Simple slopes analysis</a></li>
<li class="chapter" data-level="4.7" data-path="multiple2.html"><a href="multiple2.html#exercises"><i class="fa fa-check"></i><b>4.7</b> Exercises</a></li>
<li class="chapter" data-level="4.8" data-path="multiple2.html"><a href="multiple2.html#further-exercise"><i class="fa fa-check"></i><b>4.8</b> Further exercise</a></li>
<li class="chapter" data-level="4.9" data-path="multiple2.html"><a href="multiple2.html#further-knowledge"><i class="fa fa-check"></i><b>4.9</b> Further knowledge</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="multiple2.html"><a href="multiple2.html#moderation"><i class="fa fa-check"></i><b>4.9.1</b> Moderation</a></li>
<li class="chapter" data-level="4.9.2" data-path="multiple2.html"><a href="multiple2.html#coefficients"><i class="fa fa-check"></i><b>4.9.2</b> Coefficients</a></li>
<li class="chapter" data-level="4.9.3" data-path="multiple2.html"><a href="multiple2.html#centering"><i class="fa fa-check"></i><b>4.9.3</b> Centering</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="multiple2.html"><a href="multiple2.html#summary-2"><i class="fa fa-check"></i><b>4.10</b> Summary</a></li>
<li class="chapter" data-level="4.11" data-path="multiple2.html"><a href="multiple2.html#references-3"><i class="fa fa-check"></i><b>4.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="multiple3.html"><a href="multiple3.html"><i class="fa fa-check"></i><b>5</b> Multiple regression: hierarchical regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="multiple3.html"><a href="multiple3.html#overview-5"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="multiple3.html"><a href="multiple3.html#worked-example-1-wellbeing"><i class="fa fa-check"></i><b>5.2</b> Worked example 1: wellbeing</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="multiple3.html"><a href="multiple3.html#read-in-the-data-3"><i class="fa fa-check"></i><b>5.2.1</b> Read in the data</a></li>
<li class="chapter" data-level="5.2.2" data-path="multiple3.html"><a href="multiple3.html#visualisation"><i class="fa fa-check"></i><b>5.2.2</b> Visualisation</a></li>
<li class="chapter" data-level="5.2.3" data-path="multiple3.html"><a href="multiple3.html#correlations"><i class="fa fa-check"></i><b>5.2.3</b> Correlations</a></li>
<li class="chapter" data-level="5.2.4" data-path="multiple3.html"><a href="multiple3.html#hierarchical-regression"><i class="fa fa-check"></i><b>5.2.4</b> Hierarchical regression</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="multiple3.html"><a href="multiple3.html#exercise-1-1"><i class="fa fa-check"></i><b>5.3</b> Exercise 1</a></li>
<li class="chapter" data-level="5.4" data-path="multiple3.html"><a href="multiple3.html#worked-exercise-2-controlling-for-categorical-variables"><i class="fa fa-check"></i><b>5.4</b> Worked Exercise 2: Controlling for categorical variables</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="multiple3.html"><a href="multiple3.html#visualisation-1"><i class="fa fa-check"></i><b>5.4.1</b> Visualisation</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="multiple3.html"><a href="multiple3.html#exercise-2"><i class="fa fa-check"></i><b>5.5</b> Exercise 2</a></li>
<li class="chapter" data-level="5.6" data-path="multiple3.html"><a href="multiple3.html#further-knowledge-and-exercises"><i class="fa fa-check"></i><b>5.6</b> Further knowledge and exercises</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="multiple3.html"><a href="multiple3.html#standardised-coefficients"><i class="fa fa-check"></i><b>5.6.1</b> Standardised Coefficients</a></li>
<li class="chapter" data-level="5.6.2" data-path="multiple3.html"><a href="multiple3.html#prediction"><i class="fa fa-check"></i><b>5.6.2</b> Prediction</a></li>
<li class="chapter" data-level="5.6.3" data-path="multiple3.html"><a href="multiple3.html#residuals-1"><i class="fa fa-check"></i><b>5.6.3</b> Residuals</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="multiple3.html"><a href="multiple3.html#summary-3"><i class="fa fa-check"></i><b>5.7</b> Summary</a></li>
<li class="chapter" data-level="5.8" data-path="multiple3.html"><a href="multiple3.html#references-4"><i class="fa fa-check"></i><b>5.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="anova2.html"><a href="anova2.html"><i class="fa fa-check"></i><b>6</b> ANOVA: Repeated measures</a>
<ul>
<li class="chapter" data-level="6.1" data-path="anova2.html"><a href="anova2.html#overview-6"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="anova2.html"><a href="anova2.html#one-way-repeated-measures-anova"><i class="fa fa-check"></i><b>6.2</b> One-way repeated measures ANOVA</a></li>
<li class="chapter" data-level="6.3" data-path="anova2.html"><a href="anova2.html#long-format-data"><i class="fa fa-check"></i><b>6.3</b> Long format data</a></li>
<li class="chapter" data-level="6.4" data-path="anova2.html"><a href="anova2.html#worked-example-5"><i class="fa fa-check"></i><b>6.4</b> Worked Example</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="anova2.html"><a href="anova2.html#read-in-the-data-4"><i class="fa fa-check"></i><b>6.4.1</b> Read in the data</a></li>
<li class="chapter" data-level="6.4.2" data-path="anova2.html"><a href="anova2.html#convert-the-data-to-long-format"><i class="fa fa-check"></i><b>6.4.2</b> Convert the data to long format</a></li>
<li class="chapter" data-level="6.4.3" data-path="anova2.html"><a href="anova2.html#convert-the-participant-and-the-categorical-variable-to-factors"><i class="fa fa-check"></i><b>6.4.3</b> Convert the participant and the categorical variable to factors</a></li>
<li class="chapter" data-level="6.4.4" data-path="anova2.html"><a href="anova2.html#visualise-the-data-3"><i class="fa fa-check"></i><b>6.4.4</b> Visualise the data</a></li>
<li class="chapter" data-level="6.4.5" data-path="anova2.html"><a href="anova2.html#plot-the-means-2"><i class="fa fa-check"></i><b>6.4.5</b> Plot the means</a></li>
<li class="chapter" data-level="6.4.6" data-path="anova2.html"><a href="anova2.html#descriptives-mean-of-each-condition"><i class="fa fa-check"></i><b>6.4.6</b> Descriptives: Mean of each condition</a></li>
<li class="chapter" data-level="6.4.7" data-path="anova2.html"><a href="anova2.html#bayes-factor-2"><i class="fa fa-check"></i><b>6.4.7</b> Bayes factor</a></li>
<li class="chapter" data-level="6.4.8" data-path="anova2.html"><a href="anova2.html#follow-up-tests-1"><i class="fa fa-check"></i><b>6.4.8</b> Follow-up tests</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="anova2.html"><a href="anova2.html#two-way-within-subjects-anova"><i class="fa fa-check"></i><b>6.5</b> Two-way within subjects ANOVA</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="anova2.html"><a href="anova2.html#worked-example-6"><i class="fa fa-check"></i><b>6.5.1</b> Worked Example</a></li>
<li class="chapter" data-level="6.5.2" data-path="anova2.html"><a href="anova2.html#read-in-the-data-5"><i class="fa fa-check"></i><b>6.5.2</b> Read in the data</a></li>
<li class="chapter" data-level="6.5.3" data-path="anova2.html"><a href="anova2.html#visualise-the-data-4"><i class="fa fa-check"></i><b>6.5.3</b> Visualise the data</a></li>
<li class="chapter" data-level="6.5.4" data-path="anova2.html"><a href="anova2.html#plot-the-means-3"><i class="fa fa-check"></i><b>6.5.4</b> Plot the means</a></li>
<li class="chapter" data-level="6.5.5" data-path="anova2.html"><a href="anova2.html#descriptive-statistics---mean"><i class="fa fa-check"></i><b>6.5.5</b> Descriptive statistics - mean</a></li>
<li class="chapter" data-level="6.5.6" data-path="anova2.html"><a href="anova2.html#convert-participant-and-categorical-variables-to-factors"><i class="fa fa-check"></i><b>6.5.6</b> Convert participant and categorical variables to factors</a></li>
<li class="chapter" data-level="6.5.7" data-path="anova2.html"><a href="anova2.html#bayes-factor-3"><i class="fa fa-check"></i><b>6.5.7</b> Bayes factor</a></li>
<li class="chapter" data-level="6.5.8" data-path="anova2.html"><a href="anova2.html#follow-up-comparisons-1"><i class="fa fa-check"></i><b>6.5.8</b> Follow up comparisons</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="anova2.html"><a href="anova2.html#exercise-two-way-mixed-anova"><i class="fa fa-check"></i><b>6.6</b> Exercise: two-way mixed ANOVA</a></li>
<li class="chapter" data-level="6.7" data-path="anova2.html"><a href="anova2.html#further-knowledge---within-subject-errorbars"><i class="fa fa-check"></i><b>6.7</b> Further knowledge - within-subject errorbars</a></li>
<li class="chapter" data-level="6.8" data-path="anova2.html"><a href="anova2.html#further-knowledge---r-squared"><i class="fa fa-check"></i><b>6.8</b> Further knowledge - R-squared</a></li>
<li class="chapter" data-level="6.9" data-path="anova2.html"><a href="anova2.html#summary-4"><i class="fa fa-check"></i><b>6.9</b> Summary</a></li>
<li class="chapter" data-level="6.10" data-path="anova2.html"><a href="anova2.html#references-5"><i class="fa fa-check"></i><b>6.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="prepost.html"><a href="prepost.html"><i class="fa fa-check"></i><b>7</b> Pre-post data, clinically significant change</a>
<ul>
<li class="chapter" data-level="7.1" data-path="prepost.html"><a href="prepost.html#overview-7"><i class="fa fa-check"></i><b>7.1</b> Overview</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="prepost.html"><a href="prepost.html#worked-example-7"><i class="fa fa-check"></i><b>7.1.1</b> Worked example</a></li>
<li class="chapter" data-level="7.1.2" data-path="prepost.html"><a href="prepost.html#read-in-the-data-6"><i class="fa fa-check"></i><b>7.1.2</b> Read in the data</a></li>
<li class="chapter" data-level="7.1.3" data-path="prepost.html"><a href="prepost.html#plot-the-means-4"><i class="fa fa-check"></i><b>7.1.3</b> Plot the means</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="prepost.html"><a href="prepost.html#approach-1---difference-scores"><i class="fa fa-check"></i><b>7.2</b> Approach 1 - Difference scores</a></li>
<li class="chapter" data-level="7.3" data-path="prepost.html"><a href="prepost.html#approach-2---mixed-anova"><i class="fa fa-check"></i><b>7.3</b> Approach 2 - Mixed ANOVA</a></li>
<li class="chapter" data-level="7.4" data-path="prepost.html"><a href="prepost.html#approach-3---ancova"><i class="fa fa-check"></i><b>7.4</b> Approach 3 - ANCOVA</a></li>
<li class="chapter" data-level="7.5" data-path="prepost.html"><a href="prepost.html#which-approach-should-you-use"><i class="fa fa-check"></i><b>7.5</b> Which approach should you use?</a></li>
<li class="chapter" data-level="7.6" data-path="prepost.html"><a href="prepost.html#clinical-significance"><i class="fa fa-check"></i><b>7.6</b> Clinical Significance</a></li>
<li class="chapter" data-level="7.7" data-path="prepost.html"><a href="prepost.html#exercises-1"><i class="fa fa-check"></i><b>7.7</b> Exercises</a></li>
<li class="chapter" data-level="7.8" data-path="prepost.html"><a href="prepost.html#further-knowledge-1"><i class="fa fa-check"></i><b>7.8</b> Further Knowledge</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="prepost.html"><a href="prepost.html#reliable-change-rc-index"><i class="fa fa-check"></i><b>7.8.1</b> Reliable Change (RC) index</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="prepost.html"><a href="prepost.html#summary-5"><i class="fa fa-check"></i><b>7.9</b> Summary</a></li>
<li class="chapter" data-level="7.10" data-path="prepost.html"><a href="prepost.html#references-6"><i class="fa fa-check"></i><b>7.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="mixed.html"><a href="mixed.html"><i class="fa fa-check"></i><b>8</b> Mixed Models</a>
<ul>
<li class="chapter" data-level="8.1" data-path="mixed.html"><a href="mixed.html#overview-8"><i class="fa fa-check"></i><b>8.1</b> Overview</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="mixed.html"><a href="mixed.html#worked-example-8"><i class="fa fa-check"></i><b>8.1.1</b> Worked example</a></li>
<li class="chapter" data-level="8.1.2" data-path="mixed.html"><a href="mixed.html#read-in-the-data-7"><i class="fa fa-check"></i><b>8.1.2</b> Read in the data</a></li>
<li class="chapter" data-level="8.1.3" data-path="mixed.html"><a href="mixed.html#plot-the-means-5"><i class="fa fa-check"></i><b>8.1.3</b> Plot the means</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="mixed.html"><a href="mixed.html#approach-1---difference-scores-1"><i class="fa fa-check"></i><b>8.2</b> Approach 1 - Difference scores</a></li>
<li class="chapter" data-level="8.3" data-path="mixed.html"><a href="mixed.html#approach-2---mixed-anova-1"><i class="fa fa-check"></i><b>8.3</b> Approach 2 - Mixed ANOVA</a></li>
<li class="chapter" data-level="8.4" data-path="mixed.html"><a href="mixed.html#approach-3---ancova-1"><i class="fa fa-check"></i><b>8.4</b> Approach 3 - ANCOVA</a></li>
<li class="chapter" data-level="8.5" data-path="mixed.html"><a href="mixed.html#which-approach-should-you-use-1"><i class="fa fa-check"></i><b>8.5</b> Which approach should you use?</a></li>
<li class="chapter" data-level="8.6" data-path="mixed.html"><a href="mixed.html#clinical-significance-1"><i class="fa fa-check"></i><b>8.6</b> Clinical Significance</a></li>
<li class="chapter" data-level="8.7" data-path="mixed.html"><a href="mixed.html#exercises-2"><i class="fa fa-check"></i><b>8.7</b> Exercises</a></li>
<li class="chapter" data-level="8.8" data-path="mixed.html"><a href="mixed.html#further-knowledge-2"><i class="fa fa-check"></i><b>8.8</b> Further Knowledge</a>
<ul>
<li class="chapter" data-level="8.8.1" data-path="mixed.html"><a href="mixed.html#reliable-change-rc-index-1"><i class="fa fa-check"></i><b>8.8.1</b> Reliable Change (RC) index</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="mixed.html"><a href="mixed.html#summary-6"><i class="fa fa-check"></i><b>8.9</b> Summary</a></li>
<li class="chapter" data-level="8.10" data-path="mixed.html"><a href="mixed.html#references-7"><i class="fa fa-check"></i><b>8.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="assessment2024.html"><a href="assessment2024.html"><i class="fa fa-check"></i><b>9</b> Data Analysis Assessment 2024</a></li>
<li class="chapter" data-level="10" data-path="faqs.html"><a href="faqs.html"><i class="fa fa-check"></i><b>10</b> FAQs</a>
<ul>
<li class="chapter" data-level="10.1" data-path="faqs.html"><a href="faqs.html#e-meaning"><i class="fa fa-check"></i><b>10.1</b> What does it mean if RStudio prints out "e-" next to a number?</a></li>
<li class="chapter" data-level="10.2" data-path="faqs.html"><a href="faqs.html#how-can-i-find-out-more-about-a-particular-function-so-i-can-explore-its-settings-etc."><i class="fa fa-check"></i><b>10.2</b> How can I find out more about a particular function, so I can explore its settings etc.?</a></li>
<li class="chapter" data-level="10.3" data-path="faqs.html"><a href="faqs.html#how-do-i-import-a-data-file-to-r-studio"><i class="fa fa-check"></i><b>10.3</b> How do I import a data file to R Studio?</a></li>
<li class="chapter" data-level="10.4" data-path="faqs.html"><a href="faqs.html#how-should-i-write-up-the-report"><i class="fa fa-check"></i><b>10.4</b> How should I write up the report?</a></li>
<li class="chapter" data-level="10.5" data-path="faqs.html"><a href="faqs.html#after-downloading-my-.rmd-file-to-my-computer-how-do-i-open-it-again-in-rstudio"><i class="fa fa-check"></i><b>10.5</b> After downloading my .Rmd file to my computer, how do I open it again in RStudio?</a></li>
<li class="chapter" data-level="10.6" data-path="faqs.html"><a href="faqs.html#on-the-word-count-are-figure-captions-included"><i class="fa fa-check"></i><b>10.6</b> On the word count, are figure captions included?</a></li>
<li class="chapter" data-level="10.7" data-path="faqs.html"><a href="faqs.html#should-i-make-code-visible-in-my-html-report"><i class="fa fa-check"></i><b>10.7</b> Should I make code visible in my html report?</a></li>
<li class="chapter" data-level="10.8" data-path="faqs.html"><a href="faqs.html#do-i-need-to-include-references"><i class="fa fa-check"></i><b>10.8</b> Do I need to include references?</a></li>
<li class="chapter" data-level="10.9" data-path="faqs.html"><a href="faqs.html#can-there-be-overlap-in-the-variables-used-in-each-question"><i class="fa fa-check"></i><b>10.9</b> Can there be overlap in the variables used in each question?</a></li>
<li class="chapter" data-level="10.10" data-path="faqs.html"><a href="faqs.html#do-we-have-to-include-a-certain-number-of-variables-to-achieve-a-good-grade"><i class="fa fa-check"></i><b>10.10</b> Do we have to include a certain number of variables to achieve a good grade?</a></li>
<li class="chapter" data-level="10.11" data-path="faqs.html"><a href="faqs.html#can-i-include-more-than-one-figure"><i class="fa fa-check"></i><b>10.11</b> Can I include more than one figure?</a></li>
<li class="chapter" data-level="10.12" data-path="faqs.html"><a href="faqs.html#can-i-include-categorical-predictor-variables-in-a-hierarchical-regression"><i class="fa fa-check"></i><b>10.12</b> Can I include categorical predictor variables in a hierarchical regression?</a></li>
<li class="chapter" data-level="10.13" data-path="faqs.html"><a href="faqs.html#how-do-i-apply-for-extenuating-circumstances"><i class="fa fa-check"></i><b>10.13</b> How do I apply for extenuating circumstances?</a></li>
<li class="chapter" data-level="10.14" data-path="faqs.html"><a href="faqs.html#can-a-book-a-slot-in-your-office-hours"><i class="fa fa-check"></i><b>10.14</b> Can a book a slot in your office hours?</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>11</b> Reading</a>
<ul>
<li class="chapter" data-level="11.1" data-path="reading.html"><a href="reading.html#recommended-texts-and-resources"><i class="fa fa-check"></i><b>11.1</b> Recommended texts and resources</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="reading.html"><a href="reading.html#library-books"><i class="fa fa-check"></i><b>11.1.1</b> Library books</a></li>
<li class="chapter" data-level="11.1.2" data-path="reading.html"><a href="reading.html#electronic-resources-and-books"><i class="fa fa-check"></i><b>11.1.2</b> Electronic resources and books</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSYC761 Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple2" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Session 4</span> Multiple regression: one continuous, one categorical<a href="multiple2.html#multiple2" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><em>Chris Berry</em><br />
<em>2024</em></p>
<!--
commented text
commented text
-->
<style>
div.exercise { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<style>
div.tip { background-color:#D5F5E3; border-radius: 5px; padding: 20px;}
</style>
<div id="overview-4" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Overview<a href="multiple2.html#overview-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><strong>Slides</strong> from the lecture part of the session: <a href="slides/PSYC761_L4_MultipleRegression2.pptx">Download</a></li>
<li><strong>Slides</strong> for <a href="slides/PSYC761_Rmd_Support.pptx">Rmd support</a></li>
<li><strong>R Studio online</strong> <a href="https://psyrstudio.plymouth.ac.uk/">Access here using University log-in</a></li>
</ul>
<p><br />
</p>
<p>So far we have looked at <a href="simple1.html#simple1">simple</a> and <a href="multiple1.html#multiple1">multiple regression</a> with <em>continuous variables</em>. (And in the last session, we saw that between-subjects <a href="anova1.html#anova1">ANOVA</a> was equivalent to a multiple regression in which all the predictors are categorical.)</p>
<p>Here, we look at multiple regression with a mixture of continuous and categorical predictors. Specifically, one predictor is <em>continuous</em>, and the other is a <em>dichotomous categorical variable</em> (i.e., made up of two levels or groups).</p>
<p>This type of analysis can be used to see whether the relationship between two variables is the same or different across groups of individuals. For example, adherence to a particular treatment (e.g., CBT) may be associated with attitudes towards the efficacy of the treatment, but the nature of the association may differ according to the type of psychological disorder a person has (e.g., depressed vs. not depressed).</p>
<p>Thus, in this type of analysis, in addition to looking at the ability of individual predictors to explain an outcome variable, we're able to look at their <em>combined</em> effect in explaining the outcome. This is referred to as an <strong>interaction effect</strong>. The interaction can tell us whether the relationship between one of the predictors and the outcome differs as a function of the levels of the other predictor variable.</p>
</div>
<div id="worked-example-4" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Worked example<a href="multiple2.html#worked-example-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Scientists often research things that are of personal interest to themselves. Do we trust the researcher more when they have some personal investment in what they are researching? Altenmuller et al. (2021) looked at whether participants' trust in the researcher is related to 1) whether they are told that the researcher is personally affected by the research or not affected by their research, and 2) the participant's attitude towards the research topic.</p>
<p>The data from Altenmuller et al.'s (2021) study (Experiment 2) are stored at the link below.</p>
<p><a href="https://raw.githubusercontent.com/chrisjberry/Teaching/master/4_trust_data.csv" class="uri">https://raw.githubusercontent.com/chrisjberry/Teaching/master/4_trust_data.csv</a></p>
<p>The key variables:</p>
<ul>
<li><code>trustworthiness</code>: how trustworthy the participant finds the researcher. Higher scores indicate higher levels of trustworthiness.</li>
<li><code>attitude</code>: the participant's attitude towards the research topic. Higher scores indicate a more positive attitude.</li>
<li><code>group</code>: whether participants were told that the researcher is personally <code>affected</code> or <code>not_affected</code> by their own research.</li>
</ul>
<div class="webex-solution">
<button>
More about the data
</button>
<p>The data were made publicly available by the researchers and have been pre-processed (using the researcher's open R code). Only a subset of the data is used here for teaching purposes; variable names have been changed for clarity.</p>
</div>
<p><br />
</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-1" class="exercise"><strong>Exercise 4.1  </strong></span>Design check.</p>
<ul>
<li><p>What is the outcome variable in this design? <select class='webex-select'><option value='blank'></option><option value=''>attitude</option><option value='answer'>trustworthiness</option><option value=''>group</option></select></p></li>
<li><p>What is the nature of the outcome variable? <select class='webex-select'><option value='blank'></option><option value=''>categorical</option><option value='answer'>continuous</option></select></p></li>
<li><p>What is the name of the continuous predictor variable? <select class='webex-select'><option value='blank'></option><option value=''>group</option><option value='answer'>attitude</option><option value=''>trustworthiness</option></select></p></li>
<li><p>What is the name of the categorical predictor variable? <select class='webex-select'><option value='blank'></option><option value='answer'>group</option><option value=''>attitude</option><option value=''>trustworthiness</option></select></p></li>
<li><p>How many levels of <code>group</code> are there? <select class='webex-select'><option value='blank'></option><option value=''>1</option><option value='answer'>2</option><option value=''>3</option></select></p></li>
<li><p>When a variable has two levels it is called a <select class='webex-select'><option value='blank'></option><option value=''>continuous</option><option value='answer'>dichotomous</option><option value=''>quantitative</option></select> variable.</p></li>
</ul>
</div>
<p><br />
</p>
</div>
<div id="read-in-the-data-2" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Read in the data<a href="multiple2.html#read-in-the-data-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Read in the data to <code>trust_data</code></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="multiple2.html#cb1-1" tabindex="-1"></a><span class="co"># ensure tidyverse is loaded</span></span>
<span id="cb1-2"><a href="multiple2.html#cb1-2" tabindex="-1"></a><span class="co"># library(tidyverse)</span></span>
<span id="cb1-3"><a href="multiple2.html#cb1-3" tabindex="-1"></a></span>
<span id="cb1-4"><a href="multiple2.html#cb1-4" tabindex="-1"></a><span class="co"># read in the data</span></span>
<span id="cb1-5"><a href="multiple2.html#cb1-5" tabindex="-1"></a>trust_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://raw.githubusercontent.com/chrisjberry/Teaching/master/4_trust_data.csv&#39;</span>)</span>
<span id="cb1-6"><a href="multiple2.html#cb1-6" tabindex="-1"></a></span>
<span id="cb1-7"><a href="multiple2.html#cb1-7" tabindex="-1"></a><span class="co"># look at the data</span></span>
<span id="cb1-8"><a href="multiple2.html#cb1-8" tabindex="-1"></a>trust_data <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr class="header">
<th align="right">ppt</th>
<th align="left">group</th>
<th align="right">attitude</th>
<th align="right">trustworthiness</th>
<th align="right">credibility</th>
<th align="right">evaluation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">not_affected</td>
<td align="right">5.714286</td>
<td align="right">4.428571</td>
<td align="right">4.428571</td>
<td align="right">2.583333</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">affected</td>
<td align="right">3.142857</td>
<td align="right">4.285714</td>
<td align="right">4.428571</td>
<td align="right">3.250000</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">not_affected</td>
<td align="right">5.285714</td>
<td align="right">4.428571</td>
<td align="right">4.428571</td>
<td align="right">2.750000</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="left">not_affected</td>
<td align="right">4.428571</td>
<td align="right">4.642857</td>
<td align="right">3.857143</td>
<td align="right">2.416667</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="left">affected</td>
<td align="right">6.000000</td>
<td align="right">6.000000</td>
<td align="right">5.285714</td>
<td align="right">2.333333</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="left">not_affected</td>
<td align="right">3.642857</td>
<td align="right">5.500000</td>
<td align="right">4.571429</td>
<td align="right">2.500000</td>
</tr>
</tbody>
</table>
</div>
<p><br />
</p>
</div>
<div id="visualise-the-data-2" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Visualise the data<a href="multiple2.html#visualise-the-data-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Use a scatterplot to look at the relationship between <code>trustworthiness</code>, <code>attitude</code> and <code>group</code>. Use different colours for each <code>group</code> by specifying <code>colour = group</code> in <code>aes()</code>:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="multiple2.html#cb2-1" tabindex="-1"></a>trust_data <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="multiple2.html#cb2-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> attitude, <span class="at">y =</span> trustworthiness, <span class="at">colour =</span> group )) <span class="sc">+</span></span>
<span id="cb2-3"><a href="multiple2.html#cb2-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb2-4"><a href="multiple2.html#cb2-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="multiple2.html#cb2-5" tabindex="-1"></a>  <span class="fu">theme_light</span>() </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="04_multiple_regression_2_files/figure-html/unnamed-chunk-3-1.png" alt="Trustworthiness vs. participant attitude to research" width="75%" />
<p class="caption">
Figure 4.1: Trustworthiness vs. participant attitude to research
</p>
</div>
<div class="exercise">
<p><span id="exr:unlabeled-div-2" class="exercise"><strong>Exercise 4.2  </strong></span>Visual inspection of the scatterplot</p>
<p>Does the relationship between <code>attitude</code> and <code>trustworthiness</code> appear to be the same within each <code>group</code>? <select class='webex-select'><option value='blank'></option><option value=''>yes</option><option value='answer'>no</option></select></p>
<p><br />
</p>
<p>Within the group that were told that the researcher was personally <code>affected</code> by their research:</p>
<ul>
<li>The association between <code>attitude</code> and <code>trustworthiness</code> appears to be <select class='webex-select'><option value='blank'></option><option value=''>negative</option><option value='answer'>positive</option></select></li>
<li>A more positive attitude towards the research topic tends to be associated with <select class='webex-select'><option value='blank'></option><option value=''>lower</option><option value=''>no change</option><option value='answer'>higher</option></select> values of <code>trustworthiness</code>.</li>
</ul>
<p><br />
</p>
<p>Within the group that were told that the researcher was personally <code>not_affected</code> by their research:</p>
<ul>
<li>The association between <code>attitude</code> and <code>trustworthiness</code> appears to be <select class='webex-select'><option value='blank'></option><option value='answer'>negative</option><option value=''>positive</option></select></li>
<li>A more positive attitude towards the research topic tends to be associated with <select class='webex-select'><option value='blank'></option><option value='answer'>lower</option><option value=''>no change</option><option value=''>higher</option></select> values of <code>trustworthiness</code>.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Go further with ggplot
</button>
<p>The scatterplot can be improved through further customisation.</p>
<p>For example, to change the x- and y- labels, add the code:</p>
<p><code>+ xlab("Participants' attitude to the research")</code><br />
<code>+ ylab("Trustworthiness of researcher")</code></p>
<p>Feel free to customise the plot further if you feel it can be improved!</p>
</div>
<div class="webex-solution">
<button>
Further inspection
</button>
<p>It is good practice to inspect the distributions of the data prior to analysis, for example, with <code>geom_histogram()</code> or <code>geom_density()</code>. We can check if the data appear normally distributed, or positively or negatively skewed. We can also check for outliers using <code>geom_boxplot()</code>. Get to know your data!</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="multiple2.html#cb3-1" tabindex="-1"></a><span class="co"># look at the distribution of trustworthiness</span></span>
<span id="cb3-2"><a href="multiple2.html#cb3-2" tabindex="-1"></a>trust_data <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="multiple2.html#cb3-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(trustworthiness)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="multiple2.html#cb3-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() </span>
<span id="cb3-5"><a href="multiple2.html#cb3-5" tabindex="-1"></a></span>
<span id="cb3-6"><a href="multiple2.html#cb3-6" tabindex="-1"></a><span class="co"># look at the distribution of attitude</span></span>
<span id="cb3-7"><a href="multiple2.html#cb3-7" tabindex="-1"></a>trust_data <span class="sc">%&gt;%</span> </span>
<span id="cb3-8"><a href="multiple2.html#cb3-8" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(attitude)) <span class="sc">+</span></span>
<span id="cb3-9"><a href="multiple2.html#cb3-9" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() </span>
<span id="cb3-10"><a href="multiple2.html#cb3-10" tabindex="-1"></a></span>
<span id="cb3-11"><a href="multiple2.html#cb3-11" tabindex="-1"></a><span class="co"># obtain n in affected &amp; not_affected groups</span></span>
<span id="cb3-12"><a href="multiple2.html#cb3-12" tabindex="-1"></a>trust_data <span class="sc">%&gt;%</span> </span>
<span id="cb3-13"><a href="multiple2.html#cb3-13" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb3-14"><a href="multiple2.html#cb3-14" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div>
</div>
<p><br />
</p>
</div>
<div id="evidence-for-the-interaction" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Evidence for the interaction<a href="multiple2.html#evidence-for-the-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>An interaction between the <code>attitude</code> and <code>group</code> predictors is suggested by the scatterplot. That is, the association between <code>trustworthiness</code> and <code>attitude</code> appears to be different in the <code>affected</code> and <code>non_affected</code> groups. We may therefore want to include the interaction term in our multiple regression model and determine whether we have evidence for the interaction or not using Bayes factors.</p>
<p>We'll do this in three steps:</p>
<ul>
<li><ol style="list-style-type: decimal">
<li>Specify the model <em>without</em> the interaction</li>
</ol></li>
<li><ol start="2" style="list-style-type: decimal">
<li>Specify the model <em>with</em> the interaction</li>
</ol></li>
<li><ol start="3" style="list-style-type: decimal">
<li>Compare the model <em>with</em> and <em>without</em> the interaction</li>
</ol></li>
</ul>
<p><br />
</p>
<div id="model-without-the-interaction" class="section level3 hasAnchor" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Model without the interaction<a href="multiple2.html#model-without-the-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The model without an interaction looks like a typical multiple regression model with two predictors (from Session 2):</p>
<p><code>model &lt;- lm(outcome ~ predictor_1 + predictor_2, data = mydata)</code></p>
<p>As we did in the previous session, we need to also convert the categorical variable (<code>group</code>) to a <code>factor()</code> to ensure it's treated as categorical by R.</p>
<p>Thus, for our data:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="multiple2.html#cb4-1" tabindex="-1"></a><span class="co"># Convert group to a factor</span></span>
<span id="cb4-2"><a href="multiple2.html#cb4-2" tabindex="-1"></a>trust_data <span class="ot">&lt;-</span> trust_data <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">group =</span> <span class="fu">factor</span>(group))</span>
<span id="cb4-3"><a href="multiple2.html#cb4-3" tabindex="-1"></a></span>
<span id="cb4-4"><a href="multiple2.html#cb4-4" tabindex="-1"></a><span class="co"># Specify the model without the interaction</span></span>
<span id="cb4-5"><a href="multiple2.html#cb4-5" tabindex="-1"></a>without_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(trustworthiness <span class="sc">~</span> attitude <span class="sc">+</span> group, </span>
<span id="cb4-6"><a href="multiple2.html#cb4-6" tabindex="-1"></a>                          <span class="at">data =</span> trust_data)</span>
<span id="cb4-7"><a href="multiple2.html#cb4-7" tabindex="-1"></a></span>
<span id="cb4-8"><a href="multiple2.html#cb4-8" tabindex="-1"></a><span class="co"># R² for the model</span></span>
<span id="cb4-9"><a href="multiple2.html#cb4-9" tabindex="-1"></a><span class="co"># load the broom package if you haven&#39;t already</span></span>
<span id="cb4-10"><a href="multiple2.html#cb4-10" tabindex="-1"></a><span class="co"># library(broom)</span></span>
<span id="cb4-11"><a href="multiple2.html#cb4-11" tabindex="-1"></a><span class="fu">glance</span>(without_interaction)</span></code></pre></div>
<div class="kable-table">
<table>
<colgroup>
<col width="9%" />
<col width="12%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="2%" />
<col width="9%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="10%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.0130486</td>
<td align="right">0.0065555</td>
<td align="right">0.7588684</td>
<td align="right">2.009602</td>
<td align="right">0.1358188</td>
<td align="right">2</td>
<td align="right">-349.3972</td>
<td align="right">706.7944</td>
<td align="right">721.7018</td>
<td align="right">175.0679</td>
<td align="right">304</td>
<td align="right">307</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>How much of the variance in <code>trustworthiness</code> is explained by the model with <code>attitude</code> and <code>group</code>? The adjusted R<sup>2</sup> (as a <strong>proportion</strong>, to two decimal places) = <input class='webex-solveme nospaces' size='4' data-answer='["0.01"]'/>.</li>
</ul>
<div class="webex-solution">
<button>
Hint: rounding
</button>
<p>Did you know that R can round values to two decimal places for you?</p>
<p>Use this code in your script:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="multiple2.html#cb5-1" tabindex="-1"></a><span class="co"># round adjusted r-squared to 2.D.P</span></span>
<span id="cb5-2"><a href="multiple2.html#cb5-2" tabindex="-1"></a><span class="fu">round</span>(<span class="fl">0.0065555</span>, <span class="dv">2</span>)</span></code></pre></div>
</div>
<p><br />
</p>
<p>Next use <code>lmBF()</code> to obtain the BF for the model with no interaction:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="multiple2.html#cb6-1" tabindex="-1"></a><span class="co"># library(BayesFactor)</span></span>
<span id="cb6-2"><a href="multiple2.html#cb6-2" tabindex="-1"></a></span>
<span id="cb6-3"><a href="multiple2.html#cb6-3" tabindex="-1"></a><span class="co"># obtain BF for the model</span></span>
<span id="cb6-4"><a href="multiple2.html#cb6-4" tabindex="-1"></a>BF_without_interaction <span class="ot">&lt;-</span> <span class="fu">lmBF</span>(trustworthiness <span class="sc">~</span> attitude <span class="sc">+</span> group,</span>
<span id="cb6-5"><a href="multiple2.html#cb6-5" tabindex="-1"></a>                               <span class="at">data =</span> <span class="fu">data.frame</span>(trust_data))</span>
<span id="cb6-6"><a href="multiple2.html#cb6-6" tabindex="-1"></a></span>
<span id="cb6-7"><a href="multiple2.html#cb6-7" tabindex="-1"></a><span class="co"># look at the BF</span></span>
<span id="cb6-8"><a href="multiple2.html#cb6-8" tabindex="-1"></a>BF_without_interaction </span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] attitude + group : 0.1057472 ±2.66%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The BF for the model without the interaction is equal to (to 2 decimal places) <input class='webex-solveme nospaces' data-tol='0.1' size='5' data-answer='["0.105",".105"]'/>.</p>
<div class="webex-solution">
<button>
Meaning of ±number%
</button>
<p>You'll notice that the BF has <code>±4.03%</code> or similar next to it in the output. This is the error associated with the BF. It's like saying my height is 185 cm, plus or minus 4 cm or so. It can be non-zero because generation of the BFs involves random sampling processes. Larger error values mean that the exact same value of the BF won't necessarily be output each time the line of code containing <code>lmBF()</code> is run, so there's a chance that the BFs in your output differ slightly from those above. It should be very low, and approximately 0.10 though.</p>
</div>
<p><br />
</p>
</div>
<div id="model-with-the-interaction" class="section level3 hasAnchor" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Model with the interaction<a href="multiple2.html#model-with-the-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="tip">
<p>To specify an interaction between two predictors, use the term <code>predictor1 * predictor2</code>. The <code>*</code> symbol means multiply, so the interaction term is simply the predictors multiplied together.</p>
</div>
<p>To specify the model with the interaction, add the interaction term <code>predictor1 * predictor2</code> to the model without the interaction term:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="multiple2.html#cb8-1" tabindex="-1"></a><span class="co"># Specify the model with the interaction</span></span>
<span id="cb8-2"><a href="multiple2.html#cb8-2" tabindex="-1"></a>with_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(trustworthiness <span class="sc">~</span> attitude <span class="sc">+</span> group <span class="sc">+</span> attitude<span class="sc">*</span>group,</span>
<span id="cb8-3"><a href="multiple2.html#cb8-3" tabindex="-1"></a>                       <span class="at">data =</span> trust_data)</span>
<span id="cb8-4"><a href="multiple2.html#cb8-4" tabindex="-1"></a></span>
<span id="cb8-5"><a href="multiple2.html#cb8-5" tabindex="-1"></a><span class="co"># R² for the model</span></span>
<span id="cb8-6"><a href="multiple2.html#cb8-6" tabindex="-1"></a><span class="fu">glance</span>(with_interaction)</span></code></pre></div>
<div class="kable-table">
<table style="width:100%;">
<colgroup>
<col width="9%" />
<col width="12%" />
<col width="8%" />
<col width="9%" />
<col width="9%" />
<col width="2%" />
<col width="9%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="10%" />
<col width="4%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
<th align="right">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.0623098</td>
<td align="right">0.0530257</td>
<td align="right">0.740907</td>
<td align="right">6.711482</td>
<td align="right">0.0002128</td>
<td align="right">3</td>
<td align="right">-341.5378</td>
<td align="right">693.0756</td>
<td align="right">711.7098</td>
<td align="right">166.3298</td>
<td align="right">303</td>
<td align="right">307</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>How much of the variance in <code>trustworthiness</code> is explained by the model with <code>attitude</code>,<code>group</code>, and the <code>attitude*group</code> interaction? The adjusted R<sup>2</sup> (as a proportion, to two decimal places) = <input class='webex-solveme nospaces' size='4' data-answer='["0.05"]'/>.</li>
</ul>
<p><br />
</p>
<p>Use <code>lmBF()</code> to obtain the BF for the model with the interaction:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="multiple2.html#cb9-1" tabindex="-1"></a><span class="co"># obtain BF for the model</span></span>
<span id="cb9-2"><a href="multiple2.html#cb9-2" tabindex="-1"></a>BF_with_interaction <span class="ot">&lt;-</span> </span>
<span id="cb9-3"><a href="multiple2.html#cb9-3" tabindex="-1"></a>  <span class="fu">lmBF</span>(trustworthiness <span class="sc">~</span> attitude <span class="sc">+</span> group <span class="sc">+</span> attitude<span class="sc">*</span>group,</span>
<span id="cb9-4"><a href="multiple2.html#cb9-4" tabindex="-1"></a>       <span class="at">data =</span> <span class="fu">data.frame</span>(trust_data))</span>
<span id="cb9-5"><a href="multiple2.html#cb9-5" tabindex="-1"></a></span>
<span id="cb9-6"><a href="multiple2.html#cb9-6" tabindex="-1"></a><span class="co"># look at the BF</span></span>
<span id="cb9-7"><a href="multiple2.html#cb9-7" tabindex="-1"></a>BF_with_interaction </span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] attitude + group + attitude * group : 31.10113 ±1.55%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The BF for the model with the interaction is equal to <input class='webex-solveme nospaces' data-tol='7.5' size='2' data-answer='["31"]'/>. (Note: yours may come out slightly different to that shown in the worksheet due to random sampling processes used in the BF generation; as long as the BF is around 30, that's okay.)</p>
<p><br />
</p>
</div>
<div id="compare-the-model-with-and-without-the-interaction" class="section level3 hasAnchor" number="4.5.3">
<h3><span class="header-section-number">4.5.3</span> Compare the model with and without the interaction<a href="multiple2.html#compare-the-model-with-and-without-the-interaction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To determine whether there's evidence for the interaction, we need to compare the Bayes factor for the model with and without the interaction.</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-3" class="exercise"><strong>Exercise 4.3  </strong></span>Bayes factors can be compared with the formula:</p>
<p><span class="math inline">\(\frac{Bayes \ factor \ more \ complex \ model}{Bayes \ factor \ simpler \ model}\)</span></p>
<p>Dividing the BFs in this way will return another Bayes factor, which is a number that tells us how many times more likely the more complex model compared to the simpler model, given the data.</p>
<p><br />
</p>
<p>So, if we perform this calculation:</p>
<p><span class="math inline">\(\frac{Bayes \ factor \ for \ model \ with \ interaction}{Bayes \ factor \ for \ model \ without \ interaction}\)</span></p>
<p>this will tell us how many times more likely the model <em>with</em> the interaction is than the model <em>without</em> the interaction. In other words, dividing the BF for the model with the interaction by the BF for the model without the interaction will tell us whether there's evidence for an interaction between the predictors.</p>
</div>
<p><br />
</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="multiple2.html#cb11-1" tabindex="-1"></a><span class="co"># compare BFs of models</span></span>
<span id="cb11-2"><a href="multiple2.html#cb11-2" tabindex="-1"></a><span class="co"># to determine evidence for the interaction</span></span>
<span id="cb11-3"><a href="multiple2.html#cb11-3" tabindex="-1"></a>BF_with_interaction <span class="sc">/</span> BF_without_interaction</span></code></pre></div>
<pre><code>## Bayes factor analysis
## --------------
## [1] attitude + group + attitude * group : 294.1083 ±3.08%
## 
## Against denominator:
##   trustworthiness ~ attitude + group 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<p>The Bayes factor for the comparison of the model with and without the interaction is approximately 300. (Yours may not be exactly equal to 300 because of the error associated with the generation of the Bayes factor; it should be roughly the same though!)</p>
<p><br />
</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-4" class="exercise"><strong>Exercise 4.4  </strong></span>Assessing the interaction</p>
<p><strong>Adjusted R<sup>2</sup>:</strong></p>
<ul>
<li>The adjusted R<sup>2</sup> for the model without the interaction (that you noted earlier) was: <input class='webex-solveme nospaces' size='4' data-answer='["0.01"]'/></li>
<li>The adjusted R<sup>2</sup> for the model with the interaction (that you also noted earlier) was: <input class='webex-solveme nospaces' size='4' data-answer='["0.05"]'/></li>
<li>What is the <em>increase</em> in adjusted R<sup>2</sup> as a result of the addition of the interaction term to the model? <em>Hint. Work out the difference between the two adjusted R<sup>2</sup> values you noted above</em> <input class='webex-solveme nospaces' size='4' data-answer='["0.04"]'/></li>
</ul>
<div class="webex-solution">
<button>
calculatoR
</button>
<p>Did you know that R can function like a calculator too? Simply type the formula next to <code>&gt;</code> in the console window and hit enter, e.g., <code>&gt; 2 + 2</code></p>
<p>Or use code in your script:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="multiple2.html#cb13-1" tabindex="-1"></a><span class="co"># work out difference in R-squared</span></span>
<span id="cb13-2"><a href="multiple2.html#cb13-2" tabindex="-1"></a><span class="fl">0.05</span> <span class="sc">-</span> <span class="fl">0.01</span></span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>Bayes factors</strong></p>
<ul>
<li>According to comparison of BFs for the model with and without an interaction term included, which statement is true?</li>
</ul>
<div id="radio_NOTXRCGFTO" class="webex-radiogroup">
<label><input type="radio" autocomplete="off" name="radio_NOTXRCGFTO" value=""></input> <span>There's substantial evidence for an absence of an interaction between attitude and group</span></label><label><input type="radio" autocomplete="off" name="radio_NOTXRCGFTO" value=""></input> <span>The model with the interaction is as likely as the model without the interaction, given the data</span></label><label><input type="radio" autocomplete="off" name="radio_NOTXRCGFTO" value="answer"></input> <span>There's substantial evidence for an interaction between attitude and group</span></label>
</div>
<div class="webex-solution">
<button>
Explanation
</button>
<p>As a result of adding in the interaction term to the model, the adjusted R<sup>2</sup> value increases by approximately 0.04 (i.e., from 0.01 to 0.05). The comparison of BFs for the model with and without the interaction term indicates that there's substantial evidence for the interaction between <code>attitude</code> and <code>group</code> - it's around 300 times more likely that there is an interaction than there isn't one, given the data.</p>
<p>Thus, as indicated in the scatterplot, there's evidence that the association between <code>trustworthiness</code> and <code>attitude</code> is different in each <code>group</code>. Specifically, the association is positive in the <code>affected</code> group, whereas it appears to be negative in the <code>not_affected</code> group.</p>
</div>
</div>
<p><br />
</p>
</div>
</div>
<div id="simple-slopes-analysis" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Simple slopes analysis<a href="multiple2.html#simple-slopes-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Given evidence for the interaction, we can conduct follow-up analyses to further characterise it.</p>
<div class="tip">
<p>In a <strong>simple slopes analysis</strong> the relationship between the outcome and first predictor is examined at each level of the second predictor.</p>
</div>
<p><br />
</p>
<p>Another way of thinking about the interaction is that it implies that the <em>slopes</em> of the lines for the <code>affected</code> group (red line in the scatterplot) and <code>not_affected</code> group (blue line) are not the same. We'll conduct a simple slopes analysis by conducting two simple regressions. The first will be the regression of <code>trustworthiness</code> on the basis of <code>attitude</code> in the <code>affected</code> group. The second will be the regression of <code>trustworthiness</code> on the basis of <code>attitude</code> in the <code>not_affected</code> group. The simplest way to do this is to store the data for each group separately, then perform a simple regression with each dataset.</p>
<p><br />
</p>
<p>First, filter <code>trust_data</code> for each <code>group</code>:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="multiple2.html#cb14-1" tabindex="-1"></a><span class="co"># Filter the dataset for when group is equal to &quot;affected&quot;</span></span>
<span id="cb14-2"><a href="multiple2.html#cb14-2" tabindex="-1"></a><span class="co"># store in affected_data</span></span>
<span id="cb14-3"><a href="multiple2.html#cb14-3" tabindex="-1"></a>affected_data <span class="ot">&lt;-</span> trust_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">&quot;affected&quot;</span>)</span>
<span id="cb14-4"><a href="multiple2.html#cb14-4" tabindex="-1"></a></span>
<span id="cb14-5"><a href="multiple2.html#cb14-5" tabindex="-1"></a><span class="co"># Filter the dataset for when group is equal to &quot;not_affected&quot;</span></span>
<span id="cb14-6"><a href="multiple2.html#cb14-6" tabindex="-1"></a><span class="co"># store in not_affected_data</span></span>
<span id="cb14-7"><a href="multiple2.html#cb14-7" tabindex="-1"></a>not_affected_data <span class="ot">&lt;-</span> trust_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">&quot;not_affected&quot;</span>)</span></code></pre></div>
<p><br />
</p>
<p>Now run a simple regression of <code>trustworthiness ~ attitude</code> in each group. First, do the <code>affected</code> group:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="multiple2.html#cb15-1" tabindex="-1"></a><span class="co"># affected group: simple regression coefficients</span></span>
<span id="cb15-2"><a href="multiple2.html#cb15-2" tabindex="-1"></a><span class="fu">lm</span>(trustworthiness <span class="sc">~</span> attitude, <span class="at">data =</span> affected_data)</span>
<span id="cb15-3"><a href="multiple2.html#cb15-3" tabindex="-1"></a></span>
<span id="cb15-4"><a href="multiple2.html#cb15-4" tabindex="-1"></a><span class="co"># affected group: BF</span></span>
<span id="cb15-5"><a href="multiple2.html#cb15-5" tabindex="-1"></a><span class="fu">lmBF</span>(trustworthiness <span class="sc">~</span> attitude, <span class="at">data =</span> <span class="fu">data.frame</span>(affected_data))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = trustworthiness ~ attitude, data = affected_data)
## 
## Coefficients:
## (Intercept)     attitude  
##      3.9631       0.1839  
## 
## Bayes factor analysis
## --------------
## [1] attitude : 1483.223 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<div class="exercise">
<p><span id="exr:unlabeled-div-5" class="exercise"><strong>Exercise 4.5  </strong></span>For the <code>affected</code> group (the red line in the scatter plot)</p>
<ul>
<li>The intercept of the regression line is = <input class='webex-solveme nospaces' size='4' data-answer='["3.96"]'/></li>
<li>The slope of the regression line is = <input class='webex-solveme nospaces' size='4' data-answer='["0.18"]'/></li>
<li>The BF for the model (to two decimal places) is <input class='webex-solveme nospaces' size='7' data-answer='["1483.22"]'/></li>
<li>This is <select class='webex-select'><option value='blank'></option><option value=''>inconclusive</option><option value='answer'>substantial</option></select> evidence for <select class='webex-select'><option value='blank'></option><option value=''>a negative</option><option value=''>an absence of an</option><option value='answer'>a positive</option></select> association between <code>trustworthiness</code> and <code>attitude</code> in the <code>affected</code> group.</li>
<li>In this group, participants with more positive attitudes to the research topic perceived the researcher to be <select class='webex-select'><option value='blank'></option><option value=''>less</option><option value='answer'>more</option></select> credible.</li>
</ul>
</div>
<p><br />
</p>
<p>For the <code>not_affected</code> group:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="multiple2.html#cb17-1" tabindex="-1"></a><span class="co"># not_affected group: simple regression coefficients</span></span>
<span id="cb17-2"><a href="multiple2.html#cb17-2" tabindex="-1"></a><span class="fu">lm</span>(trustworthiness <span class="sc">~</span> attitude, <span class="at">data =</span> not_affected_data)</span>
<span id="cb17-3"><a href="multiple2.html#cb17-3" tabindex="-1"></a></span>
<span id="cb17-4"><a href="multiple2.html#cb17-4" tabindex="-1"></a><span class="co"># not_affected group BF</span></span>
<span id="cb17-5"><a href="multiple2.html#cb17-5" tabindex="-1"></a><span class="fu">lmBF</span>(trustworthiness <span class="sc">~</span> attitude, <span class="at">data =</span> <span class="fu">data.frame</span>(not_affected_data))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = trustworthiness ~ attitude, data = not_affected_data)
## 
## Coefficients:
## (Intercept)     attitude  
##     5.09157     -0.09505  
## 
## Bayes factor analysis
## --------------
## [1] attitude : 0.5874073 ±0%
## 
## Against denominator:
##   Intercept only 
## ---
## Bayes factor type: BFlinearModel, JZS</code></pre>
<div class="exercise">
<p><span id="exr:unlabeled-div-6" class="exercise"><strong>Exercise 4.6  </strong></span>For the <code>not_affected</code> group (the blue line in the scatterplot)</p>
<ul>
<li>The intercept of the regression line is = <input class='webex-solveme nospaces' size='4' data-answer='["5.09"]'/></li>
<li>The slope of the regression line is = <input class='webex-solveme nospaces' size='5' data-answer='["-0.10"]'/></li>
<li>The BF for the model is <input class='webex-solveme nospaces' size='4' data-answer='["0.59"]'/></li>
<li>Although the scatterplot suggests <select class='webex-select'><option value='blank'></option><option value='answer'>a negative</option><option value=''>an absence of an</option><option value=''>a positive</option></select> association between <code>trustworthiness</code> and <code>attitude</code> in the <code>not_affected</code> group, there was insufficient evidence for this association because the Bayes factor was <select class='webex-select'><option value='blank'></option><option value='answer'>inconclusive</option><option value=''>substantial</option></select></li>
</ul>
</div>
<p><br />
</p>
<p>In sum, this analysis has shown that when participants hold a more favourable attitude towards a research topic, they perceived researchers who were personally affected by their own research as being more trustworthy. Although the association appeared to be reversed for researchers who were not personally affected by their research, a Bayes factor analysis indicated that there was insufficient evidence of an association between trustworthiness and attitude in this group.</p>
<p><br />
</p>
</div>
<div id="exercises" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> Exercises<a href="multiple2.html#exercises" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-7" class="exercise"><strong>Exercise 4.7  </strong></span>Credibility</p>
<p>In addition to asking about <em>trustworthiness</em>, Altenmuller et al. (2021) also asked participants how <em>credible</em> they found the researcher. The scores are stored in <code>credibility</code> in the <code>trust_data</code>; higher scores indicate greater perceived credibility. As with <code>trustworthiness</code>, the authors looked at whether <code>attitude</code> and <code>group</code> predicted <code>credibility</code>.</p>
<p><br />
</p>
<p><strong>Adapt the code in this worksheet to do the following:</strong></p>
<ol style="list-style-type: decimal">
<li><strong>Create a scatterplot with <code>credibility</code> on the y-axis, <code>attitude</code> on the x-axis, and <code>group</code> as separate lines.</strong></li>
</ol>
<div class="webex-solution">
<button>
Hint
</button>
<p>Pipe the data to <code>ggplot()</code> and use <code>colour = group</code> in <code>aes</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="multiple2.html#cb19-1" tabindex="-1"></a>trust_data <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="multiple2.html#cb19-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> attitude, <span class="at">y =</span> credibility, <span class="at">colour =</span> group )) <span class="sc">+</span></span>
<span id="cb19-3"><a href="multiple2.html#cb19-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb19-4"><a href="multiple2.html#cb19-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="multiple2.html#cb19-5" tabindex="-1"></a>  <span class="fu">theme_light</span>() </span></code></pre></div>
</div>
<ul>
<li>The slope for the <code>affected</code> group appears to be <select class='webex-select'><option value='blank'></option><option value=''>close to zero</option><option value='answer'>positive</option><option value=''>negative</option></select></li>
<li>The slope for the <code>not_affected</code> group appears to be <select class='webex-select'><option value='blank'></option><option value='answer'>close to zero</option><option value='answer'>weakly positive</option><option value=''>negative</option></select></li>
</ul>
<p><br />
</p>
<p><strong>2. Obtain adjusted R<sup>2</sup> and the BF for the model <em>without</em> an interaction</strong></p>
<ul>
<li>Adjusted R<sup>2</sup> (as a proportion, to 2 decimal places) for the model without an interaction is: <input class='webex-solveme nospaces' size='4' data-answer='["0.15"]'/></li>
<li>The BF for the model without an interaction is <input class='webex-solveme nospaces' data-tol='9e+07' size='9' data-answer='["927611180"]'/></li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<p>Specify the model with <code>predictor1 + predictor2</code> with <code>lm()</code>, pass to <code>glance()</code>, then use <code>lmBF()</code> to get the BF.</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="multiple2.html#cb20-1" tabindex="-1"></a><span class="co"># Specify the model without an interaction</span></span>
<span id="cb20-2"><a href="multiple2.html#cb20-2" tabindex="-1"></a>credibility_no_interaction <span class="ot">&lt;-</span> </span>
<span id="cb20-3"><a href="multiple2.html#cb20-3" tabindex="-1"></a>  <span class="fu">lm</span>(credibility <span class="sc">~</span> attitude <span class="sc">+</span> group, <span class="at">data =</span> trust_data)</span>
<span id="cb20-4"><a href="multiple2.html#cb20-4" tabindex="-1"></a></span>
<span id="cb20-5"><a href="multiple2.html#cb20-5" tabindex="-1"></a><span class="co"># library(broom)</span></span>
<span id="cb20-6"><a href="multiple2.html#cb20-6" tabindex="-1"></a><span class="fu">glance</span>(credibility_no_interaction)</span>
<span id="cb20-7"><a href="multiple2.html#cb20-7" tabindex="-1"></a></span>
<span id="cb20-8"><a href="multiple2.html#cb20-8" tabindex="-1"></a><span class="co"># BF model</span></span>
<span id="cb20-9"><a href="multiple2.html#cb20-9" tabindex="-1"></a>BF_credibility_no_interaction <span class="ot">&lt;-</span></span>
<span id="cb20-10"><a href="multiple2.html#cb20-10" tabindex="-1"></a>  <span class="fu">lmBF</span>(credibility <span class="sc">~</span> attitude <span class="sc">+</span> group, <span class="at">data =</span> <span class="fu">data.frame</span>(trust_data))</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>3. Obtain adjusted R<sup>2</sup> and the BF for the model <em>with</em> an interaction</strong></p>
<ul>
<li>Adjusted R<sup>2</sup> (as a <em>proportion</em>, to 2 decimal places) for the model with an interaction is: <input class='webex-solveme nospaces' size='4' data-answer='["0.21"]'/></li>
<li>The BF for the model with an interaction is <input class='webex-solveme nospaces' data-tol='1.2' size='3' data-answer='["7.5"]'/> x 10<sup>12</sup></li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<p>Specify the model with <code>predictor1 + predictor2 + predictor1*predictor2</code> with <code>lm()</code>, pass to <code>glance()</code>, then use <code>lmBF()</code> to get the BF.</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="multiple2.html#cb21-1" tabindex="-1"></a><span class="co"># Specify the model with an interaction</span></span>
<span id="cb21-2"><a href="multiple2.html#cb21-2" tabindex="-1"></a>credibility_with_interaction <span class="ot">&lt;-</span> </span>
<span id="cb21-3"><a href="multiple2.html#cb21-3" tabindex="-1"></a>  <span class="fu">lm</span>(credibility <span class="sc">~</span> attitude <span class="sc">+</span> group <span class="sc">+</span> attitude<span class="sc">*</span>group, <span class="at">data =</span> trust_data)</span>
<span id="cb21-4"><a href="multiple2.html#cb21-4" tabindex="-1"></a></span>
<span id="cb21-5"><a href="multiple2.html#cb21-5" tabindex="-1"></a><span class="co"># library(broom)</span></span>
<span id="cb21-6"><a href="multiple2.html#cb21-6" tabindex="-1"></a><span class="fu">glance</span>(credibility_with_interaction)</span>
<span id="cb21-7"><a href="multiple2.html#cb21-7" tabindex="-1"></a></span>
<span id="cb21-8"><a href="multiple2.html#cb21-8" tabindex="-1"></a><span class="co"># BF model</span></span>
<span id="cb21-9"><a href="multiple2.html#cb21-9" tabindex="-1"></a>BF_credibility_with_interaction <span class="ot">&lt;-</span></span>
<span id="cb21-10"><a href="multiple2.html#cb21-10" tabindex="-1"></a>  <span class="fu">lmBF</span>(credibility <span class="sc">~</span> attitude <span class="sc">+</span> group <span class="sc">+</span> attitude<span class="sc">*</span>group, <span class="at">data =</span> <span class="fu">data.frame</span>(trust_data))</span></code></pre></div>
</div>
<div class="webex-solution">
<button>
What does x 10^12 mean?
</button>
<p>It means a very large number! For more information see:
<a href="https://chrisjberry.github.io/datafluencyCB/faqs#e-meaning" target="_blank">FAQ</a> (Opens a new tab.)</p>
<p>Please take care to notice "e+" or "e-" in the output for your Bayes factors. As you can see, BF<sub>10</sub> = 1.82 means something drastically different to BF<sub>10</sub> = 1.82 x 10<sup>27</sup>, and you wouldn't want to make this kind of mistake when drawing statistical inferences!</p>
</div>
<p><br />
</p>
<p><strong>4. Compare the models with and without the interaction</strong></p>
<ul>
<li>The increase in adjusted R<sup>2</sup> as a result of including the interaction term in the model is (as a proportion to 2 decimal places) = <input class='webex-solveme nospaces' size='4' data-answer='["0.06"]'/></li>
<li>The Bayes factor for the comparison of the models with and without the interaction = <input class='webex-solveme nospaces' data-tol='600' size='4' data-answer='["8400"]'/></li>
<li>Is there substantial evidence for an interaction between <code>attitude</code> and <code>group</code> in the prediction of percieved credibility of the researcher? <select class='webex-select'><option value='blank'></option><option value=''>no</option><option value='answer'>yes</option></select></li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<ul>
<li>Work out the difference in adjusted R<sup>2</sup> in the model with and without the interaction.</li>
<li>Use <code>BF_model_with_interaction / BF_model_without_interaction</code></li>
<li>If the BF &gt; 3, then by convention we say there's substantial evidence for the interaction.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="multiple2.html#cb22-1" tabindex="-1"></a><span class="co"># Adj R-square difference</span></span>
<span id="cb22-2"><a href="multiple2.html#cb22-2" tabindex="-1"></a><span class="fl">0.21</span> <span class="sc">-</span> <span class="fl">0.15</span></span>
<span id="cb22-3"><a href="multiple2.html#cb22-3" tabindex="-1"></a></span>
<span id="cb22-4"><a href="multiple2.html#cb22-4" tabindex="-1"></a><span class="co"># Compare BFs</span></span>
<span id="cb22-5"><a href="multiple2.html#cb22-5" tabindex="-1"></a>BF_credibility_with_interaction <span class="sc">/</span> BF_credibility_no_interaction</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>5. Simple slopes analysis</strong></p>
<p>For the <code>affected</code> group:</p>
<ul>
<li>The intercept of the regression line is = <input class='webex-solveme nospaces' size='4' data-answer='["1.92"]'/></li>
<li>The slope of the regression line is = <input class='webex-solveme nospaces' size='4' data-answer='["0.47"]'/></li>
<li>The BF for the model is <input class='webex-solveme nospaces' size='4' data-answer='["1.91"]'/> x 10<sup>15</sup></li>
<li>This is <select class='webex-select'><option value='blank'></option><option value=''>inconclusive</option><option value='answer'>substantial</option></select> evidence for <select class='webex-select'><option value='blank'></option><option value=''>a negative</option><option value=''>an absence of an</option><option value='answer'>a positive</option></select> association between <code>credibility</code> and <code>attitude</code> in the <code>affected</code> group.</li>
<li>In this group, participants with more positive attitudes to the research topic perceived the researcher to <select class='webex-select'><option value='blank'></option><option value=''>be less</option><option value='answer'>be more</option></select> credible.</li>
</ul>
<p><br />
</p>
<p>For the <code>not_affected</code> group:</p>
<ul>
<li>The intercept of the regression line is = <input class='webex-solveme nospaces' size='4' data-answer='["3.73"]'/></li>
<li>The slope of the regression line is = <input class='webex-solveme nospaces' size='4' data-answer='["0.08"]'/></li>
<li>The BF for the model is <input class='webex-solveme nospaces' size='4' data-answer='["0.32"]'/></li>
<li>This is <select class='webex-select'><option value='blank'></option><option value=''>inconclusive</option><option value='answer'>substantial</option></select> evidence for <select class='webex-select'><option value='blank'></option><option value=''>a negative</option><option value='answer'>an absence of an</option><option value=''>a positive</option></select> association between <code>credibility</code> and <code>attitude</code> in the <code>not_affected</code> group.</li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<p>Use <code>filter()</code> to separate out the groups of each dataset.
Conduct one simple regression for the <code>affected</code> group.
Conduct one simple regression for the <code>not_affected</code> group.</p>
</div>
<div class="webex-solution">
<button>
Code
</button>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="multiple2.html#cb23-1" tabindex="-1"></a><span class="co"># Filter the dataset for when group is equal to &quot;affected&quot;</span></span>
<span id="cb23-2"><a href="multiple2.html#cb23-2" tabindex="-1"></a>affected_data <span class="ot">&lt;-</span> trust_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">&quot;affected&quot;</span>)</span>
<span id="cb23-3"><a href="multiple2.html#cb23-3" tabindex="-1"></a></span>
<span id="cb23-4"><a href="multiple2.html#cb23-4" tabindex="-1"></a><span class="co"># Filter the dataset for when group is equal to &quot;not_affected&quot;</span></span>
<span id="cb23-5"><a href="multiple2.html#cb23-5" tabindex="-1"></a>not_affected_data <span class="ot">&lt;-</span> trust_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">&quot;not_affected&quot;</span>)</span>
<span id="cb23-6"><a href="multiple2.html#cb23-6" tabindex="-1"></a></span>
<span id="cb23-7"><a href="multiple2.html#cb23-7" tabindex="-1"></a><span class="co"># affected group coefficients</span></span>
<span id="cb23-8"><a href="multiple2.html#cb23-8" tabindex="-1"></a><span class="fu">lm</span>(credibility <span class="sc">~</span> attitude, <span class="at">data =</span> affected_data)</span>
<span id="cb23-9"><a href="multiple2.html#cb23-9" tabindex="-1"></a></span>
<span id="cb23-10"><a href="multiple2.html#cb23-10" tabindex="-1"></a><span class="co"># affected group BF</span></span>
<span id="cb23-11"><a href="multiple2.html#cb23-11" tabindex="-1"></a><span class="fu">lmBF</span>(credibility <span class="sc">~</span> attitude, <span class="at">data =</span> <span class="fu">data.frame</span>(affected_data))</span>
<span id="cb23-12"><a href="multiple2.html#cb23-12" tabindex="-1"></a></span>
<span id="cb23-13"><a href="multiple2.html#cb23-13" tabindex="-1"></a><span class="co"># not_affected group coefficients</span></span>
<span id="cb23-14"><a href="multiple2.html#cb23-14" tabindex="-1"></a><span class="fu">lm</span>(credibility <span class="sc">~</span> attitude, <span class="at">data =</span> not_affected_data)</span>
<span id="cb23-15"><a href="multiple2.html#cb23-15" tabindex="-1"></a></span>
<span id="cb23-16"><a href="multiple2.html#cb23-16" tabindex="-1"></a><span class="co"># not_affected group BF</span></span>
<span id="cb23-17"><a href="multiple2.html#cb23-17" tabindex="-1"></a><span class="fu">lmBF</span>(credibility <span class="sc">~</span> attitude, <span class="at">data =</span> <span class="fu">data.frame</span>(not_affected_data))</span></code></pre></div>
</div>
</div>
<p><br />
</p>
<div class="exercise">
<p><span id="exr:unlabeled-div-8" class="exercise"><strong>Exercise 4.8  </strong></span>Critical evaluation of the field</p>
<p>Altenmuller et al. (2021) also asked participants to report how critical they were in their evaluation of the entire research field. The scores are stored in <code>evaluation</code> in the <code>trust_data</code>; higher scores indicate that the participant evaluated the field <em>more critically</em>. As with the other outcome variables we've considered, the authors looked at whether <code>attitude</code> and <code>group</code> predicted <code>evaluation</code>.</p>
<p><br />
</p>
<p><strong>Adapt the code in this worksheet to do the following:</strong></p>
<ol style="list-style-type: decimal">
<li><strong>Create a scatterplot with <code>evaluation</code> on the y-axis, <code>attitude</code> on the x-axis, and <code>group</code> as separate lines.</strong></li>
</ol>
<div class="webex-solution">
<button>
Hint
</button>
<p>Pipe the data to <code>ggplot()</code> and use <code>colour = group</code> in <code>aes()</code></p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="multiple2.html#cb24-1" tabindex="-1"></a>trust_data <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="multiple2.html#cb24-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> attitude, <span class="at">y =</span> evaluation, <span class="at">colour =</span> group )) <span class="sc">+</span></span>
<span id="cb24-3"><a href="multiple2.html#cb24-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-4"><a href="multiple2.html#cb24-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="multiple2.html#cb24-5" tabindex="-1"></a>  <span class="fu">theme_light</span>() </span></code></pre></div>
</div>
<ul>
<li>The slope for the <code>affected</code> group appears to be <select class='webex-select'><option value='blank'></option><option value=''>close to zero</option><option value=''>positive</option><option value='answer'>negative</option></select></li>
<li>The slope for the <code>not_affected</code> group appears to be <select class='webex-select'><option value='blank'></option><option value='answer'>close to zero</option><option value=''>positive</option><option value='answer'>negative</option></select></li>
</ul>
<p><br />
</p>
<p><strong>2. Obtain adjusted R<sup>2</sup> and the BF for the model without an interaction</strong></p>
<ul>
<li>Adjusted R<sup>2</sup> (as a proportion, to 2 decimal places) for the model without an interaction is: <input class='webex-solveme nospaces' size='4' data-answer='["0.20"]'/></li>
<li>The BF for the model without an interaction is <input class='webex-solveme nospaces' data-tol='0.3' size='3' data-answer='["1.4"]'/> x 10<sup>13</sup></li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<p>Specify the model with <code>predictor1 + predictor2</code> with <code>lm()</code>, pass to <code>glance()</code>, then use <code>lmBF()</code> to get the BF.</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="multiple2.html#cb25-1" tabindex="-1"></a><span class="co"># Specify the model without an interaction</span></span>
<span id="cb25-2"><a href="multiple2.html#cb25-2" tabindex="-1"></a>evaluation_no_interaction <span class="ot">&lt;-</span> </span>
<span id="cb25-3"><a href="multiple2.html#cb25-3" tabindex="-1"></a>  <span class="fu">lm</span>(evaluation <span class="sc">~</span> attitude <span class="sc">+</span> group, <span class="at">data =</span> trust_data)</span>
<span id="cb25-4"><a href="multiple2.html#cb25-4" tabindex="-1"></a></span>
<span id="cb25-5"><a href="multiple2.html#cb25-5" tabindex="-1"></a><span class="co"># library(broom)</span></span>
<span id="cb25-6"><a href="multiple2.html#cb25-6" tabindex="-1"></a><span class="fu">glance</span>(evaluation_no_interaction)</span>
<span id="cb25-7"><a href="multiple2.html#cb25-7" tabindex="-1"></a></span>
<span id="cb25-8"><a href="multiple2.html#cb25-8" tabindex="-1"></a><span class="co"># BF model</span></span>
<span id="cb25-9"><a href="multiple2.html#cb25-9" tabindex="-1"></a>BF_evaluation_no_interaction <span class="ot">&lt;-</span></span>
<span id="cb25-10"><a href="multiple2.html#cb25-10" tabindex="-1"></a>  <span class="fu">lmBF</span>(evaluation <span class="sc">~</span> attitude <span class="sc">+</span> group, <span class="at">data =</span> <span class="fu">data.frame</span>(trust_data))</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>3. Obtain adjusted R<sup>2</sup> and the BF for the model with an interaction</strong></p>
<ul>
<li>Adjusted R<sup>2</sup> (as a <em>proportion</em>, to 2 decimal places) for the model with an interaction is: <input class='webex-solveme nospaces' size='4' data-answer='["0.27"]'/></li>
<li>The BF for the model with an interaction is <input class='webex-solveme nospaces' data-tol='1' size='3' data-answer='["2.9"]'/> x 10<sup>18</sup></li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<p>Specify the model with <code>predictor1 + predictor2 + predictor1*predictor2</code> with <code>lm()</code>, pass to <code>glance()</code>, then use <code>lmBF()</code> to get the BF.</p>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="multiple2.html#cb26-1" tabindex="-1"></a><span class="co"># Specify the model with an interaction</span></span>
<span id="cb26-2"><a href="multiple2.html#cb26-2" tabindex="-1"></a>evaluation_with_interaction <span class="ot">&lt;-</span> </span>
<span id="cb26-3"><a href="multiple2.html#cb26-3" tabindex="-1"></a>  <span class="fu">lm</span>(evaluation <span class="sc">~</span> attitude <span class="sc">+</span> group <span class="sc">+</span> attitude<span class="sc">*</span>group, <span class="at">data =</span> trust_data)</span>
<span id="cb26-4"><a href="multiple2.html#cb26-4" tabindex="-1"></a></span>
<span id="cb26-5"><a href="multiple2.html#cb26-5" tabindex="-1"></a><span class="co"># library(broom)</span></span>
<span id="cb26-6"><a href="multiple2.html#cb26-6" tabindex="-1"></a><span class="fu">glance</span>(evaluation_with_interaction)</span>
<span id="cb26-7"><a href="multiple2.html#cb26-7" tabindex="-1"></a></span>
<span id="cb26-8"><a href="multiple2.html#cb26-8" tabindex="-1"></a><span class="co"># BF model</span></span>
<span id="cb26-9"><a href="multiple2.html#cb26-9" tabindex="-1"></a>BF_evaluation_with_interaction <span class="ot">&lt;-</span></span>
<span id="cb26-10"><a href="multiple2.html#cb26-10" tabindex="-1"></a>  <span class="fu">lmBF</span>(evaluation <span class="sc">~</span> attitude <span class="sc">+</span> group <span class="sc">+</span> attitude<span class="sc">*</span>group, <span class="at">data =</span> <span class="fu">data.frame</span>(trust_data))</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>4. Compare the model with and without the interaction</strong></p>
<ul>
<li>The increase in adjusted R<sup>2</sup> as a result of including the interaction in the model is (as a proportion to 2 decimal places) = <input class='webex-solveme nospaces' size='4' data-answer='["0.07"]'/></li>
<li>The Bayes factor for the model with the interaction vs. without = <input class='webex-solveme nospaces' data-tol='50000' size='6' data-answer='["212284"]'/></li>
<li>Is there evidence for an interaction between <code>attitude</code> and <code>group</code>? <select class='webex-select'><option value='blank'></option><option value=''>no</option><option value='answer'>yes</option></select></li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<ul>
<li>Work out the difference in adjusted R<sup>2</sup> in the model with and without the interaction.</li>
<li>Use <code>BF_more_complex_model / BF_simpler_model</code></li>
<li>If the BF &gt; 3, then there's substantial evidence for the interaction.</li>
</ul>
</div>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="multiple2.html#cb27-1" tabindex="-1"></a><span class="co"># Adj R-square difference</span></span>
<span id="cb27-2"><a href="multiple2.html#cb27-2" tabindex="-1"></a><span class="fl">0.27</span> <span class="sc">-</span> <span class="fl">0.20</span></span>
<span id="cb27-3"><a href="multiple2.html#cb27-3" tabindex="-1"></a></span>
<span id="cb27-4"><a href="multiple2.html#cb27-4" tabindex="-1"></a><span class="co"># Compare BFs</span></span>
<span id="cb27-5"><a href="multiple2.html#cb27-5" tabindex="-1"></a>BF_evaluation_with_interaction <span class="sc">/</span> BF_evaluation_no_interaction</span></code></pre></div>
</div>
<p><br />
</p>
<p><strong>5. Simple slopes analysis</strong></p>
<p>For the <code>affected</code> group:</p>
<ul>
<li>The intercept of the regression line is = <input class='webex-solveme nospaces' size='4' data-answer='["4.80"]'/></li>
<li>The slope of the regression line is = <input class='webex-solveme nospaces' size='5' data-answer='["-0.44"]'/></li>
<li>The BF for the model is <input class='webex-solveme nospaces' size='4' data-answer='["1.15"]'/> x 10<sup>20</sup></li>
<li>This is <select class='webex-select'><option value='blank'></option><option value=''>inconclusive</option><option value='answer'>substantial</option></select> evidence for <select class='webex-select'><option value='blank'></option><option value='answer'>a negative</option><option value=''>an absence of an</option><option value=''>a positive</option></select> association between <code>evaluation</code> and <code>attitude</code> in the <code>affected</code> group.</li>
<li>In this group, participants with more positive attitudes to the research topic evaluated the research field <select class='webex-select'><option value='blank'></option><option value='answer'>less</option><option value=''>more</option></select> critically</li>
</ul>
<p><br />
</p>
<p>For the <code>not_affected</code> group:</p>
<ul>
<li>The intercept of the regression line is = <input class='webex-solveme nospaces' size='4' data-answer='["3.32"]'/></li>
<li>The slope of the regression line is = <input class='webex-solveme nospaces' size='5' data-answer='["-0.09"]'/></li>
<li>The BF for the model is <input class='webex-solveme nospaces' size='4' data-answer='["0.65"]'/></li>
<li>This is <select class='webex-select'><option value='blank'></option><option value=''>substantial</option><option value='answer'>insufficient</option></select> evidence for an association between <code>evaluation</code> and <code>attitude</code> in the <code>not_affected</code> group.</li>
</ul>
<div class="webex-solution">
<button>
Hint
</button>
<p>Use <code>filter()</code> to separate out the groups of each dataset.
Conduct one simple regression for the <code>affected</code> group.
Conduct one simple regression for the <code>not_affected</code> group.</p>
</div>
<div class="webex-solution">
<button>
Code
</button>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="multiple2.html#cb28-1" tabindex="-1"></a><span class="co"># Filter the dataset for when group is equal to &quot;affected&quot;</span></span>
<span id="cb28-2"><a href="multiple2.html#cb28-2" tabindex="-1"></a>affected_data <span class="ot">&lt;-</span> trust_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">&quot;affected&quot;</span>)</span>
<span id="cb28-3"><a href="multiple2.html#cb28-3" tabindex="-1"></a></span>
<span id="cb28-4"><a href="multiple2.html#cb28-4" tabindex="-1"></a><span class="co"># Filter the dataset for when group is equal to &quot;not_affected&quot;</span></span>
<span id="cb28-5"><a href="multiple2.html#cb28-5" tabindex="-1"></a>not_affected_data <span class="ot">&lt;-</span> trust_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">&quot;not_affected&quot;</span>)</span>
<span id="cb28-6"><a href="multiple2.html#cb28-6" tabindex="-1"></a></span>
<span id="cb28-7"><a href="multiple2.html#cb28-7" tabindex="-1"></a><span class="co"># affected group</span></span>
<span id="cb28-8"><a href="multiple2.html#cb28-8" tabindex="-1"></a><span class="fu">lm</span>(evaluation <span class="sc">~</span> attitude, <span class="at">data =</span> affected_data)</span>
<span id="cb28-9"><a href="multiple2.html#cb28-9" tabindex="-1"></a></span>
<span id="cb28-10"><a href="multiple2.html#cb28-10" tabindex="-1"></a><span class="co"># affected group BF</span></span>
<span id="cb28-11"><a href="multiple2.html#cb28-11" tabindex="-1"></a><span class="fu">lmBF</span>(evaluation <span class="sc">~</span> attitude, <span class="at">data =</span> <span class="fu">data.frame</span>(affected_data))</span>
<span id="cb28-12"><a href="multiple2.html#cb28-12" tabindex="-1"></a></span>
<span id="cb28-13"><a href="multiple2.html#cb28-13" tabindex="-1"></a><span class="co"># not_affected group</span></span>
<span id="cb28-14"><a href="multiple2.html#cb28-14" tabindex="-1"></a><span class="fu">lm</span>(evaluation <span class="sc">~</span> attitude, <span class="at">data =</span> not_affected_data)</span>
<span id="cb28-15"><a href="multiple2.html#cb28-15" tabindex="-1"></a></span>
<span id="cb28-16"><a href="multiple2.html#cb28-16" tabindex="-1"></a><span class="co"># not affected group BF</span></span>
<span id="cb28-17"><a href="multiple2.html#cb28-17" tabindex="-1"></a><span class="fu">lmBF</span>(evaluation <span class="sc">~</span> attitude, <span class="at">data =</span> <span class="fu">data.frame</span>(not_affected_data))</span></code></pre></div>
</div>
</div>
<p><br />
</p>
</div>
<div id="further-exercise" class="section level2 hasAnchor" number="4.8">
<h2><span class="header-section-number">4.8</span> Further exercise<a href="multiple2.html#further-exercise" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-9" class="exercise"><strong>Exercise 4.9  </strong></span>No interaction</p>
<p>Using the data from Teychenne and Hinkley (2016) that we used in Session 1, determine whether there is evidence for an interaction between <code>anxiety_score</code> and level of <code>education</code> in the prediction of <code>screen_time</code>. <code>education</code> is made up of groups 'No uni degree' and 'University degree'.</p>
<p>The data are located at:</p>
<p><a href="https://raw.githubusercontent.com/chrisjberry/Teaching/master/1_mental_health_data.csv" class="uri">https://raw.githubusercontent.com/chrisjberry/Teaching/master/1_mental_health_data.csv</a></p>
<ul>
<li>The increase in adjusted R<sup>2</sup> associated with the addition of the interaction to the model is (as a proportion) <input class='webex-solveme nospaces' data-tol='0.01' size='1' data-answer='["0"]'/></li>
<li>The Bayes factor comparing the model with and without the interaction is (to two decimal places) <input class='webex-solveme nospaces' data-tol='0.55' size='4' data-answer='["0.17",".17"]'/></li>
<li>There's substantial evidence that the relationship between <code>anxiety_score</code> and <code>screen_time</code> is <select class='webex-select'><option value='blank'></option><option value='answer'>the same</option><option value=''>different</option></select> in those who have a degree and those who don't.</li>
</ul>
<p><br />
</p>
<p>Given the lack of evidence for an interaction, in an additive model containing only <code>anxiety_score</code> and <code>education</code> as predictors of <code>screen_time</code>:</p>
<ul>
<li>Higher anxiety scores tended to be associated with <select class='webex-select'><option value='blank'></option><option value=''>fewer</option><option value=''>no change in</option><option value='answer'>greater</option></select> hours of screen time, but the Bayes factor indicated that there was insufficient evidence for this association, BF = <input class='webex-solveme nospaces' data-tol='0.2' size='3' data-answer='["2.2"]'/>.</li>
<li>Individuals without a university degree tended to spend <select class='webex-select'><option value='blank'></option><option value=''>a similar amount of time</option><option value='answer'>greater amounts of time</option><option value=''>lower amounts of time</option></select> using screens (e.g., devices, TV, computer) each week than those with a university degree, BF = <input class='webex-solveme nospaces' data-tol='1000' size='5' data-answer='["32604"]'/></li>
</ul>
<div class="webex-solution">
<button>
Solution code
</button>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="multiple2.html#cb29-1" tabindex="-1"></a><span class="co"># read the data to R using read_csv()</span></span>
<span id="cb29-2"><a href="multiple2.html#cb29-2" tabindex="-1"></a>mentalh <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://raw.githubusercontent.com/chrisjberry/Teaching/master/1_mental_health_data.csv&#39;</span>)</span>
<span id="cb29-3"><a href="multiple2.html#cb29-3" tabindex="-1"></a></span>
<span id="cb29-4"><a href="multiple2.html#cb29-4" tabindex="-1"></a><span class="co"># scatterplot</span></span>
<span id="cb29-5"><a href="multiple2.html#cb29-5" tabindex="-1"></a>mentalh <span class="sc">%&gt;%</span> </span>
<span id="cb29-6"><a href="multiple2.html#cb29-6" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> anxiety_score, <span class="at">y =</span> screen_time, <span class="at">colour =</span> education )) <span class="sc">+</span></span>
<span id="cb29-7"><a href="multiple2.html#cb29-7" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-8"><a href="multiple2.html#cb29-8" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb29-9"><a href="multiple2.html#cb29-9" tabindex="-1"></a>  <span class="fu">theme_light</span>() </span>
<span id="cb29-10"><a href="multiple2.html#cb29-10" tabindex="-1"></a></span>
<span id="cb29-11"><a href="multiple2.html#cb29-11" tabindex="-1"></a><span class="co"># Specify the model without an interaction</span></span>
<span id="cb29-12"><a href="multiple2.html#cb29-12" tabindex="-1"></a>screen_time_no_interaction <span class="ot">&lt;-</span> </span>
<span id="cb29-13"><a href="multiple2.html#cb29-13" tabindex="-1"></a>  <span class="fu">lm</span>(screen_time <span class="sc">~</span> anxiety_score <span class="sc">+</span> education, <span class="at">data =</span> mentalh)</span>
<span id="cb29-14"><a href="multiple2.html#cb29-14" tabindex="-1"></a></span>
<span id="cb29-15"><a href="multiple2.html#cb29-15" tabindex="-1"></a><span class="co"># in library(broom)</span></span>
<span id="cb29-16"><a href="multiple2.html#cb29-16" tabindex="-1"></a><span class="fu">glance</span>(screen_time_no_interaction) <span class="co"># adj R² = 0.06</span></span>
<span id="cb29-17"><a href="multiple2.html#cb29-17" tabindex="-1"></a></span>
<span id="cb29-18"><a href="multiple2.html#cb29-18" tabindex="-1"></a><span class="co"># BF model</span></span>
<span id="cb29-19"><a href="multiple2.html#cb29-19" tabindex="-1"></a>BF_screen_time_no_interaction <span class="ot">&lt;-</span></span>
<span id="cb29-20"><a href="multiple2.html#cb29-20" tabindex="-1"></a>  <span class="fu">lmBF</span>(screen_time <span class="sc">~</span> anxiety_score <span class="sc">+</span> education, <span class="at">data =</span> <span class="fu">data.frame</span>(mentalh))</span>
<span id="cb29-21"><a href="multiple2.html#cb29-21" tabindex="-1"></a></span>
<span id="cb29-22"><a href="multiple2.html#cb29-22" tabindex="-1"></a><span class="co"># Specify the model with an interaction</span></span>
<span id="cb29-23"><a href="multiple2.html#cb29-23" tabindex="-1"></a>screen_time_with_interaction <span class="ot">&lt;-</span> </span>
<span id="cb29-24"><a href="multiple2.html#cb29-24" tabindex="-1"></a>  <span class="fu">lm</span>(screen_time <span class="sc">~</span> anxiety_score <span class="sc">+</span> education <span class="sc">+</span> anxiety_score<span class="sc">*</span>education, <span class="at">data =</span> mentalh)</span>
<span id="cb29-25"><a href="multiple2.html#cb29-25" tabindex="-1"></a></span>
<span id="cb29-26"><a href="multiple2.html#cb29-26" tabindex="-1"></a><span class="co"># library(broom)</span></span>
<span id="cb29-27"><a href="multiple2.html#cb29-27" tabindex="-1"></a><span class="fu">glance</span>(screen_time_with_interaction)  <span class="co"># adj R² = 0.06</span></span>
<span id="cb29-28"><a href="multiple2.html#cb29-28" tabindex="-1"></a></span>
<span id="cb29-29"><a href="multiple2.html#cb29-29" tabindex="-1"></a><span class="co"># BF model</span></span>
<span id="cb29-30"><a href="multiple2.html#cb29-30" tabindex="-1"></a>BF_screen_time_with_interaction <span class="ot">&lt;-</span></span>
<span id="cb29-31"><a href="multiple2.html#cb29-31" tabindex="-1"></a>  <span class="fu">lmBF</span>(screen_time <span class="sc">~</span> anxiety_score <span class="sc">+</span> education <span class="sc">+</span> anxiety_score<span class="sc">*</span>education, <span class="at">data =</span> <span class="fu">data.frame</span>(mentalh))</span>
<span id="cb29-32"><a href="multiple2.html#cb29-32" tabindex="-1"></a></span>
<span id="cb29-33"><a href="multiple2.html#cb29-33" tabindex="-1"></a><span class="co"># Adj R-square difference</span></span>
<span id="cb29-34"><a href="multiple2.html#cb29-34" tabindex="-1"></a><span class="fl">0.06</span> <span class="sc">-</span> <span class="fl">0.06</span></span>
<span id="cb29-35"><a href="multiple2.html#cb29-35" tabindex="-1"></a></span>
<span id="cb29-36"><a href="multiple2.html#cb29-36" tabindex="-1"></a><span class="co"># Compare BFs</span></span>
<span id="cb29-37"><a href="multiple2.html#cb29-37" tabindex="-1"></a>BF_screen_time_with_interaction <span class="sc">/</span> BF_screen_time_no_interaction</span>
<span id="cb29-38"><a href="multiple2.html#cb29-38" tabindex="-1"></a></span>
<span id="cb29-39"><a href="multiple2.html#cb29-39" tabindex="-1"></a><span class="co"># There&#39;s no evidence for the interaction, </span></span>
<span id="cb29-40"><a href="multiple2.html#cb29-40" tabindex="-1"></a><span class="co"># therefore assume additive model</span></span>
<span id="cb29-41"><a href="multiple2.html#cb29-41" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb29-42"><a href="multiple2.html#cb29-42" tabindex="-1"></a><span class="co"># BF of unique contribution of anxiety_score in model with education</span></span>
<span id="cb29-43"><a href="multiple2.html#cb29-43" tabindex="-1"></a><span class="co"># This is the BF for model with both anxiety AND education,</span></span>
<span id="cb29-44"><a href="multiple2.html#cb29-44" tabindex="-1"></a><span class="co"># divided by the BF for the model where anxiety is left out</span></span>
<span id="cb29-45"><a href="multiple2.html#cb29-45" tabindex="-1"></a>BF_screen_time_no_interaction <span class="sc">/</span> <span class="fu">lmBF</span>(screen_time <span class="sc">~</span> education, <span class="at">data =</span> <span class="fu">data.frame</span>(mentalh))</span>
<span id="cb29-46"><a href="multiple2.html#cb29-46" tabindex="-1"></a></span>
<span id="cb29-47"><a href="multiple2.html#cb29-47" tabindex="-1"></a><span class="co"># BF of unique contribution of education in model with anxiety_score</span></span>
<span id="cb29-48"><a href="multiple2.html#cb29-48" tabindex="-1"></a><span class="co"># This is the BF for model with both anxiety AND education,</span></span>
<span id="cb29-49"><a href="multiple2.html#cb29-49" tabindex="-1"></a><span class="co"># divided by the BF for the model where education is left out</span></span>
<span id="cb29-50"><a href="multiple2.html#cb29-50" tabindex="-1"></a>BF_screen_time_no_interaction <span class="sc">/</span> <span class="fu">lmBF</span>(screen_time <span class="sc">~</span> anxiety_score, <span class="at">data =</span> <span class="fu">data.frame</span>(mentalh))</span></code></pre></div>
</div>
<div class="webex-solution">
<button>
Storing R<sup>2</sup> values in variables
</button>
<p>It's possible to store R<sup>2</sup> values in variables. This can be handy if referring to them again in calculations, or if you want greater precision.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="multiple2.html#cb30-1" tabindex="-1"></a><span class="co"># Store adj r-sq for model with no interaction</span></span>
<span id="cb30-2"><a href="multiple2.html#cb30-2" tabindex="-1"></a>rsq_no <span class="ot">&lt;-</span> <span class="fu">glance</span>(screen_time_no_interaction)<span class="sc">$</span>adj.r.squared</span>
<span id="cb30-3"><a href="multiple2.html#cb30-3" tabindex="-1"></a></span>
<span id="cb30-4"><a href="multiple2.html#cb30-4" tabindex="-1"></a><span class="co"># look at rsq</span></span>
<span id="cb30-5"><a href="multiple2.html#cb30-5" tabindex="-1"></a>rsq_no</span>
<span id="cb30-6"><a href="multiple2.html#cb30-6" tabindex="-1"></a></span>
<span id="cb30-7"><a href="multiple2.html#cb30-7" tabindex="-1"></a></span>
<span id="cb30-8"><a href="multiple2.html#cb30-8" tabindex="-1"></a><span class="co"># Store adj r-sq for model with interaction</span></span>
<span id="cb30-9"><a href="multiple2.html#cb30-9" tabindex="-1"></a>rsq_with <span class="ot">&lt;-</span> <span class="fu">glance</span>(screen_time_with_interaction)<span class="sc">$</span>adj.r.squared</span>
<span id="cb30-10"><a href="multiple2.html#cb30-10" tabindex="-1"></a></span>
<span id="cb30-11"><a href="multiple2.html#cb30-11" tabindex="-1"></a><span class="co"># look at rsq</span></span>
<span id="cb30-12"><a href="multiple2.html#cb30-12" tabindex="-1"></a>rsq_with</span>
<span id="cb30-13"><a href="multiple2.html#cb30-13" tabindex="-1"></a></span>
<span id="cb30-14"><a href="multiple2.html#cb30-14" tabindex="-1"></a><span class="co"># work out change in adj R^2^ as a result of adding the interaction </span></span>
<span id="cb30-15"><a href="multiple2.html#cb30-15" tabindex="-1"></a>rsq_with <span class="sc">-</span> rsq_no</span></code></pre></div>
<p>Interestingly the change in adjusted R<sup>2</sup> is negative here. Remember that this is because the calculation of adjusted R<sup>2</sup> adjusts R<sup>2</sup> downwards, taking into account the additional predictor in the model. Performing the calculation with the non-adjusted R<sup>2</sup> values returns a (very small) positive number.</p>
</div>
</div>
<p><br />
</p>
</div>
<div id="further-knowledge" class="section level2 hasAnchor" number="4.9">
<h2><span class="header-section-number">4.9</span> Further knowledge<a href="multiple2.html#further-knowledge" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="moderation" class="section level3 hasAnchor" number="4.9.1">
<h3><span class="header-section-number">4.9.1</span> Moderation<a href="multiple2.html#moderation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="webex-solution">
<button>
Moderation
</button>
<p>The analysis that we've performed with <code>attitude</code> and <code>group</code> in this session is sometimes referred to as a test of moderation (Baron &amp; Kenny, 1986).</p>
<div class="tip">
<p>Moderation is when the relationship between two variables changes as a function of a third variable.</p>
</div>
<p><br />
</p>
<p>Altenmuller et al. (2021) concluded that participants' <code>attitude</code> <em>moderated</em> "the effect of a researcher disclosing being personally <code>affected</code> (vs. <code>not affected</code> ) by their own research on participants' <code>trustworthiness</code> ascriptions regarding the research". That is, <code>attitude</code> moderates the effect of <code>group</code> on <code>trustworthiness</code>.</p>
<p>It could also be said that the effect of a researcher saying that they are personally affected by their own research moderates the relationship between <code>attitude</code> and <code>trustworthiness</code> (or <code>credibility</code>). That is, the <code>group</code> moderates the relationship between <code>attitude</code> and <code>trustworthiness</code>. A relationship is present when the researcher says they are affected, but absent when they say they are not affected.</p>
<p>Which variable is said to be the <em>moderator</em> variable appears to be down to the choice of the researcher and the context of the research.</p>
<p>If we don't find evidence for the interaction term, then we don't have evidence that one variable moderates the relationship between the other two. Instead, researchers may say that there is <em>an additive effect of both predictors on the outcome variable</em>. The absence of an interaction indicates that the regression lines for each group do not differ (i.e., the lines for each group in a scatterplot are statistically parallel to one another).</p>
</div>
<p><br />
</p>
</div>
<div id="coefficients" class="section level3 hasAnchor" number="4.9.2">
<h3><span class="header-section-number">4.9.2</span> Coefficients<a href="multiple2.html#coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Only for those wanting a deeper understanding.</p>
<div class="webex-solution">
<button>
Coefficients
</button>
<p>If we obtain the coefficients for the full regression model (with the interaction), we can write out the regression equation:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="multiple2.html#cb31-1" tabindex="-1"></a><span class="fu">lm</span>(trustworthiness <span class="sc">~</span> attitude <span class="sc">+</span> group <span class="sc">+</span> attitude<span class="sc">*</span>group, <span class="at">data =</span> trust_data)</span></code></pre></div>
<p><br />
</p>
<p><span class="math inline">\(Predicted\ outcome = a + b_1X_1 + b_2X_2 + b_3X_1X_2\)</span></p>
<p>So,</p>
<p><span class="math inline">\(Predicted\ trustworthiness = 3.96 + 0.18(attitude) + 1.13(group) - 0.28(attitude\times group)\)</span></p>
<p><br />
</p>
<p>From this equation, we can derive the simple regression equations for each group.</p>
<p><br />
</p>
<p>As we saw in the previous session, behind the scenes, R uses <em>dummy coding</em> to code the two levels of the categorical variable (i.e., coding levels of a categorical variable with 0s and 1s). It uses 0s to code the <code>affected</code> group and 1s to code the <code>not_affected</code> group. It does it this way because it assigns 0s and 1s alphabetically.</p>
<p><br />
</p>
<p>Thus, taking the regression equation and substituting <code>group</code> = 0 for the <code>affected</code> group:</p>
<p><span class="math display">\[
\begin{align}
Predicted\ trustworthiness    &amp;= 3.96 + 0.18(attitude) + (1.13\times0) - 0.28(attitude\times0)\\
                              &amp;= 3.96 + 0.18(attitude) + 0 - 0 \\
                              &amp;= 3.96 + 0.18(attitude)
\end{align}
\]</span>
The intercept (3.96) and slope (0.18) in this simple regression equation match those obtained for the <code>affected</code> group in the earlier simple slopes analysis.</p>
<p><br />
</p>
<p>Next, taking the full regression equation and substituting <code>group</code> = 1 for the <code>not_affected</code> group:</p>
<p><span class="math display">\[
\begin{align}
Predicted\ trustworthiness    &amp;= 3.96 + 0.18(attitude) + (1.13\times1) - 0.28(attitude\times1)\\
                              &amp;= 3.96 + 0.18(attitude) + 1.13 - 0.28(attitude) \\
                              &amp;= 5.09 + 0.18(attitude) - 0.28(attitude) \\
                              &amp;= 5.09 -0.10(attitude)
\end{align}
\]</span></p>
<p>The intercept (5.09) and slope (-0.10) in this simple regression correspond to those we obtained for the <code>not_affected</code> group in the earlier simple slopes analysis.</p>
<p>In sum, when one of the predictors is dichotomous, it is possible to derive the simple regression equation for each level of that predictor from the regression equation for the model with the interaction term included.</p>
</div>
<p><br />
</p>
</div>
<div id="centering" class="section level3 hasAnchor" number="4.9.3">
<h3><span class="header-section-number">4.9.3</span> Centering<a href="multiple2.html#centering" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Again, only for those wanting deeper knowledge.</p>
<div class="webex-solution">
<button>
Centering
</button>
<p>When testing for moderation effects, it is common to <em>center</em> the predictor variables prior to the analysis. (Indeed, Altenmuller et al. (2021) centered <code>attitude</code> prior to running their analyses.) Centering is where you subtract the mean of a variable from every score of that variable. For example, to center the <code>attitude</code> scores, we'd obtain the mean of <code>attitude</code>, and then subtract that value from each of our <code>attitude</code> scores. Thus, a participant with a score of 0 on the centered attitude score would therefore have an attitude value that is equal to the mean.</p>
<p>Centering is usually performed to help increase the interpretability of the coefficients of the predictor variables in a model with an interaction. It can also help to reduce the chances of multicollinearity between the predictor variables and the interaction term. Multicollinearity can occur because the interaction term is derived from the individual predictors themselves (by multiplying them together).</p>
<p><code>scale()</code> can be used to center variables automatically. Set the option <code>center = TRUE</code> to center the variable. Setting the option <code>scale = TRUE</code> would also standardise the variable (i.e., divide each score by the standard deviation, to create <em>z</em>-scores), so <code>scale = FALSE</code> means that we won't also standardise the scores:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="multiple2.html#cb32-1" tabindex="-1"></a><span class="co"># center the attitude scores</span></span>
<span id="cb32-2"><a href="multiple2.html#cb32-2" tabindex="-1"></a><span class="co"># use mutate() to create a new variable in trust_data</span></span>
<span id="cb32-3"><a href="multiple2.html#cb32-3" tabindex="-1"></a><span class="co"># called attitude_centered</span></span>
<span id="cb32-4"><a href="multiple2.html#cb32-4" tabindex="-1"></a>trust_data <span class="ot">&lt;-</span> </span>
<span id="cb32-5"><a href="multiple2.html#cb32-5" tabindex="-1"></a>  trust_data <span class="sc">%&gt;%</span> </span>
<span id="cb32-6"><a href="multiple2.html#cb32-6" tabindex="-1"></a>  <span class="fu">mutate</span>( <span class="at">attitude_centered =</span> <span class="fu">scale</span>(attitude, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">FALSE</span>)[,<span class="dv">1</span>] )</span>
<span id="cb32-7"><a href="multiple2.html#cb32-7" tabindex="-1"></a></span>
<span id="cb32-8"><a href="multiple2.html#cb32-8" tabindex="-1"></a><span class="co"># compare the means to check that centered scores have mean of 0</span></span>
<span id="cb32-9"><a href="multiple2.html#cb32-9" tabindex="-1"></a>trust_data <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="fu">mean</span>(attitude), <span class="fu">mean</span>(attitude_centered))</span></code></pre></div>
<p>Before centering, the mean of the <code>attitude</code> scores was 4.26. After centering, the mean (of <code>attitude_centered</code>) is 0, or close enough to zero, being 4.08 x 10<sup>-16</sup>, more precisely because there's some rounding error along the way.</p>
<p><br />
</p>
<p>Now re-run the analysis using <code>attitude_centered</code> in place of <code>attitude</code> and look at adjusted R<sup>2</sup> and the BF:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="multiple2.html#cb33-1" tabindex="-1"></a><span class="co"># full model with attitude_centered</span></span>
<span id="cb33-2"><a href="multiple2.html#cb33-2" tabindex="-1"></a>full_centered <span class="ot">&lt;-</span> <span class="fu">lm</span>(trustworthiness <span class="sc">~</span> attitude_centered <span class="sc">+</span> group <span class="sc">+</span> attitude_centered<span class="sc">*</span>group, <span class="at">data =</span> trust_data)</span>
<span id="cb33-3"><a href="multiple2.html#cb33-3" tabindex="-1"></a></span>
<span id="cb33-4"><a href="multiple2.html#cb33-4" tabindex="-1"></a><span class="co"># R-squared</span></span>
<span id="cb33-5"><a href="multiple2.html#cb33-5" tabindex="-1"></a><span class="fu">glance</span>(full_centered)</span>
<span id="cb33-6"><a href="multiple2.html#cb33-6" tabindex="-1"></a></span>
<span id="cb33-7"><a href="multiple2.html#cb33-7" tabindex="-1"></a><span class="co"># BF</span></span>
<span id="cb33-8"><a href="multiple2.html#cb33-8" tabindex="-1"></a><span class="fu">lmBF</span>(trustworthiness <span class="sc">~</span> attitude_centered <span class="sc">+</span> group <span class="sc">+</span> attitude_centered<span class="sc">*</span>group, </span>
<span id="cb33-9"><a href="multiple2.html#cb33-9" tabindex="-1"></a>     <span class="at">data =</span> <span class="fu">data.frame</span>(trust_data))</span></code></pre></div>
<ul>
<li>The adjusted R<sup>2</sup> for the full model is <input class='webex-solveme nospaces' size='4' data-answer='["0.05"]'/>, which is the same as we found previously when <code>attitude</code> was not centered.</li>
<li>The BF for the model is approximately 33, which is the same as we found previously with the non-centered version of <code>attitude</code>.</li>
</ul>
<p>Thus, centering predictors does not affect the adjusted R<sup>2</sup> or evidence for the model. This is because subtracting the mean from a variable is equivalent to a linear transformation and this does not affect the association.</p>
<p><br />
</p>
<p><br />
</p>
<p>To go even further, centering affects the values of the coefficients of the individual predictors in the model, but has no effect on the coefficient for the interaction.</p>
<p><br />
</p>
<p>When <code>attitude</code> wasn't centered, the regression equation was:</p>
<p><span class="math inline">\(Predicted\ trustworthiness = 3.96 + 0.18(attitude) + 1.13(group) - 0.28(attitude\times group)\)</span></p>
<p><br />
</p>
<p>Using <code>attitude_centered</code>, the coefficients for the regression equation are obtained from:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="multiple2.html#cb34-1" tabindex="-1"></a>full_centered</span></code></pre></div>
<p>And so the regression equation is:</p>
<p><span class="math inline">\(Predicted\ trustworthiness = 4.75 + 0.18(attitude) -0.06(group) - 0.28(attitude\times group)\)</span></p>
<p>Notice that the intercept has changed and so has the coefficient for <code>group</code>.</p>
<p><br />
</p>
<p>As before, to obtain the simple regression equations for each <code>group</code> we can once again substitute in the dummy codes for <code>group</code>. Thus, for the <code>affected</code> group:</p>
<p><span class="math display">\[
\begin{align}
Predicted\ trustworthiness    &amp;= 4.75 + 0.18(attitude) - (0.06\times0) - 0.28(attitude\times0)\\
                              &amp;= 4.75 + 0.18(attitude) + 0 - 0 \\
                              &amp;= 4.75 + 0.18(attitude)
\end{align}
\]</span></p>
<p>For the <code>not_affected</code> group:</p>
<p><span class="math display">\[
\begin{align}
Predicted\ trustworthiness    &amp;= 4.75 + 0.18(attitude) - (0.06\times1) - 0.28(attitude\times0)\\
                              &amp;= 4.75 + 0.18(attitude) -0.06 - 0.28(attitude) \\
                              &amp;= 4.69 + 0.18(attitude) - 0.28(attitude) \\
                              &amp;= 4.69 -0.10(attitude)
\end{align}
\]</span>
The values in the simple regression equations come out slightly differently when attitude is centered, but the direction on the sign of the coefficient for <code>attitude</code> is the same.</p>
<p><br />
</p>
<p>In sum, centering of predictor variables is often performed in moderation analyses, but does not affect the variance explained by the model, nor the evidence (i.e., the BF) for the model, nor the direction (positive/negative) of the associations in the simple slopes analyses (because it doesn't change the slope). Centering can be desirable to aid interpretation of the coefficients of individual predictors and can reduce multicollinearity.</p>
</div>
<p><br />
</p>
</div>
</div>
<div id="summary-2" class="section level2 hasAnchor" number="4.10">
<h2><span class="header-section-number">4.10</span> Summary<a href="multiple2.html#summary-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>A multiple regression model can consist of a mixture of continuous and categorical predictors,</li>
<li>Predictors may have a combined effect in explaining the outcome variable. Evidence for this <em>interaction effect</em> can be examined by adding the interaction term to the model, i.e., with <code>lm(outcome ~ predictor1 + predictor2 + predictor1*predictor2)</code></li>
<li>With a dichotomous categorical variable, the interaction implies that the slopes of the simple regressions of <code>outcome ~ continuous_predictor</code> are different. This can be examined with a simple slopes analysis.</li>
<li>The interaction implies that the relationship between the outcome and continuous predictor are different in each group.</li>
</ul>
<p><br />
</p>
</div>
<div id="references-3" class="section level2 hasAnchor" number="4.11">
<h2><span class="header-section-number">4.11</span> References<a href="multiple2.html#references-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Altenmuller M.S., Lange L.L., Gollwitzer M. (2021). When research is me-search: How researchers’ motivation to pursue a topic affects laypeople’s trust in science. <em>PLoS ONE</em> <em>16</em>(7): e0253911. <a href="https://doi.org/10.1371/journal.pone.0253911" class="uri">https://doi.org/10.1371/journal.pone.0253911</a></p>
<p>Baron, R. M., &amp; Kenny, D. A. (1986). The moderator–mediator variable distinction in social psychological research: Conceptual, strategic, and statistical considerations. <em>Journal of Personality and Social Psychology</em>, <em>51</em>(6), 1173. <a href="https://psycnet.apa.org/doi/10.1037/0022-3514.51.6.1173" class="uri">https://psycnet.apa.org/doi/10.1037/0022-3514.51.6.1173</a></p>

</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="anova1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
